package com.jetbrains.youtrackdb.internal.annotations.gremlin.dsl;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.zip.CRC32;
import javax.annotation.Nullable;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 * Helper for DSL source digest (CRC32) used to decide whether to skip regeneration.
 * Extracted for unit testing.
 */
public final class GremlinDslDigestHelper {

  private static final Logger log = LoggerFactory.getLogger(GremlinDslDigestHelper.class);

  /** Comment line prefix written into generated files; stored digest follows. */
  public static final String DSL_SOURCE_DIGEST_PREFIX =
      "Generated by GremlinDslProcessor; DSL source digest: ";

  private GremlinDslDigestHelper() {
  }

  /**
   * CRC32 of file content (hex string) with line endings normalized to LF.
   * Normalization ensures the digest is identical on Windows (CRLF) and Unix (LF),
   * so that generated files committed from one OS are not needlessly regenerated on another.
   * Returns empty string if the file cannot be read.
   */
  public static String computeSourceDigest(final Path sourcePath) {
    try {
      var raw = Files.readAllBytes(sourcePath);
      var normalized = new String(raw, StandardCharsets.UTF_8).replace("\r\n", "\n")
          .getBytes(StandardCharsets.UTF_8);
      var crc = new CRC32();
      crc.update(normalized);
      return Long.toHexString(crc.getValue());
    } catch (IOException e) {
      log.warn("Cannot read DSL source for digest: {}", sourcePath, e);
      return "";
    }
  }

  /**
   * Reads the stored DSL source digest from a generated file's comment line.
   * Returns null if the file does not exist or the comment line is missing/invalid.
   */
  @Nullable
  public static String getStoredDigestFromGeneratedFile(final Path generatedPath) {
    if (!Files.isRegularFile(generatedPath)) {
      return null;
    }
    try {
      return getStoredDigestFromContent(Files.readString(generatedPath));
    } catch (IOException e) {
      log.warn("Cannot read stored digest from: {}", generatedPath, e);
      return null;
    }
  }

  /**
   * Extracts the stored DSL source digest from the content of a generated file.
   * Returns null if the digest comment line is missing.
   */
  @Nullable
  public static String getStoredDigestFromContent(final CharSequence content) {
    var text = content.toString();
    var idx = text.indexOf(DSL_SOURCE_DIGEST_PREFIX);
    if (idx < 0) {
      return null;
    }
    var start = idx + DSL_SOURCE_DIGEST_PREFIX.length();
    var end = text.indexOf('\n', start);
    if (end < 0) {
      end = text.length();
    }
    return text.substring(start, end).trim();
  }
}
