/*
 * Originally generated by JJTree from YouTrackDBSql.jjt, but now maintained
 * manually — contains hand-written ANALYZE INDEX execution logic.
 */
package com.jetbrains.youtrackdb.internal.core.sql.parser;

import com.jetbrains.youtrackdb.internal.core.command.CommandContext;
import com.jetbrains.youtrackdb.internal.core.db.DatabaseSessionEmbedded;
import com.jetbrains.youtrackdb.internal.core.exception.CommandExecutionException;
import com.jetbrains.youtrackdb.internal.core.index.Index;
import com.jetbrains.youtrackdb.internal.core.index.engine.HistogramSnapshot;
import com.jetbrains.youtrackdb.internal.core.sql.executor.ResultInternal;
import com.jetbrains.youtrackdb.internal.core.sql.executor.resultset.ExecutionStream;
import java.util.ArrayList;
import java.util.Map;
import java.util.Objects;
import javax.annotation.Nullable;

public class SQLAnalyzeIndexStatement extends SQLSimpleExecStatement {

  protected boolean all = false;
  protected SQLIndexName name;

  public SQLAnalyzeIndexStatement(int id) {
    super(id);
  }

  public SQLAnalyzeIndexStatement(YouTrackDBSql p, int id) {
    super(p, id);
  }

  @Override
  public ExecutionStream executeSimple(CommandContext ctx) {
    final var session = ctx.getDatabaseSession();

    if (all) {
      // Analyze ALL indexes (not just automatic ones, unlike REBUILD INDEX *).
      // Histogram analysis is read-only and cheap, so there is no reason to
      // restrict it to automatic indexes.
      var results = new ArrayList<ResultInternal>();
      for (var idx : session.getSharedContext().getIndexManager().getIndexes()) {
        results.add(buildResult(session, idx));
      }
      return ExecutionStream.resultIterator(results.iterator());
    } else {
      final var idx =
          session.getSharedContext().getIndexManager().getIndex(name.getValue());
      if (idx == null) {
        throw new CommandExecutionException(
            session, "Index '" + name + "' not found");
      }
      return ExecutionStream.singleton(buildResult(session, idx));
    }
  }

  private ResultInternal buildResult(
      DatabaseSessionEmbedded session, Index idx) {
    @Nullable var snapshot = idx.analyzeHistogram(session);
    var result = new ResultInternal(session);
    result.setProperty("operation", "analyze index");
    result.setProperty("indexName", idx.getName());
    if (snapshot != null) {
      result.setProperty("totalCount", snapshot.stats().totalCount());
      result.setProperty("distinctCount", snapshot.stats().distinctCount());
      result.setProperty("nullCount", snapshot.stats().nullCount());
      result.setProperty("bucketCount",
          snapshot.histogram() != null
              ? snapshot.histogram().boundaries().length - 1
              : 0);
    } else {
      result.setProperty("totalCount", 0L);
      result.setProperty("distinctCount", 0L);
      result.setProperty("nullCount", 0L);
      result.setProperty("bucketCount", 0);
    }
    return result;
  }

  @Override
  public void toString(Map<Object, Object> params, StringBuilder builder) {
    builder.append("ANALYZE INDEX ");
    if (all) {
      builder.append("*");
    } else {
      name.toString(params, builder);
    }
  }

  @Override
  public void toGenericStatement(StringBuilder builder) {
    builder.append("ANALYZE INDEX ");
    if (all) {
      builder.append("*");
    } else {
      name.toGenericStatement(builder);
    }
  }

  @Override
  public SQLAnalyzeIndexStatement copy() {
    var result = new SQLAnalyzeIndexStatement(-1);
    result.all = all;
    result.name = name == null ? null : name.copy();
    return result;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    var that = (SQLAnalyzeIndexStatement) o;
    if (all != that.all) {
      return false;
    }
    return Objects.equals(name, that.name);
  }

  @Override
  public int hashCode() {
    var result = (all ? 1 : 0);
    result = 31 * result + (name != null ? name.hashCode() : 0);
    return result;
  }
}
