/* Generated By:JJTree: Do not edit this line. SQLArrayConcatExpression.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=O,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.jetbrains.youtrackdb.internal.core.sql.parser;

import com.jetbrains.youtrackdb.internal.common.collection.MultiValue;
import com.jetbrains.youtrackdb.internal.core.command.CommandContext;
import com.jetbrains.youtrackdb.internal.core.db.DatabaseSessionEmbedded;
import com.jetbrains.youtrackdb.internal.core.db.record.RecordElement;
import com.jetbrains.youtrackdb.internal.core.db.record.TrackedMultiValue;
import com.jetbrains.youtrackdb.internal.core.db.record.record.Identifiable;
import com.jetbrains.youtrackdb.internal.core.exception.CommandExecutionException;
import com.jetbrains.youtrackdb.internal.core.metadata.schema.PropertyTypeInternal;
import com.jetbrains.youtrackdb.internal.core.query.Result;
import com.jetbrains.youtrackdb.internal.core.sql.executor.ResultInternal;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Set;
import java.util.stream.Collectors;
import javax.annotation.Nullable;

public class SQLArrayConcatExpression extends SimpleNode {

  protected List<SQLArrayConcatExpressionElement> childExpressions = new ArrayList<>();

  public SQLArrayConcatExpression(int id) {
    super(id);
  }

  public SQLArrayConcatExpression(YouTrackDBSql p, int id) {
    super(p, id);
  }

  public List<SQLArrayConcatExpressionElement> getChildExpressions() {
    return childExpressions;
  }

  public void setChildExpressions(List<SQLArrayConcatExpressionElement> childExpressions) {
    this.childExpressions = childExpressions;
  }

  public void addChildExpression(SQLArrayConcatExpressionElement elem) {
    this.childExpressions.add(elem);
  }

  @Nullable
  public static Object apply(Object left, Object right, DatabaseSessionEmbedded session) {
    if (left == null && right == null) {
      return null;
    }

    if (right == null) {
      if (MultiValue.isMultiValue(left)) {
        return left;
      } else {
        return Collections.singletonList(left);
      }
    }

    if (left == null) {
      if (MultiValue.isMultiValue(right)) {
        return right;
      } else {
        return Collections.singletonList(right);
      }
    }

    List<Object> result = null;
    if (left instanceof TrackedMultiValue<?, ?> trackedMultiValue) {
      var type = PropertyTypeInternal.getTypeByValue(trackedMultiValue);
      left = type.copy(trackedMultiValue, session);

      if (left instanceof List<?> list) {
        //noinspection unchecked
        result = (List<Object>) list;
      }
    }

    if (right instanceof TrackedMultiValue<?, ?> trackedMultiValue) {
      var type = PropertyTypeInternal.getTypeByValue(trackedMultiValue);
      right = type.copy(trackedMultiValue, session);
      if (result == null && right instanceof List<?> list) {
        //noinspection unchecked
        result = (List<Object>) list;
      }
    }

    if (result == null) {
      result = new ArrayList<>();
    }

    if (result != left) {
      addValueToResultList(left, session, result);
    }

    if (result != right) {
      addValueToResultList(right, session, result);
    }

    return result;
  }

  private static void addValueToResultList(Object value, DatabaseSessionEmbedded session,
      List<Object> result) {
    if (MultiValue.isMultiValue(value)) {
      var leftIter = MultiValue.getMultiValueIterator(value);
      while (leftIter.hasNext()) {
        if (result instanceof TrackedMultiValue<?, ?> trackedMultiValue) {
          var item = leftIter.next();
          var type = PropertyTypeInternal.getTypeByValue(item);
          if (type == null) {
            throw new CommandExecutionException(session,
                "Cannot concatenate values of not supported types : " + item.getClass() + " : "
                    + item);
          }
          if (item instanceof RecordElement recordElement) {
            var copy = type.copy(recordElement, session);
            result.add(copy);
          } else {
            var converted = type.convert(item, session);
            result.add(converted);
          }
        } else {
          result.add(leftIter.next());
        }
      }
    } else {
      result.add(value);
    }
  }

  public Object execute(Identifiable iCurrentRecord, CommandContext ctx) {
    var session = ctx.getDatabaseSession();
    var result = childExpressions.getFirst().execute(iCurrentRecord, ctx);
    for (var i = 1; i < childExpressions.size(); i++) {
      result = apply(result, childExpressions.get(i).execute(iCurrentRecord, ctx), session);
    }
    return result;
  }

  public Object execute(Result iCurrentRecord, CommandContext ctx) {
    var session = ctx.getDatabaseSession();
    var result = childExpressions.getFirst().execute(iCurrentRecord, ctx);
    for (var i = 1; i < childExpressions.size(); i++) {
      result = apply(result, childExpressions.get(i).execute(iCurrentRecord, ctx), session);
    }
    return result;
  }

  public boolean isEarlyCalculated(CommandContext ctx) {
    for (var element : childExpressions) {
      if (!element.isEarlyCalculated(ctx)) {
        return false;
      }
    }
    return true;
  }

  protected boolean supportsBasicCalculation() {
    for (var expr : this.childExpressions) {
      if (!expr.supportsBasicCalculation()) {
        return false;
      }
    }
    return true;
  }

  public boolean needsAliases(Set<String> aliases) {
    for (var expr : childExpressions) {
      if (expr.needsAliases(aliases)) {
        return true;
      }
    }
    return false;
  }

  public boolean isAggregate(DatabaseSessionEmbedded session) {
    for (var expr : this.childExpressions) {
      if (expr.isAggregate(session)) {
        return true;
      }
    }
    return false;
  }

  public SimpleNode splitForAggregation(DatabaseSessionEmbedded session,
      AggregateProjectionSplit aggregateProj) {
    if (isAggregate(session)) {
      throw new CommandExecutionException(session,
          "Cannot use aggregate functions in array concatenation");
    } else {
      return this;
    }
  }


  @Override
  public SQLArrayConcatExpression copy() {
    var result = new SQLArrayConcatExpression(-1);
    this.childExpressions.forEach(x -> result.childExpressions.add(x.copy()));
    return result;
  }

  public void extractSubQueries(SubQueryCollector collector) {
    for (var expr : this.childExpressions) {
      expr.extractSubQueries(collector);
    }
  }

  public boolean refersToParent() {
    for (var expr : this.childExpressions) {
      if (expr.refersToParent()) {
        return true;
      }
    }
    return false;
  }

  @Nullable
  public List<String> getMatchPatternInvolvedAliases() {
    List<String> result = new ArrayList<String>();
    for (var exp : childExpressions) {
      var x = exp.getMatchPatternInvolvedAliases();
      if (x != null) {
        result.addAll(x);
      }
    }
    if (result.isEmpty()) {
      return null;
    }
    return result;
  }

  @Override
  public void toString(Map<Object, Object> params, StringBuilder builder) {
    for (var i = 0; i < childExpressions.size(); i++) {
      if (i > 0) {
        builder.append(" || ");
      }
      childExpressions.get(i).toString(params, builder);
    }
  }

  @Override
  public void toGenericStatement(StringBuilder builder) {
    for (var i = 0; i < childExpressions.size(); i++) {
      if (i > 0) {
        builder.append(" || ");
      }
      childExpressions.get(i).toGenericStatement(builder);
    }
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }

    var that = (SQLArrayConcatExpression) o;

    return Objects.equals(childExpressions, that.childExpressions);
  }

  @Override
  public int hashCode() {
    return childExpressions != null ? childExpressions.hashCode() : 0;
  }

  public Result serialize(DatabaseSessionEmbedded session) {
    var result = new ResultInternal(session);
    if (childExpressions != null) {
      result.setProperty(
          "childExpressions",
          childExpressions.stream().map(x -> x.serialize(session)).collect(Collectors.toList()));
    }
    return result;
  }

  public void deserialize(Result fromResult) {

    if (fromResult.getProperty("childExpressions") != null) {
      List<Result> ser = fromResult.getProperty("childExpressions");
      childExpressions = new ArrayList<>();
      for (var r : ser) {
        var exp = new SQLArrayConcatExpressionElement(-1);
        exp.deserialize(r);
        childExpressions.add(exp);
      }
    }
  }

  public boolean isCacheable(DatabaseSessionEmbedded session) {
    for (var exp : childExpressions) {
      if (!exp.isCacheable(session)) {
        return false;
      }
    }
    return true;
  }

  public boolean varMightBeInUse(String varName) {
    for (var exp : childExpressions) {
      if (exp.varMightBeInUse(varName)) {
        return true;
      }
    }
    return false;
  }
}
/* JavaCC - OriginalChecksum=8d976a02f84460bf21c4304009135345 (do not edit this line) */
