/* Generated By:JJTree: Do not edit this line. SQLArraySelector.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=O,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.jetbrains.youtrackdb.internal.core.sql.parser;

import com.jetbrains.youtrackdb.internal.core.command.CommandContext;
import com.jetbrains.youtrackdb.internal.core.db.DatabaseSessionEmbedded;
import com.jetbrains.youtrackdb.internal.core.db.record.record.Identifiable;
import com.jetbrains.youtrackdb.internal.core.query.Result;
import com.jetbrains.youtrackdb.internal.core.sql.executor.ResultInternal;
import java.lang.reflect.Array;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Set;
import javax.annotation.Nullable;

public class SQLArraySelector extends SimpleNode {

  protected SQLRid rid;
  protected SQLInputParameter inputParam;
  protected SQLExpression expression;
  protected SQLInteger integer;

  public SQLArraySelector(int id) {
    super(id);
  }

  public SQLArraySelector(YouTrackDBSql p, int id) {
    super(p, id);
  }

  @Override
  public void toString(Map<Object, Object> params, StringBuilder builder) {
    if (rid != null) {
      rid.toString(params, builder);
    } else if (inputParam != null) {
      inputParam.toString(params, builder);
    } else if (expression != null) {
      expression.toString(params, builder);
    } else if (integer != null) {
      integer.toString(params, builder);
    }
  }

  @Override
  public void toGenericStatement(StringBuilder builder) {
    if (rid != null) {
      rid.toGenericStatement(builder);
    } else if (inputParam != null) {
      inputParam.toGenericStatement(builder);
    } else if (expression != null) {
      expression.toGenericStatement(builder);
    } else if (integer != null) {
      integer.toGenericStatement(builder);
    }
  }

  @Nullable
  public Object getValue(Identifiable iCurrentRecord, CommandContext ctx) {
    Object result = null;
    if (inputParam != null) {
      result = inputParam.getValue(ctx.getInputParameters());
    } else if (expression != null) {
      result = expression.execute(iCurrentRecord, ctx);
    } else if (integer != null) {
      result = integer;
    }

    if (result == null) {
      return null;
    }
    if (result instanceof Number) {
      return ((Number) result).intValue();
    }
    return result;
  }

  @Nullable
  public Object getValue(Result iCurrentRecord, CommandContext ctx) {
    Object result = null;
    if (inputParam != null) {
      result = inputParam.getValue(ctx.getInputParameters());
    } else if (expression != null) {
      result = expression.execute(iCurrentRecord, ctx);
    } else if (integer != null) {
      result = integer;
    }

    if (result == null) {
      return null;
    }
    if (result instanceof Number) {
      return ((Number) result).intValue();
    }
    return result;
  }

  public boolean needsAliases(Set<String> aliases) {
    if (expression != null) {
      return expression.needsAliases(aliases);
    }
    return false;
  }

  @Override
  public SQLArraySelector copy() {
    var result = new SQLArraySelector(-1);

    result.rid = rid == null ? null : rid.copy();
    result.inputParam = inputParam == null ? null : inputParam.copy();
    result.expression = expression == null ? null : expression.copy();
    result.integer = integer == null ? null : integer.copy();

    return result;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }

    var that = (SQLArraySelector) o;

    if (!Objects.equals(rid, that.rid)) {
      return false;
    }
    if (!Objects.equals(inputParam, that.inputParam)) {
      return false;
    }
    if (!Objects.equals(expression, that.expression)) {
      return false;
    }
    return Objects.equals(integer, that.integer);
  }

  @Override
  public int hashCode() {
    var result = rid != null ? rid.hashCode() : 0;
    result = 31 * result + (inputParam != null ? inputParam.hashCode() : 0);
    result = 31 * result + (expression != null ? expression.hashCode() : 0);
    result = 31 * result + (integer != null ? integer.hashCode() : 0);
    return result;
  }

  public void extractSubQueries(SubQueryCollector collector) {
    if (expression != null) {
      expression.extractSubQueries(collector);
    }
  }

  public boolean refersToParent() {
    return expression != null && expression.refersToParent();
  }

  public void setValue(Result currentRecord, Object target, Object value, CommandContext ctx) {
    Object idx = null;
    if (this.rid != null) {
      idx = this.rid.toRecordId(currentRecord, ctx);
    } else if (inputParam != null) {
      idx = inputParam.getValue(ctx.getInputParameters());
    } else if (expression != null) {
      idx = expression.execute(currentRecord, ctx);
    } else if (integer != null) {
      idx = integer.getValue();
    }

    if (target instanceof Set && idx instanceof Number) {
      //noinspection unchecked
      setValue((Set<Object>) target, ((Number) idx).intValue(), value);
    } else if (target instanceof List && idx instanceof Number) {
      //noinspection unchecked
      setValue((List<Object>) target, ((Number) idx).intValue(), value);
    } else if (target instanceof Map) {
      //noinspection unchecked
      setValue((Map<Object, Object>) target, idx, value);
    } else if (target != null && target.getClass().isArray() && idx instanceof Number) {
      setArrayValue(target, ((Number) idx).intValue(), value);
    }
  }

  public static void setValue(List<Object> target, int idx, Object value) {
    var originalSize = target.size();
    for (var i = originalSize; i <= idx; i++) {
      if (i >= originalSize) {
        target.add(null);
      }
    }
    target.set(idx, value);
  }

  public static void setValue(Set<Object> target, int idx, Object value) {
    var result = new LinkedHashSet<>();
    var originalSize = target.size();
    var max = Math.max(idx, originalSize - 1);
    var targetIterator = target.iterator();
    for (var i = 0; i <= max; i++) {
      Object next = null;
      if (targetIterator.hasNext()) {
        next = targetIterator.next();
      }
      if (i == idx) {
        result.add(value);
      } else if (i < originalSize) {
        result.add(next);
      } else {
        result.add(null);
      }
      target.clear();
      target.addAll(result);
    }
  }

  public static void setValue(Map<Object, Object> target, Object idx, Object value) {
    target.put(idx, value);
  }

  private static void setArrayValue(Object target, int idx, Object value) {
    if (idx >= 0 && idx < Array.getLength(target)) {
      Array.set(target, idx, value);
    }
  }

  public Result serialize(DatabaseSessionEmbedded session) {
    var result = new ResultInternal(session);
    if (rid != null) {
      result.setProperty("rid", rid.serialize(session));
    }
    if (inputParam != null) {
      result.setProperty("inputParam", inputParam.serialize(session));
    }
    if (expression != null) {
      result.setProperty("expression", expression.serialize(session));
    }
    if (integer != null) {
      result.setProperty("integer", integer.serialize(session));
    }
    return result;
  }

  public void deserialize(Result fromResult) {
    if (fromResult.getProperty("rid") != null) {
      rid = new SQLRid(-1);
      rid.deserialize(fromResult.getProperty("rid"));
    }
    if (fromResult.getProperty("inputParam") != null) {
      inputParam = SQLInputParameter.deserializeFromOResult(fromResult.getProperty("inputParam"));
    }
    if (fromResult.getProperty("expression") != null) {
      expression = new SQLExpression(-1);
      expression.deserialize(fromResult.getProperty("expression"));
    }
    if (fromResult.getProperty("integer") != null) {
      integer = new SQLInteger(-1);
      integer.deserialize(fromResult.getProperty("integer"));
    }
  }
}
/* JavaCC - OriginalChecksum=f87a5543b1dad0fb5f6828a0663a7c9e (do not edit this line) */
