/* Generated By:JJTree: Do not edit this line. SQLAndBlock.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=O,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.jetbrains.youtrackdb.internal.core.sql.parser;

import com.jetbrains.youtrackdb.internal.core.command.CommandContext;
import com.jetbrains.youtrackdb.internal.core.db.DatabaseSessionEmbedded;
import com.jetbrains.youtrackdb.internal.core.db.record.record.Identifiable;
import com.jetbrains.youtrackdb.internal.core.metadata.schema.SchemaClassInternal;
import com.jetbrains.youtrackdb.internal.core.metadata.schema.schema.SchemaClass;
import com.jetbrains.youtrackdb.internal.core.query.Result;
import com.jetbrains.youtrackdb.internal.core.sql.executor.IndexSearchInfo;
import com.jetbrains.youtrackdb.internal.core.sql.executor.metadata.IndexCandidate;
import com.jetbrains.youtrackdb.internal.core.sql.executor.metadata.IndexFinder;
import com.jetbrains.youtrackdb.internal.core.sql.executor.metadata.MultipleIndexCanditate;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Set;
import javax.annotation.Nonnull;
import javax.annotation.Nullable;

public class SQLAndBlock extends SQLBooleanExpression {

  List<SQLBooleanExpression> subBlocks = new ArrayList<>();

  public SQLAndBlock(int id) {
    super(id);
  }

  public SQLAndBlock(YouTrackDBSql p, int id) {
    super(p, id);
  }

  @Override
  public boolean evaluate(Identifiable currentRecord, CommandContext ctx) {
    if (subBlocks == null) {
      return true;
    }

    for (var block : subBlocks) {
      if (!block.evaluate(currentRecord, ctx)) {
        return false;
      }
    }
    return true;
  }

  @Override
  public boolean evaluate(Result currentRecord, CommandContext ctx) {
    if (subBlocks == null) {
      return true;
    }

    for (var block : subBlocks) {
      if (!block.evaluate(currentRecord, ctx)) {
        return false;
      }
    }
    return true;
  }

  public List<SQLBooleanExpression> getSubBlocks() {
    return subBlocks;
  }

  public void setSubBlocks(List<SQLBooleanExpression> subBlocks) {
    this.subBlocks = subBlocks;
  }

  public void addSubBlock(SQLBooleanExpression block) {
    this.subBlocks.add(block);
  }

  @Override
  public void toString(Map<Object, Object> params, StringBuilder builder) {
    if (subBlocks == null || subBlocks.isEmpty()) {
      return;
    }
    var first = true;
    for (var expr : subBlocks) {
      if (!first) {
        builder.append(" AND ");
      }
      expr.toString(params, builder);
      first = false;
    }
  }

  @Override
  public void toGenericStatement(StringBuilder builder) {
    if (subBlocks == null || subBlocks.isEmpty()) {
      return;
    }
    var first = true;
    for (var expr : subBlocks) {
      if (!first) {
        builder.append(" AND ");
      }
      expr.toGenericStatement(builder);
      first = false;
    }
  }

  @Override
  protected boolean supportsBasicCalculation() {
    for (var expr : subBlocks) {
      if (!expr.supportsBasicCalculation()) {
        return false;
      }
    }
    return true;
  }

  @Override
  protected int getNumberOfExternalCalculations() {
    var result = 0;
    for (var expr : subBlocks) {
      result += expr.getNumberOfExternalCalculations();
    }
    return result;
  }

  @Override
  protected List<Object> getExternalCalculationConditions() {
    List<Object> result = new ArrayList<Object>();
    for (var expr : subBlocks) {
      result.addAll(expr.getExternalCalculationConditions());
    }
    return result;
  }

  @Override
  @Nullable
  public List<SQLBinaryCondition> getIndexedFunctionConditions(
      SchemaClass iSchemaClass, DatabaseSessionEmbedded session) {
    if (subBlocks == null) {
      return null;
    }
    List<SQLBinaryCondition> result = new ArrayList<SQLBinaryCondition>();
    for (var exp : subBlocks) {
      var sub = exp.getIndexedFunctionConditions(iSchemaClass, session);
      if (sub != null && !sub.isEmpty()) {
        result.addAll(sub);
      }
    }
    return result.isEmpty() ? null : result;
  }

  @Override
  public List<SQLAndBlock> flatten(CommandContext ctx, SchemaClassInternal schemaClass) {
    List<SQLAndBlock> result = new ArrayList<SQLAndBlock>();
    var first = true;
    for (var sub : subBlocks) {
      var subFlattened = sub.flatten(ctx, schemaClass);
      var oldResult = result;

      result = new ArrayList<>();
      for (var subAndItem : subFlattened) {
        if (first) {
          result.add(subAndItem);
        } else {
          for (var oldResultItem : oldResult) {
            var block = new SQLAndBlock(-1);
            block.subBlocks.addAll(oldResultItem.subBlocks);
            block.subBlocks.addAll(subAndItem.subBlocks);
            result.add(block);
          }
        }
      }
      first = false;
    }
    return result;
  }

  @Override
  public boolean needsAliases(Set<String> aliases) {
    for (var block : subBlocks) {
      if (block.needsAliases(aliases)) {
        return true;
      }
    }
    return false;
  }

  @Override
  public SQLAndBlock copy() {
    var result = new SQLAndBlock(-1);
    for (var exp : subBlocks) {
      result.subBlocks.add(exp.copy());
    }
    return result;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }

    var andBlock = (SQLAndBlock) o;

    return Objects.equals(subBlocks, andBlock.subBlocks);
  }

  @Override
  public int hashCode() {
    return subBlocks != null ? subBlocks.hashCode() : 0;
  }

  @Override
  public boolean isEmpty() {
    if (subBlocks.isEmpty()) {
      return true;
    }
    for (var block : subBlocks) {
      if (!block.isEmpty()) {
        return false;
      }
    }
    return true;
  }

  @Override
  public void extractSubQueries(SubQueryCollector collector) {
    for (var exp : subBlocks) {
      exp.extractSubQueries(collector);
    }
  }

  @Override
  public boolean refersToParent() {
    for (var exp : subBlocks) {
      if (exp.refersToParent()) {
        return true;
      }
    }
    return false;
  }

  @Nullable
  @Override
  public List<String> getMatchPatternInvolvedAliases() {
    List<String> result = new ArrayList<String>();
    for (var exp : subBlocks) {
      var x = exp.getMatchPatternInvolvedAliases();
      if (x != null) {
        result.addAll(x);
      }
    }
    return result.isEmpty() ? null : result;
  }

  @Override
  public void translateLuceneOperator() {
    subBlocks.forEach(SQLBooleanExpression::translateLuceneOperator);
  }

  @Override
  public boolean isCacheable(DatabaseSessionEmbedded session) {
    for (var exp : subBlocks) {
      if (!exp.isCacheable(session)) {
        return false;
      }
    }
    return true;
  }

  @Override
  public SQLBooleanExpression rewriteIndexChainsAsSubqueries(CommandContext ctx,
      SchemaClassInternal clazz) {
    for (var exp : subBlocks) {
      exp.rewriteIndexChainsAsSubqueries(ctx, clazz);
      // this is on purpose. Multiple optimizations in this case in an AND block can
      // lead to wrong results (no intersection)
      return this;
    }
    return this;
  }

  @Override
  public IndexCandidate findIndex(IndexFinder info, CommandContext ctx) {
    IndexCandidate result = null;
    for (var exp : subBlocks) {
      var singleResult = exp.findIndex(info, ctx);
      if (singleResult != null) {
        if (result != null) {
          if (result instanceof MultipleIndexCanditate) {
            ((MultipleIndexCanditate) result).addCanditate(singleResult);
          } else {
            var mult = new MultipleIndexCanditate();
            mult.addCanditate(result);
            mult.addCanditate(singleResult);
            result = mult;
          }
        } else {
          result = singleResult;
        }
      }
    }
    return result;
  }

  @Override
  public boolean isConstantExpression() {
    if (subBlocks.isEmpty()) {
      return true;
    }
    for (var exp : subBlocks) {
      if (!exp.isConstantExpression()) {
        return false;
      }
    }
    return true;
  }

  @Override
  public boolean isIndexAware(IndexSearchInfo info, CommandContext ctx) {
    //only simple expression like `a = 3` can be indexed
    return false;
  }

  @Override
  public boolean isRangeExpression() {
    return false;
  }

  @Nullable
  @Override
  public String getRelatedIndexPropertyName() {
    return null;
  }

  @Nullable
  @Override
  public SQLBooleanExpression mergeUsingAnd(SQLBooleanExpression other,
      @Nonnull CommandContext ctx) {
    return null;
  }

  @Override
  public boolean varMightBeInUse(String varName) {
    for (var subBlock : subBlocks) {
      if (subBlock.varMightBeInUse(varName)) {
        return true;
      }
    }
    return false;
  }

  @Override
  public boolean isAggregate(DatabaseSessionEmbedded session) {
    for (var sub : subBlocks) {
      if (sub.isAggregate(session)) {
        return true;
      }
    }
    return false;
  }

  @Override
  public SQLBooleanExpression splitForAggregation(
      AggregateProjectionSplit aggregateProj, CommandContext ctx) {
    if (!isAggregate(ctx.getDatabaseSession())) {
      return this;
    }
    var result = new SQLAndBlock(-1);
    for (var sub : subBlocks) {
      result.subBlocks.add(sub.splitForAggregation(aggregateProj, ctx));
    }
    return result;
  }
}
/* JavaCC - OriginalChecksum=cf1f66cc86cfc93d357f9fcdfa4a4604 (do not edit this line) */
