/* Generated By:JJTree: Do not edit this line. SQLBetweenCondition.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=O,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.jetbrains.youtrackdb.internal.core.sql.parser;

import com.jetbrains.youtrackdb.internal.core.command.CommandContext;
import com.jetbrains.youtrackdb.internal.core.db.DatabaseSessionEmbedded;
import com.jetbrains.youtrackdb.internal.core.db.record.record.Identifiable;
import com.jetbrains.youtrackdb.internal.core.metadata.schema.PropertyTypeInternal;
import com.jetbrains.youtrackdb.internal.core.metadata.schema.SchemaClassInternal;
import com.jetbrains.youtrackdb.internal.core.query.Result;
import com.jetbrains.youtrackdb.internal.core.sql.executor.IndexSearchInfo;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Set;
import javax.annotation.Nonnull;
import javax.annotation.Nullable;

public class SQLBetweenCondition extends SQLBooleanExpression {

  protected SQLExpression first;
  protected SQLExpression second;
  protected SQLExpression third;

  public SQLBetweenCondition(int id) {
    super(id);
  }

  public SQLBetweenCondition(YouTrackDBSql p, int id) {
    super(p, id);
  }

  @Override
  public boolean evaluate(Identifiable currentRecord, CommandContext ctx) {
    var firstValue = first.execute(currentRecord, ctx);
    if (firstValue == null) {
      return false;
    }

    var secondValue = second.execute(currentRecord, ctx);
    if (secondValue == null) {
      return false;
    }

    var db = ctx.getDatabaseSession();
    secondValue = PropertyTypeInternal.convert(db, secondValue, firstValue.getClass());

    var thirdValue = third.execute(currentRecord, ctx);
    if (thirdValue == null) {
      return false;
    }
    thirdValue = PropertyTypeInternal.convert(db, thirdValue, firstValue.getClass());

    final var leftResult = ((Comparable<Object>) firstValue).compareTo(secondValue);
    final var rightResult = ((Comparable<Object>) firstValue).compareTo(thirdValue);

    return leftResult >= 0 && rightResult <= 0;
  }

  @Override
  public boolean evaluate(Result currentRecord, CommandContext ctx) {

    var db = ctx.getDatabaseSession();
    if (first.isFunctionAny()) {
      return evaluateAny(db, currentRecord, ctx);
    }

    if (first.isFunctionAll()) {
      return evaluateAllFunction(currentRecord, ctx);
    }

    var firstValue = first.execute(currentRecord, ctx);
    var secondValue = second.execute(currentRecord, ctx);
    var thirdValue = third.execute(currentRecord, ctx);

    return evaluate(db, firstValue, secondValue, thirdValue);
  }

  private static boolean evaluate(DatabaseSessionEmbedded session, Object firstValue,
      Object secondValue,
      Object thirdValue) {
    if (firstValue == null) {
      return false;
    }

    if (secondValue == null) {
      return false;
    }

    secondValue = PropertyTypeInternal.convert(session, secondValue, firstValue.getClass());

    if (thirdValue == null) {
      return false;
    }
    thirdValue = PropertyTypeInternal.convert(session, thirdValue, firstValue.getClass());

    final var leftResult = ((Comparable<Object>) firstValue).compareTo(secondValue);
    final var rightResult = ((Comparable<Object>) firstValue).compareTo(thirdValue);

    return leftResult >= 0 && rightResult <= 0;
  }

  private boolean evaluateAny(DatabaseSessionEmbedded session, Result currentRecord,
      CommandContext ctx) {
    var secondValue = second.execute(currentRecord, ctx);
    var thirdValue = third.execute(currentRecord, ctx);

    for (var s : currentRecord.getPropertyNames()) {
      var firstValue = currentRecord.getProperty(s);
      if (evaluate(session, firstValue, secondValue, thirdValue)) {
        return true;
      }
    }
    return false;
  }

  private boolean evaluateAllFunction(Result currentRecord, CommandContext ctx) {
    var secondValue = second.execute(currentRecord, ctx);
    var thirdValue = third.execute(currentRecord, ctx);

    var database = ctx.getDatabaseSession();
    for (var s : currentRecord.getPropertyNames()) {
      var firstValue = currentRecord.getProperty(s);
      if (!evaluate(database, firstValue, secondValue, thirdValue)) {
        return false;
      }
    }
    return true;
  }

  public SQLExpression getFirst() {
    return first;
  }

  public void setFirst(SQLExpression first) {
    this.first = first;
  }

  public SQLExpression getSecond() {
    return second;
  }

  public void setSecond(SQLExpression second) {
    this.second = second;
  }

  public SQLExpression getThird() {
    return third;
  }

  public void setThird(SQLExpression third) {
    this.third = third;
  }

  @Override
  public void toString(Map<Object, Object> params, StringBuilder builder) {
    first.toString(params, builder);
    builder.append(" BETWEEN ");
    second.toString(params, builder);
    builder.append(" AND ");
    third.toString(params, builder);
  }

  @Override
  public void toGenericStatement(StringBuilder builder) {
    first.toGenericStatement(builder);
    builder.append(" BETWEEN ");
    second.toGenericStatement(builder);
    builder.append(" AND ");
    third.toGenericStatement(builder);
  }

  @Override
  public boolean supportsBasicCalculation() {
    return true;
  }

  @Override
  protected int getNumberOfExternalCalculations() {
    return 0;
  }

  @Override
  protected List<Object> getExternalCalculationConditions() {
    return Collections.EMPTY_LIST;
  }

  @Override
  public boolean needsAliases(Set<String> aliases) {
    if (first.needsAliases(aliases)) {
      return true;
    }
    if (second.needsAliases(aliases)) {
      return true;
    }
    return third.needsAliases(aliases);
  }

  @Override
  public SQLBooleanExpression copy() {
    var result = new SQLBetweenCondition(-1);
    result.first = first.copy();
    result.second = second.copy();
    result.third = third.copy();
    return result;
  }

  @Override
  public void extractSubQueries(SubQueryCollector collector) {
    first.extractSubQueries(collector);
    second.extractSubQueries(collector);
    third.extractSubQueries(collector);
  }

  @Override
  public boolean refersToParent() {
    return first.refersToParent() || second.refersToParent() || third.refersToParent();
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }

    var that = (SQLBetweenCondition) o;

    if (!Objects.equals(first, that.first)) {
      return false;
    }
    if (!Objects.equals(second, that.second)) {
      return false;
    }
    return Objects.equals(third, that.third);
  }

  @Override
  public int hashCode() {
    var result = first != null ? first.hashCode() : 0;
    result = 31 * result + (second != null ? second.hashCode() : 0);
    result = 31 * result + (third != null ? third.hashCode() : 0);
    return result;
  }

  @Nullable
  @Override
  public List<String> getMatchPatternInvolvedAliases() {
    List<String> result = new ArrayList<String>();
    var x = first.getMatchPatternInvolvedAliases();
    if (x != null) {
      result.addAll(x);
    }
    x = second.getMatchPatternInvolvedAliases();
    if (x != null) {
      result.addAll(x);
    }
    x = third.getMatchPatternInvolvedAliases();
    if (x != null) {
      result.addAll(x);
    }

    if (result.isEmpty()) {
      return null;
    }

    return result;
  }

  @Override
  public boolean isCacheable(DatabaseSessionEmbedded session) {
    if (first != null && !first.isCacheable(session)) {
      return false;
    }
    if (second != null && !second.isCacheable(session)) {
      return false;
    }
    return third == null || third.isCacheable(session);
  }

  /**
   * Rewrites {@code val BETWEEN low AND high} into
   * {@code val >= low AND val <= high} during flatten, enabling the index
   * infrastructure to recognize this as a range condition. The rewritten
   * binary conditions are fully index-aware, so no changes are needed in
   * {@link com.jetbrains.youtrackdb.internal.core.sql.executor.SelectExecutionPlanner}
   * or {@link com.jetbrains.youtrackdb.internal.core.sql.executor.FetchFromIndexStep}.
   */
  @Override
  public List<SQLAndBlock> flatten(
      CommandContext ctx, @Nullable SchemaClassInternal schemaClass) {
    // Only rewrite simple property references (not any()/all() functions)
    if (first.isFunctionAny() || first.isFunctionAll()) {
      return super.flatten(ctx, schemaClass);
    }

    // val >= low
    var geCondition = new SQLBinaryCondition(-1);
    geCondition.left = first.copy();
    geCondition.operator = new SQLGeOperator(-1);
    geCondition.right = second.copy();

    // val <= high
    var leCondition = new SQLBinaryCondition(-1);
    leCondition.left = first.copy();
    leCondition.operator = new SQLLeOperator(-1);
    leCondition.right = third.copy();

    var block = new SQLAndBlock(-1);
    block.subBlocks.add(geCondition);
    block.subBlocks.add(leCondition);
    return Collections.singletonList(block);
  }

  @Override
  public boolean isIndexAware(IndexSearchInfo info, CommandContext ctx) {
    return false;
  }

  @Override
  public boolean isRangeExpression() {
    return false;
  }

  @Nullable
  @Override
  public String getRelatedIndexPropertyName() {
    return null;
  }

  @Nullable
  @Override
  public SQLBooleanExpression mergeUsingAnd(SQLBooleanExpression other,
      @Nonnull CommandContext ctx) {
    return null;
  }

  @Override
  public boolean varMightBeInUse(String varName) {
    return first != null && first.varMightBeInUse(varName) ||
        second != null && second.varMightBeInUse(varName) ||
        third != null && third.varMightBeInUse(varName);
  }

  @Override
  public boolean isAggregate(DatabaseSessionEmbedded session) {
    return first != null && first.isAggregate(session)
        || second != null && second.isAggregate(session)
        || third != null && third.isAggregate(session);
  }

  @Override
  public SQLBooleanExpression splitForAggregation(
      AggregateProjectionSplit aggregateProj, CommandContext ctx) {
    if (!isAggregate(ctx.getDatabaseSession())) {
      return this;
    }
    var result = new SQLBetweenCondition(-1);
    result.first = first == null ? null : first.splitForAggregation(aggregateProj, ctx);
    result.second = second == null ? null : second.splitForAggregation(aggregateProj, ctx);
    result.third = third == null ? null : third.splitForAggregation(aggregateProj, ctx);
    return result;
  }
}
/* JavaCC - OriginalChecksum=f94f4779c4a6c6d09539446045ceca89 (do not edit this line) */
