/* Generated By:JJTree: Do not edit this line. SQLContainsKeyOperator.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=O,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.jetbrains.youtrackdb.internal.core.sql.parser;

import com.jetbrains.youtrackdb.internal.core.db.DatabaseSessionEmbedded;
import com.jetbrains.youtrackdb.internal.core.sql.executor.metadata.IndexFinder.Operation;
import com.jetbrains.youtrackdb.internal.core.sql.operator.QueryOperatorEquals;
import java.util.Map;
import javax.annotation.Nonnull;
import javax.annotation.Nullable;

public class SQLContainsKeyOperator extends SimpleNode implements SQLBinaryCompareOperator {

  public SQLContainsKeyOperator(int id) {
    super(id);
  }

  public SQLContainsKeyOperator(YouTrackDBSql p, int id) {
    super(p, id);
  }

  @Override
  public boolean execute(@Nonnull DatabaseSessionEmbedded session, Object left, Object right) {
    if (left == null) {
      return false;
    }
    if (left instanceof Map<?, ?>) {
      final var map = (Map<String, ?>) left;
      return map.containsKey(right);
    }
    return false;
  }

  @Override
  public String toString() {
    return "CONTAINSKEY";
  }

  @Override
  public void toString(Map<Object, Object> params, StringBuilder builder) {
    builder.append("CONTAINSKEY");
  }

  @Override
  public void toGenericStatement(StringBuilder builder) {
    builder.append("CONTAINSKEY");
  }

  @Override
  public boolean supportsBasicCalculation() {
    return true;
  }

  @Nullable
  @Override
  public MergeResult mergeWithOperator(@Nonnull DatabaseSessionEmbedded session,
      @Nonnull SQLBinaryCompareOperator otherOperator, Object currentRight,
      Object otherRight) {
    if (QueryOperatorEquals.equals(session, currentRight, otherRight)) {
      return new MergeResult(this, currentRight);
    }

    return null;
  }

  @Override
  public SQLContainsKeyOperator copy() {
    return this;
  }

  @Override
  public Operation getOperation() {
    return Operation.Eq;
  }

  @Override
  public boolean equals(Object obj) {
    return obj != null && obj.getClass().equals(this.getClass());
  }

  @Override
  public int hashCode() {
    return getClass().hashCode();
  }
}
/* JavaCC - OriginalChecksum=1a03daaa6712eb981b070e8e94960951 (do not edit this line) */
