/* Generated By:JJTree: Do not edit this line. SQLCreateClassStatement.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=O,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.jetbrains.youtrackdb.internal.core.sql.parser;

import com.jetbrains.youtrackdb.internal.core.command.CommandContext;
import com.jetbrains.youtrackdb.internal.core.exception.CommandExecutionException;
import com.jetbrains.youtrackdb.internal.core.metadata.schema.schema.Schema;
import com.jetbrains.youtrackdb.internal.core.metadata.schema.schema.SchemaClass;
import com.jetbrains.youtrackdb.internal.core.sql.executor.ResultInternal;
import com.jetbrains.youtrackdb.internal.core.sql.executor.resultset.ExecutionStream;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.stream.Collectors;

public class SQLCreateClassStatement extends DDLStatement {

  /**
   * Class name
   */
  public SQLIdentifier name;

  public boolean ifNotExists;

  /**
   * Direct superclasses for this class
   */
  protected List<SQLIdentifier> superclasses;

  /**
   * Collection IDs for this class
   */
  protected List<SQLInteger> collections;

  /**
   * Total number collections for this class
   */
  protected SQLInteger totalCollectionNo;

  protected boolean abstractClass = false;

  public SQLCreateClassStatement(int id) {
    super(id);
  }

  public SQLCreateClassStatement(YouTrackDBSql p, int id) {
    super(p, id);
  }

  @Override
  public ExecutionStream executeDDL(CommandContext ctx) {
    var session = ctx.getDatabaseSession();
    var schema = session.getMetadata().getSchema();
    if (schema.existsClass(name.getStringValue())) {
      if (ifNotExists) {
        return ExecutionStream.empty();
      } else {
        throw new CommandExecutionException(session, "Class " + name + " already exists");
      }
    }
    checkSuperclasses(schema, ctx);

    var result = new ResultInternal(session);
    result.setProperty("operation", "create class");
    result.setProperty("className", name.getStringValue());

    var superclasses = getSuperClasses(schema);
    if (abstractClass) {
      schema.createAbstractClass(name.getStringValue(), superclasses);
      result.setProperty("abstract", abstractClass);
    } else if (totalCollectionNo != null) {
      schema.createClass(
          name.getStringValue(), totalCollectionNo.getValue().intValue(), superclasses);
    } else if (collections != null) {
      collections.stream().map(x -> x.getValue().intValue()).toList();
      var collectionIds = new int[collections.size()];
      for (var i = 0; i < collections.size(); i++) {
        collectionIds[i] = collections.get(i).getValue().intValue();
      }
      schema.createClass(name.getStringValue(), collectionIds, superclasses);
    } else {
      schema.createClass(name.getStringValue(), superclasses);
    }

    return ExecutionStream.singleton(result);
  }

  private SchemaClass[] getSuperClasses(Schema schema) {
    if (superclasses == null) {
      return new SchemaClass[]{};
    }
    return superclasses.stream()
        .map(x -> schema.getClass(x.getStringValue()))
        .filter(x -> x != null)
        .collect(Collectors.toList())
        .toArray(new SchemaClass[]{});
  }

  private void checkSuperclasses(Schema schema, CommandContext ctx) {
    if (superclasses != null) {
      for (var superclass : superclasses) {
        if (!schema.existsClass(superclass.getStringValue())) {
          throw new CommandExecutionException(ctx.getDatabaseSession(),
              "Superclass " + superclass + " not found");
        }
      }
    }
  }

  @Override
  public void toString(Map<Object, Object> params, StringBuilder builder) {
    builder.append("CREATE CLASS ");
    name.toString(params, builder);
    if (ifNotExists) {
      builder.append(" IF NOT EXISTS");
    }
    if (superclasses != null && !superclasses.isEmpty()) {
      builder.append(" EXTENDS ");
      var first = true;
      for (var sup : superclasses) {
        if (!first) {
          builder.append(", ");
        }
        sup.toString(params, builder);
        first = false;
      }
    }
    if (collections != null && collections.size() > 0) {
      builder.append(" COLLECTION ");
      var first = true;
      for (var collection : collections) {
        if (!first) {
          builder.append(",");
        }
        collection.toString(params, builder);
        first = false;
      }
    }
    if (totalCollectionNo != null) {
      builder.append(" COLLECTIONS ");
      totalCollectionNo.toString(params, builder);
    }
    if (abstractClass) {
      builder.append(" ABSTRACT");
    }
  }

  @Override
  public void toGenericStatement(StringBuilder builder) {
    builder.append("CREATE CLASS ");
    name.toGenericStatement(builder);
    if (ifNotExists) {
      builder.append(" IF NOT EXISTS");
    }
    if (superclasses != null && superclasses.size() > 0) {
      builder.append(" EXTENDS ");
      var first = true;
      for (var sup : superclasses) {
        if (!first) {
          builder.append(", ");
        }
        sup.toGenericStatement(builder);
        first = false;
      }
    }
    if (collections != null && collections.size() > 0) {
      builder.append(" COLLECTION ");
      var first = true;
      for (var collection : collections) {
        if (!first) {
          builder.append(",");
        }
        collection.toGenericStatement(builder);
        first = false;
      }
    }
    if (totalCollectionNo != null) {
      builder.append(" COLLECTIONS ");
      totalCollectionNo.toGenericStatement(builder);
    }
    if (abstractClass) {
      builder.append(" ABSTRACT");
    }
  }

  @Override
  public SQLCreateClassStatement copy() {
    var result = new SQLCreateClassStatement(-1);
    result.name = name == null ? null : name.copy();
    result.superclasses =
        superclasses == null
            ? null
            : superclasses.stream().map(x -> x.copy()).collect(Collectors.toList());
    result.collections =
        collections == null ? null
            : collections.stream().map(x -> x.copy()).collect(Collectors.toList());
    result.totalCollectionNo = totalCollectionNo == null ? null : totalCollectionNo.copy();
    result.abstractClass = abstractClass;
    result.ifNotExists = ifNotExists;
    return result;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }

    var that = (SQLCreateClassStatement) o;

    if (abstractClass != that.abstractClass) {
      return false;
    }
    if (!Objects.equals(name, that.name)) {
      return false;
    }
    if (!Objects.equals(superclasses, that.superclasses)) {
      return false;
    }
    if (!Objects.equals(collections, that.collections)) {
      return false;
    }
    if (!Objects.equals(totalCollectionNo, that.totalCollectionNo)) {
      return false;
    }
    return ifNotExists == that.ifNotExists;
  }

  @Override
  public int hashCode() {
    var result = name != null ? name.hashCode() : 0;
    result = 31 * result + (superclasses != null ? superclasses.hashCode() : 0);
    result = 31 * result + (collections != null ? collections.hashCode() : 0);
    result = 31 * result + (totalCollectionNo != null ? totalCollectionNo.hashCode() : 0);
    result = 31 * result + (abstractClass ? 1 : 0);
    return result;
  }

  public List<SQLIdentifier> getSuperclasses() {
    return superclasses;
  }

  public void addSuperclass(SQLIdentifier identifier) {
    if (this.superclasses == null) {
      this.superclasses = new ArrayList<>();
    }
    this.superclasses.add(identifier);
  }

  public void addCollection(SQLInteger id) {
    if (collections == null) {
      this.collections = new ArrayList<>();
    }
    this.collections.add(id);
  }
}
/* JavaCC - OriginalChecksum=4043013624f55fdf0ea8fee6d4f211b0 (do not edit this line) */
