/* Generated By:JJTree: Do not edit this line. SQLExpression.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=O,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.jetbrains.youtrackdb.internal.core.sql.parser;

import com.jetbrains.youtrackdb.internal.core.command.CommandContext;
import com.jetbrains.youtrackdb.internal.core.db.DatabaseSessionEmbedded;
import com.jetbrains.youtrackdb.internal.core.db.record.record.Entity;
import com.jetbrains.youtrackdb.internal.core.db.record.record.Identifiable;
import com.jetbrains.youtrackdb.internal.core.exception.CommandExecutionException;
import com.jetbrains.youtrackdb.internal.core.id.RecordId;
import com.jetbrains.youtrackdb.internal.core.metadata.schema.SchemaClassInternal;
import com.jetbrains.youtrackdb.internal.core.metadata.schema.schema.Collate;
import com.jetbrains.youtrackdb.internal.core.metadata.schema.schema.SchemaClass;
import com.jetbrains.youtrackdb.internal.core.query.Result;
import com.jetbrains.youtrackdb.internal.core.sql.executor.AggregationContext;
import com.jetbrains.youtrackdb.internal.core.sql.executor.ResultInternal;
import com.jetbrains.youtrackdb.internal.core.sql.executor.metadata.IndexMetadataPath;
import java.util.Collection;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Set;
import javax.annotation.Nullable;

public class SQLExpression extends SimpleNode {

  protected Boolean singleQuotes;
  protected Boolean doubleQuotes;

  protected boolean isNull = false;
  protected SQLRid rid;
  protected SQLMathExpression mathExpression;
  protected SQLArrayConcatExpression arrayConcatExpression;
  protected SQLJson json;
  protected SQLBooleanExpression booleanExpression;
  protected Boolean booleanValue;
  private Object literalValue;

  public SQLExpression(int id) {
    super(id);
  }

  public SQLExpression(YouTrackDBSql p, int id) {
    super(p, id);
  }

  public SQLExpression(SQLIdentifier identifier) {
    mathExpression = new SQLBaseExpression(identifier);
  }

  public SQLExpression(SQLIdentifier identifier, SQLModifier modifier) {

    mathExpression = new SQLBaseExpression(identifier, modifier);
  }

  public SQLExpression(SQLRecordAttribute attr, SQLModifier modifier) {
    mathExpression = new SQLBaseExpression(attr, modifier);
  }

  public boolean isStatement() {
    return mathExpression instanceof SQLParenthesisExpression sqlParenthesisExpression
        && sqlParenthesisExpression.statement != null;
  }

  public SQLStatement asStatement() {
    if (!isStatement()) {
      throw new IllegalStateException("This expression is not a statement");
    }

    return ((SQLParenthesisExpression) mathExpression).statement;
  }

  @Nullable
  public Object execute(Identifiable iCurrentRecord, CommandContext ctx) {
    if (isNull) {
      return null;
    }
    if (rid != null) {
      return rid.toRecordId(iCurrentRecord, ctx);
    }
    if (mathExpression != null) {
      return mathExpression.execute(iCurrentRecord, ctx);
    }
    if (arrayConcatExpression != null) {
      return arrayConcatExpression.execute(iCurrentRecord, ctx);
    }
    if (booleanExpression != null) {
      return booleanExpression.evaluate(iCurrentRecord, ctx);
    }
    if (json != null) {
      return json.toObjectDetermineType(iCurrentRecord, ctx);
    }
    if (booleanValue != null) {
      return booleanValue;
    }
    if (literalValue != null) {
      return literalValue;
    }
    if (value instanceof SQLNumber) {
      return ((SQLNumber) value).getValue(); // only for old executor (manually replaced params)
    }

    // from here it's old stuff, only for the old executor
    if (value instanceof SQLRid v) {
      return new RecordId(v.collection.getValue().intValue(),
          v.position.getValue().longValue());
    } else if (value instanceof SQLMathExpression) {
      return ((SQLMathExpression) value).execute(iCurrentRecord, ctx);
    } else if (value instanceof SQLArrayConcatExpression) {
      return ((SQLArrayConcatExpression) value).execute(iCurrentRecord, ctx);
    } else if (value instanceof SQLJson) {
      return ((SQLJson) value).toMap(iCurrentRecord, ctx);
    } else if (value instanceof String) {
      return value;
    } else if (value instanceof Number) {
      return value;
    }

    return value;
  }

  @Nullable
  public Object execute(Result iCurrentRecord, CommandContext ctx) {
    if (isNull) {
      return null;
    }
    if (rid != null) {
      return rid.toRecordId(iCurrentRecord, ctx);
    }
    if (mathExpression != null) {
      return mathExpression.execute(iCurrentRecord, ctx);
    }
    if (arrayConcatExpression != null) {
      return arrayConcatExpression.execute(iCurrentRecord, ctx);
    }
    if (booleanExpression != null) {
      return booleanExpression.evaluate(iCurrentRecord, ctx);
    }
    if (json != null) {
      return json.toObjectDetermineType(iCurrentRecord, ctx);
    }
    if (booleanValue != null) {
      return booleanValue;
    }
    if (literalValue != null) {
      return literalValue;
    }
    if (value instanceof SQLNumber) {
      return ((SQLNumber) value).getValue(); // only for old executor (manually replaced params)
    }

    // from here it's old stuff, only for the old executor
    if (value instanceof SQLRid v) {
      return new RecordId(v.collection.getValue().intValue(),
          v.position.getValue().longValue());
    } else if (value instanceof SQLMathExpression) {
      return ((SQLMathExpression) value).execute(iCurrentRecord, ctx);
    } else if (value instanceof SQLArrayConcatExpression) {
      return ((SQLArrayConcatExpression) value).execute(iCurrentRecord, ctx);
    } else if (value instanceof SQLJson) {
      return ((SQLJson) value).toMap(iCurrentRecord, ctx);
    } else if (value instanceof String) {
      return value;
    } else if (value instanceof Number) {
      return value;
    }

    return value;
  }

  public boolean isBaseIdentifier() {
    if (mathExpression != null) {
      return mathExpression.isBaseIdentifier();
    }
    if (value instanceof SQLMathExpression) { // only backward stuff, remote it
      return ((SQLMathExpression) value).isBaseIdentifier();
    }

    return false;
  }

  public boolean isGraphNavigationFunction(DatabaseSessionEmbedded session) {
    if (mathExpression != null) {
      return mathExpression.isGraphRelationFunction(session);
    }
    if (value instanceof SQLMathExpression) { // only backward stuff, remote it
      return ((SQLMathExpression) value).isGraphRelationFunction(session);
    }

    return false;
  }

  @Nullable
  public Collection<String> getGraphRelationProperties(CommandContext ctx,
      SchemaClass schemaClass) {
    if (mathExpression != null) {
      return mathExpression.getGraphNavigationFunctionProperties(ctx, schemaClass);
    }

    return null;
  }

  @Nullable
  public IndexMetadataPath getIndexMetadataPath(DatabaseSessionEmbedded session) {
    if (mathExpression != null) {
      return mathExpression.getIndexMetadataPath(session);
    }

    if (value instanceof SQLMathExpression) {
      return ((SQLMathExpression) value).getIndexMetadataPath(session);
    }

    return null;
  }

  public boolean isEarlyCalculated(CommandContext ctx) {
    if (this.mathExpression != null) {
      return this.mathExpression.isEarlyCalculated(ctx);
    }
    if (this.arrayConcatExpression != null) {
      return this.arrayConcatExpression.isEarlyCalculated(ctx);
    }

    if (booleanValue != null) {
      return true;
    }
    if (literalValue != null) {
      return true;
    }
    if (rid != null) {
      return true;
    }
    if (value instanceof Number) {
      return true;
    }
    if (value instanceof String) {
      return true;
    }
    if (value instanceof SQLMathExpression) {
      return ((SQLMathExpression) value).isEarlyCalculated(ctx);
    }

    return false;
  }

  public SQLIdentifier getDefaultAlias() {
    SQLIdentifier identifier;
    if (isBaseIdentifier()) {
      identifier =
          new SQLIdentifier(
              ((SQLBaseExpression) mathExpression)
                  .getIdentifier()
                  .getSuffix()
                  .getIdentifier()
                  .getStringValue());
    } else {
      identifier = new SQLIdentifier(this.toString());
    }
    return identifier;
  }

  @Override
  public void toString(Map<Object, Object> params, StringBuilder builder) {
    if (isNull) {
      builder.append("null");
    } else if (rid != null) {
      rid.toString(params, builder);
    } else if (mathExpression != null) {
      mathExpression.toString(params, builder);
    } else if (arrayConcatExpression != null) {
      arrayConcatExpression.toString(params, builder);
    } else if (booleanExpression != null) {
      booleanExpression.toString(params, builder);
    } else if (json != null) {
      json.toString(params, builder);
    } else if (booleanValue != null) {
      builder.append(booleanValue);
    } else if (literalValue != null) {
      builder.append(literalValue);
    } else if (value instanceof SimpleNode) {
      ((SimpleNode) value)
          .toString(
              params,
              builder); // only for translated input params, will disappear with new executor
    } else if (value instanceof String) {
      if (Boolean.TRUE.equals(singleQuotes)) {
        builder.append("'").append(value).append("'");
      } else {
        builder.append("\"").append(value).append("\"");
      }

    } else {
      builder.append(value); // only for translated input params, will disappear with new executor
    }
  }

  @Override
  public void toGenericStatement(StringBuilder builder) {
    if (isNull) {
      builder.append("null");
    } else if (rid != null) {
      rid.toGenericStatement(builder);
    } else if (mathExpression != null) {
      mathExpression.toGenericStatement(builder);
    } else if (arrayConcatExpression != null) {
      arrayConcatExpression.toGenericStatement(builder);
    } else if (booleanExpression != null) {
      booleanExpression.toGenericStatement(builder);
    } else if (json != null) {
      json.toGenericStatement(builder);
    } else if (booleanValue != null) {
      builder.append(PARAMETER_PLACEHOLDER);
    } else if (literalValue != null) {
      builder.append(PARAMETER_PLACEHOLDER);
    } else if (value instanceof SimpleNode) {
      ((SimpleNode) value).toGenericStatement(builder);
    } else if (value instanceof String) {
      builder.append(PARAMETER_PLACEHOLDER);
    } else {
      builder.append(PARAMETER_PLACEHOLDER);
    }
  }

  public static String encode(String s) {
    var builder = new StringBuilder(s.length());
    for (var c : s.toCharArray()) {
      if (c == '\n') {
        builder.append("\\n");
        continue;
      }
      if (c == '\t') {
        builder.append("\\t");
        continue;
      }
      if (c == '\\' || c == '"') {
        builder.append("\\");
      }
      builder.append(c);
    }
    return builder.toString();
  }

  public boolean supportsBasicCalculation() {
    if (mathExpression != null) {
      return mathExpression.supportsBasicCalculation();
    }
    if (arrayConcatExpression != null) {
      return arrayConcatExpression.supportsBasicCalculation();
    }
    return true;
  }

  public boolean isIndexedFunctionCal(DatabaseSessionEmbedded session) {
    if (mathExpression != null) {
      return mathExpression.isIndexedFunctionCall(session);
    }
    return false;
  }

  public static String encodeSingle(String s) {

    var builder = new StringBuilder(s.length());
    for (var c : s.toCharArray()) {
      if (c == '\n') {
        builder.append("\\n");
        continue;
      }
      if (c == '\t') {
        builder.append("\\t");
        continue;
      }
      if (c == '\\' || c == '\'') {
        builder.append("\\");
      }
      builder.append(c);
    }
    return builder.toString();
  }

  public long estimateIndexedFunction(
      SQLFromClause target, CommandContext context, SQLBinaryCompareOperator operator,
      Object right) {
    if (mathExpression != null) {
      return mathExpression.estimateIndexedFunction(target, context, operator, right);
    }
    return -1;
  }

  @Nullable
  public Iterable<Identifiable> executeIndexedFunction(
      SQLFromClause target, CommandContext context, SQLBinaryCompareOperator operator,
      Object right) {
    if (mathExpression != null) {
      return mathExpression.executeIndexedFunction(target, context, operator, right);
    }
    return null;
  }

  /**
   * tests if current expression is an indexed function AND that function can also be executed
   * without using the index
   *
   * @param target  the query target
   * @param context the execution context
   * @return true if current expression is an indexed funciton AND that function can also be
   * executed without using the index, false otherwise
   */
  public boolean canExecuteIndexedFunctionWithoutIndex(
      SQLFromClause target, CommandContext context, SQLBinaryCompareOperator operator,
      Object right) {
    if (mathExpression != null) {
      return mathExpression.canExecuteIndexedFunctionWithoutIndex(target, context, operator, right);
    }
    return false;
  }

  /**
   * tests if current expression is an indexed function AND that function can be used on this
   * target
   *
   * @param target  the query target
   * @param context the execution context
   * @return true if current expression involves an indexed function AND that function can be used
   * on this target, false otherwise
   */
  public boolean allowsIndexedFunctionExecutionOnTarget(
      SQLFromClause target, CommandContext context, SQLBinaryCompareOperator operator,
      Object right) {
    if (mathExpression != null) {
      return mathExpression.allowsIndexedFunctionExecutionOnTarget(
          target, context, operator, right);
    }
    return false;
  }

  /**
   * tests if current expression is an indexed function AND the function has also to be executed
   * after the index search. In some cases, the index search is accurate, so this condition can be
   * excluded from further evaluation. In other cases the result from the index is a superset of the
   * expected result, so the function has to be executed anyway for further filtering
   *
   * @param target  the query target
   * @param context the execution context
   * @return true if current expression involves an indexed function AND the function has also to be
   * executed after the index search.
   */
  public boolean executeIndexedFunctionAfterIndexSearch(
      SQLFromClause target, CommandContext context, SQLBinaryCompareOperator operator,
      Object right) {
    if (mathExpression != null) {
      return mathExpression.executeIndexedFunctionAfterIndexSearch(
          target, context, operator, right);
    }
    return false;
  }

  public boolean isExpand() {
    if (mathExpression != null) {
      return mathExpression.isExpand();
    }
    return false;
  }

  public SQLExpression getExpandContent() {
    return mathExpression.getExpandContent();
  }

  public boolean needsAliases(Set<String> aliases) {
    if (mathExpression != null) {
      return mathExpression.needsAliases(aliases);
    }
    if (arrayConcatExpression != null) {
      return arrayConcatExpression.needsAliases(aliases);
    }
    if (booleanExpression != null) {
      return booleanExpression.needsAliases(aliases);
    }
    if (json != null) {
      return json.needsAliases(aliases);
    }
    return false;
  }

  public boolean isAggregate(DatabaseSessionEmbedded session) {
    if (mathExpression != null && mathExpression.isAggregate(session)) {
      return true;
    }
    if (arrayConcatExpression != null && arrayConcatExpression.isAggregate(session)) {
      return true;
    }
    return json != null && json.isAggregate(session);
  }

  public SQLExpression splitForAggregation(
      AggregateProjectionSplit aggregateSplit, CommandContext ctx) {
    var database = ctx.getDatabaseSession();
    if (isAggregate(database)) {
      var result = new SQLExpression(-1);
      if (mathExpression != null) {
        var splitResult = mathExpression.splitForAggregation(aggregateSplit, ctx);
        if (splitResult instanceof SQLMathExpression) {
          result.mathExpression = (SQLMathExpression) splitResult;
        } else if (splitResult instanceof SQLExpression) {
          return (SQLExpression) splitResult;
        } else {
          throw new IllegalStateException(
              "something went wrong while splitting expression for aggregate " + this);
        }
      }
      if (arrayConcatExpression != null) {
        var splitResult = arrayConcatExpression.splitForAggregation(database,
            aggregateSplit);
        if (splitResult instanceof SQLArrayConcatExpression) {
          result.arrayConcatExpression = (SQLArrayConcatExpression) splitResult;
        } else if (splitResult instanceof SQLExpression) {
          return (SQLExpression) splitResult;
        } else {
          throw new IllegalStateException(
              "something went wrong while splitting expression for aggregate " + this);
        }
      }
      if (json != null) {
        result.json = json.splitForAggregation(aggregateSplit, ctx);
      }
      return result;
    } else {
      return this;
    }
  }

  public AggregationContext getAggregationContext(CommandContext ctx) {
    if (mathExpression != null) {
      return mathExpression.getAggregationContext(ctx);
    } else if (arrayConcatExpression != null) {
      throw new UnsupportedOperationException();
    } else {
      throw new CommandExecutionException(ctx.getDatabaseSession(), "Cannot aggregate on " + this);
    }
  }

  @Override
  public SQLExpression copy() {

    var result = new SQLExpression(-1);
    result.singleQuotes = singleQuotes;
    result.doubleQuotes = doubleQuotes;
    result.isNull = isNull;
    result.rid = rid == null ? null : rid.copy();
    result.mathExpression = mathExpression == null ? null : mathExpression.copy();
    result.arrayConcatExpression =
        arrayConcatExpression == null ? null : arrayConcatExpression.copy();
    result.json = json == null ? null : json.copy();
    result.booleanExpression = booleanExpression == null ? null : booleanExpression.copy();
    result.booleanValue = booleanValue;
    result.literalValue = deepCopyLiteralValue(literalValue);

    return result;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }

    var that = (SQLExpression) o;

    if (isNull != that.isNull) {
      return false;
    }
    if (!Objects.equals(singleQuotes, that.singleQuotes)) {
      return false;
    }
    if (!Objects.equals(doubleQuotes, that.doubleQuotes)) {
      return false;
    }
    if (!Objects.equals(rid, that.rid)) {
      return false;
    }
    if (!Objects.equals(mathExpression, that.mathExpression)) {
      return false;
    }
    if (!Objects.equals(arrayConcatExpression, that.arrayConcatExpression)) {
      return false;
    }
    if (!Objects.equals(json, that.json)) {
      return false;
    }
    if (!Objects.equals(booleanExpression, that.booleanExpression)) {
      return false;
    }
    if (!Objects.equals(booleanValue, that.booleanValue)) {
      return false;
    }
    return deepEqualsLiteralValue(literalValue, that.literalValue);
  }

  @Override
  public int hashCode() {
    var result = singleQuotes != null ? singleQuotes.hashCode() : 0;
    result = 31 * result + (doubleQuotes != null ? doubleQuotes.hashCode() : 0);
    result = 31 * result + (isNull ? 1 : 0);
    result = 31 * result + (rid != null ? rid.hashCode() : 0);
    result = 31 * result + (mathExpression != null ? mathExpression.hashCode() : 0);
    result = 31 * result + (arrayConcatExpression != null ? arrayConcatExpression.hashCode() : 0);
    result = 31 * result + (json != null ? json.hashCode() : 0);
    result = 31 * result + (booleanExpression != null ? booleanExpression.hashCode() : 0);
    result = 31 * result + (booleanValue != null ? booleanValue.hashCode() : 0);
    result = 31 * result + deepHashCodeLiteralValue(literalValue);
    return result;
  }

  /// Deep-copies mutable literal values (byte[], List, Map, Set, Date) to prevent
  /// AST corruption when plans are cached and reused.
  @Nullable
  private static Object deepCopyLiteralValue(@Nullable Object value) {
    if (value == null) {
      return null;
    }
    if (value instanceof byte[] bytes) {
      return bytes.clone();
    }
    if (value instanceof List<?> list) {
      return new java.util.ArrayList<>(list);
    }
    if (value instanceof Map<?, ?> map) {
      return new java.util.LinkedHashMap<>(map);
    }
    if (value instanceof Set<?> set) {
      return new java.util.LinkedHashSet<>(set);
    }
    if (value instanceof java.util.Date date) {
      return new java.util.Date(date.getTime());
    }
    // Immutable types (String, Number, Boolean, etc.) — no copy needed
    return value;
  }

  /// Compares literal values with proper deep equality for byte[].
  private static boolean deepEqualsLiteralValue(
      @Nullable Object a, @Nullable Object b) {
    if (a instanceof byte[] aBytes && b instanceof byte[] bBytes) {
      return java.util.Arrays.equals(aBytes, bBytes);
    }
    return Objects.equals(a, b);
  }

  /// Computes hash code for literal values with proper handling for byte[].
  private static int deepHashCodeLiteralValue(@Nullable Object value) {
    if (value instanceof byte[] bytes) {
      return java.util.Arrays.hashCode(bytes);
    }
    return value != null ? value.hashCode() : 0;
  }

  public void setBooleanValue(Boolean booleanValue) {
    this.booleanValue = booleanValue;
  }

  public void setLiteralValue(Object literalValue) {
    this.literalValue = literalValue;
  }

  public void setMathExpression(SQLMathExpression mathExpression) {
    this.mathExpression = mathExpression;
  }

  public void extractSubQueries(SubQueryCollector collector) {
    if (mathExpression != null) {
      mathExpression.extractSubQueries(collector);
    }
    if (arrayConcatExpression != null) {
      arrayConcatExpression.extractSubQueries(collector);
    }
    if (booleanExpression != null) {
      booleanExpression.extractSubQueries(collector);
    }
    if (json != null) {
      json.extractSubQueries(collector);
    }
  }

  public void extractSubQueries(SQLIdentifier letAlias, SubQueryCollector collector) {
    if (mathExpression != null) {
      mathExpression.extractSubQueries(letAlias, collector);
    }
    if (arrayConcatExpression != null) {
      arrayConcatExpression.extractSubQueries(collector);
    }
    if (booleanExpression != null) {
      booleanExpression.extractSubQueries(collector);
    }
    if (json != null) {
      json.extractSubQueries(collector);
    }
  }

  public boolean refersToParent() {
    if (mathExpression != null && mathExpression.refersToParent()) {
      return true;
    }
    if (arrayConcatExpression != null && arrayConcatExpression.refersToParent()) {
      return true;
    }
    if (booleanExpression != null && booleanExpression.refersToParent()) {
      return true;
    }
    return json != null && json.refersToParent();
  }

  public SQLRid getRid() {
    return rid;
  }

  public void setRid(SQLRid rid) {
    this.rid = rid;
  }

  public SQLMathExpression getMathExpression() {
    return mathExpression;
  }

  /**
   * if the condition involved the current pattern (MATCH statement, eg. $matched.something = foo),
   * returns the name of involved pattern aliases ("something" in this case)
   *
   * @return a list of pattern aliases involved in this condition. Null it does not involve the
   * pattern
   */
  @Nullable
  public List<String> getMatchPatternInvolvedAliases() {
    if (mathExpression != null) {
      return mathExpression.getMatchPatternInvolvedAliases();
    }
    if (arrayConcatExpression != null) {
      return arrayConcatExpression.getMatchPatternInvolvedAliases();
    }
    if (booleanExpression != null) {
      return booleanExpression.getMatchPatternInvolvedAliases();
    }
    return null;
  }

  public void applyRemove(ResultInternal result, CommandContext ctx) {
    if (mathExpression != null) {
      mathExpression.applyRemove(result, ctx);
    } else {
      throw new CommandExecutionException(ctx.getDatabaseSession(), "Cannot apply REMOVE " + this);
    }
  }

  public boolean isCount() {
    if (mathExpression == null) {
      return false;
    }
    return mathExpression.isCount();
  }

  public SQLArrayConcatExpression getArrayConcatExpression() {
    return arrayConcatExpression;
  }

  public void setArrayConcatExpression(SQLArrayConcatExpression arrayConcatExpression) {
    this.arrayConcatExpression = arrayConcatExpression;
  }

  public Result serialize(DatabaseSessionEmbedded session) {
    var result = new ResultInternal(session);
    result.setProperty("singleQuotes", singleQuotes);
    result.setProperty("doubleQuotes", doubleQuotes);
    result.setProperty("isNull", isNull);

    if (rid != null) {
      result.setProperty("rid", rid.serialize(session));
    }
    if (mathExpression != null) {
      result.setProperty("mathExpression", mathExpression.serialize(session));
    }
    if (arrayConcatExpression != null) {
      result.setProperty("arrayConcatExpression", arrayConcatExpression.serialize(session));
    }
    if (json != null) {
      result.setProperty("json", json.serialize(session));
    }
    if (booleanExpression != null) {
      result.setProperty("booleanExpression", booleanExpression.serialize(session));
    }
    result.setProperty("booleanValue", booleanValue);
    result.setProperty("literalValue", literalValue);
    return result;
  }

  public void deserialize(Result fromResult) {
    singleQuotes = fromResult.getProperty("singleQuotes");
    doubleQuotes = fromResult.getProperty("doubleQuotes");
    isNull = fromResult.getProperty("isNull");

    if (fromResult.getProperty("rid") != null) {
      rid = new SQLRid(-1);
      rid.deserialize(fromResult.getProperty("rid"));
    }
    if (fromResult.getProperty("mathExpression") != null) {
      mathExpression =
          SQLMathExpression.deserializeFromResult(fromResult.getProperty("mathExpression"));
    }
    if (fromResult.getProperty("arrayConcatExpression") != null) {
      arrayConcatExpression = new SQLArrayConcatExpression(-1);
      arrayConcatExpression.deserialize(fromResult.getProperty("arrayConcatExpression"));
    }
    if (fromResult.getProperty("json") != null) {
      json = new SQLJson(-1);
      json.deserialize(fromResult.getProperty("json"));
    }
    if (fromResult.getProperty("booleanExpression") != null) {
      booleanExpression =
          SQLBooleanExpression.deserializeFromOResult(fromResult.getProperty("booleanExpression"));
    }
    booleanValue = fromResult.getProperty("booleanValue");
    literalValue = fromResult.getProperty("literalValue");
  }

  public boolean isDefinedFor(Result currentRecord) {
    if (mathExpression != null) {
      return mathExpression.isDefinedFor(currentRecord);
    } else {
      return true;
    }
  }

  public boolean isDefinedFor(DatabaseSessionEmbedded db, Entity currentRecord) {
    if (mathExpression != null) {
      return mathExpression.isDefinedFor(db, currentRecord);
    } else {
      return true;
    }
  }

  @Nullable
  public Collate getCollate(Result currentRecord, CommandContext ctx) {
    if (mathExpression != null) {
      return mathExpression.getCollate(currentRecord, ctx);
    }
    return null;
  }

  public boolean isCacheable(DatabaseSessionEmbedded session) {
    if (mathExpression != null) {
      return mathExpression.isCacheable(session);
    }
    if (arrayConcatExpression != null) {
      return arrayConcatExpression.isCacheable(session);
    }
    if (booleanExpression != null) {
      return booleanExpression.isCacheable(session);
    }
    if (literalValue != null) {
      return true;
    }
    return json == null;
  }

  public boolean isIndexChain(CommandContext ctx, SchemaClassInternal clazz) {
    if (mathExpression != null) {
      return mathExpression.isIndexChain(ctx, clazz);
    }
    return false;
  }

  public boolean isFunctionAny() {
    if (mathExpression != null) {
      return mathExpression.isFunctionAny();
    }
    return false;
  }

  public boolean isFunctionAll() {
    if (mathExpression != null) {
      return mathExpression.isFunctionAll();
    }
    return false;
  }

  public boolean varMightBeInUse(String varName) {
    return mathExpression != null && mathExpression.varMightBeInUse(varName)
        || arrayConcatExpression != null && arrayConcatExpression.varMightBeInUse(varName)
        || booleanExpression != null && booleanExpression.varMightBeInUse(varName);
  }
}
/* JavaCC - OriginalChecksum=9c860224b121acdc89522ae97010be01 (do not edit this line) */
