/* Generated By:JJTree: Do not edit this line. SQLFromItem.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=O,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.jetbrains.youtrackdb.internal.core.sql.parser;

import com.jetbrains.youtrackdb.internal.core.db.DatabaseSessionEmbedded;
import com.jetbrains.youtrackdb.internal.core.metadata.schema.SchemaClassInternal;
import com.jetbrains.youtrackdb.internal.core.query.Result;
import com.jetbrains.youtrackdb.internal.core.sql.executor.ResultInternal;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.stream.Collectors;
import javax.annotation.Nullable;

public class SQLFromItem extends SimpleNode {

  protected List<SQLRid> rids;
  protected List<SQLInputParameter> inputParams;
  protected SQLMetadataIdentifier metadata;
  protected SQLStatement statement;
  protected SQLInputParameter inputParam;
  protected SQLIdentifier identifier;
  protected SQLFunctionCall functionCall;
  protected SQLModifier modifier;

  public SQLFromItem(int id) {
    super(id);
  }

  public SQLFromItem(YouTrackDBSql p, int id) {
    super(p, id);
  }

  @Override
  public void toString(Map<Object, Object> params, StringBuilder builder) {
    if (rids != null && !rids.isEmpty()) {
      if (rids.size() == 1) {
        rids.getFirst().toString(params, builder);
        return;
      } else {
        builder.append("[");
        var first = true;
        for (var rid : rids) {
          if (!first) {
            builder.append(", ");
          }
          rid.toString(params, builder);
          first = false;
        }
        builder.append("]");
        return;
      }
    } else if (inputParams != null && !inputParams.isEmpty()) {
      if (inputParams.size() == 1) {
        inputParams.getFirst().toString(params, builder);
        return;
      } else {
        builder.append("[");
        var first = true;
        for (var rid : inputParams) {
          if (!first) {
            builder.append(", ");
          }
          rid.toString(params, builder);
          first = false;
        }
        builder.append("]");
        return;
      }
    } else if (metadata != null) {
      metadata.toString(params, builder);
      return;
    } else if (statement != null) {
      builder.append("(");
      statement.toString(params, builder);
      builder.append(")");
      return;
    } else if (inputParam != null) {
      inputParam.toString(params, builder);
    } else if (functionCall != null) {
      functionCall.toString(params, builder);
    } else if (identifier != null) {
      identifier.toString(params, builder);
    }
    if (modifier != null) {
      modifier.toString(params, builder);
    }
  }

  @Override
  public void toGenericStatement(StringBuilder builder) {
    if (rids != null && !rids.isEmpty()) {
      if (rids.size() == 1) {
        rids.getFirst().toGenericStatement(builder);
        return;
      } else {
        builder.append("[");
        var first = true;
        for (var rid : rids) {
          if (!first) {
            builder.append(", ");
          }
          rid.toGenericStatement(builder);
          first = false;
        }
        builder.append("]");
        return;
      }
    } else if (inputParams != null && !inputParams.isEmpty()) {
      if (inputParams.size() == 1) {
        inputParams.getFirst().toGenericStatement(builder);
        return;
      } else {
        builder.append("[");
        var first = true;
        for (var rid : inputParams) {
          if (!first) {
            builder.append(", ");
          }
          rid.toGenericStatement(builder);
          first = false;
        }
        builder.append("]");
        return;
      }
    } else if (metadata != null) {
      metadata.toGenericStatement(builder);
      return;
    } else if (statement != null) {
      builder.append("(");
      statement.toGenericStatement(builder);
      builder.append(")");
      return;
    } else if (inputParam != null) {
      inputParam.toGenericStatement(builder);
    } else if (functionCall != null) {
      functionCall.toGenericStatement(builder);
    } else if (identifier != null) {
      identifier.toGenericStatement(builder);
    }
    if (modifier != null) {
      modifier.toGenericStatement(builder);
    }
  }

  public SQLIdentifier getIdentifier() {
    return identifier;
  }

  @Nullable
  public SchemaClassInternal getSchemaClass(DatabaseSessionEmbedded session) {
    if (identifier == null) {
      return null;
    }

    var stringValue = identifier.getStringValue();
    if (stringValue != null && !stringValue.isEmpty()) {
      return session.getMetadata().getImmutableSchemaSnapshot().getClassInternal(stringValue);
    }

    return null;
  }

  public List<SQLRid> getRids() {
    return rids;
  }

  public SQLMetadataIdentifier getMetadata() {
    return metadata;
  }

  public SQLStatement getStatement() {
    return statement;
  }

  public SQLInputParameter getInputParam() {
    return inputParam;
  }

  public List<SQLInputParameter> getInputParams() {
    return inputParams;
  }

  public SQLFunctionCall getFunctionCall() {
    return functionCall;
  }

  public SQLModifier getModifier() {
    return modifier;
  }

  @Override
  public SQLFromItem copy() {
    var result = new SQLFromItem(-1);
    if (rids != null) {
      result.rids = rids.stream().map(SQLRid::copy).collect(Collectors.toList());
    }
    if (inputParams != null) {
      result.inputParams = inputParams.stream().map(SQLInputParameter::copy)
          .collect(Collectors.toList());
    }
    result.metadata = metadata == null ? null : metadata.copy();
    result.statement = statement == null ? null : statement.copy();
    result.inputParam = inputParam == null ? null : inputParam.copy();
    result.identifier = identifier == null ? null : identifier.copy();
    result.functionCall = functionCall == null ? null : functionCall.copy();
    result.modifier = modifier == null ? null : modifier.copy();

    return result;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }

    var oFromItem = (SQLFromItem) o;

    if (!Objects.equals(rids, oFromItem.rids)) {
      return false;
    }
    if (!Objects.equals(inputParams, oFromItem.inputParams)) {
      return false;
    }
    if (!Objects.equals(metadata, oFromItem.metadata)) {
      return false;
    }
    if (!Objects.equals(statement, oFromItem.statement)) {
      return false;
    }
    if (!Objects.equals(inputParam, oFromItem.inputParam)) {
      return false;
    }
    if (!Objects.equals(identifier, oFromItem.identifier)) {
      return false;
    }
    if (!Objects.equals(functionCall, oFromItem.functionCall)) {
      return false;
    }
    return Objects.equals(modifier, oFromItem.modifier);
  }

  @Override
  public int hashCode() {
    var result = rids != null ? rids.hashCode() : 0;
    result = 31 * result + (inputParams != null ? inputParams.hashCode() : 0);
    result = 31 * result + (metadata != null ? metadata.hashCode() : 0);
    result = 31 * result + (statement != null ? statement.hashCode() : 0);
    result = 31 * result + (inputParam != null ? inputParam.hashCode() : 0);
    result = 31 * result + (identifier != null ? identifier.hashCode() : 0);
    result = 31 * result + (functionCall != null ? functionCall.hashCode() : 0);
    result = 31 * result + (modifier != null ? modifier.hashCode() : 0);
    return result;
  }

  public void setRids(List<SQLRid> rids) {
    this.rids = rids;
  }

  public void setMetadata(SQLMetadataIdentifier metadata) {
    this.metadata = metadata;
  }

  public void setStatement(SQLStatement statement) {
    this.statement = statement;
  }

  public void setInputParam(SQLInputParameter inputParam) {
    this.inputParam = inputParam;
  }

  public void setIdentifier(SQLIdentifier identifier) {
    this.identifier = identifier;
  }

  public void setFunctionCall(SQLFunctionCall functionCall) {
    this.functionCall = functionCall;
  }

  public void setModifier(SQLModifier modifier) {
    this.modifier = modifier;
  }

  public void setInputParams(List<SQLInputParameter> inputParams) {
    this.inputParams = inputParams;
  }

  public Result serialize(DatabaseSessionEmbedded session) {
    var result = new ResultInternal(session);
    if (rids != null) {
      result.setProperty(
          "rids", rids.stream().map(x -> x.serialize(session)).collect(Collectors.toList()));
    }
    if (inputParams != null) {
      result.setProperty(
          "inputParams", rids.stream().map(x -> x.serialize(session)).collect(Collectors.toList()));
    }
    if (metadata != null) {
      result.setProperty("metadata", metadata.serialize(session));
    }
    if (statement != null) {
      result.setProperty("statement", statement.serialize(session));
    }
    if (inputParam != null) {
      result.setProperty("inputParam", inputParam.serialize(session));
    }
    if (identifier != null) {
      result.setProperty("identifier", identifier.serialize(session));
    }
    if (functionCall != null) {
      result.setProperty("functionCall", functionCall.serialize(session));
    }
    if (modifier != null) {
      result.setProperty("modifier", modifier.serialize(session));
    }

    return result;
  }

  public void deserialize(Result fromResult) {
    if (fromResult.getProperty("rids") != null) {
      List<Result> serRids = fromResult.getProperty("rids");
      rids = new ArrayList<>();
      for (var res : serRids) {
        var rid = new SQLRid(-1);
        rid.deserialize(res);
        rids.add(rid);
      }
    }

    if (fromResult.getProperty("inputParams") != null) {
      List<Result> ser = fromResult.getProperty("inputParams");
      inputParams = new ArrayList<>();
      for (var res : ser) {
        inputParams.add(SQLInputParameter.deserializeFromOResult(res));
      }
    }
    if (fromResult.getProperty("metadata") != null) {
      metadata = new SQLMetadataIdentifier(-1);
      metadata.deserialize(fromResult.getProperty("metadata"));
    }
    if (fromResult.getProperty("statement") != null) {
      statement = SQLStatement.deserializeFromOResult(fromResult.getProperty("statement"));
    }
    if (fromResult.getProperty("inputParam") != null) {
      inputParam = SQLInputParameter.deserializeFromOResult(fromResult.getProperty("inputParam"));
    }
    if (fromResult.getProperty("identifier") != null) {
      identifier = SQLIdentifier.deserialize(fromResult.getProperty("identifier"));
    }
    if (fromResult.getProperty("functionCall") != null) {
      functionCall = new SQLFunctionCall(-1);
      functionCall.deserialize(fromResult.getProperty("functionCall"));
    }
    if (fromResult.getProperty("modifier") != null) {
      modifier = new SQLModifier(-1);
      modifier.deserialize(fromResult.getProperty("modifier"));
    }
  }

  public boolean isCacheable(DatabaseSessionEmbedded session) {
    if (modifier != null) {
      return false;
    }
    if (inputParam != null) {
      return false;
    }
    if (inputParams != null && !inputParams.isEmpty()) {
      return false;
    }
    if (statement != null) {
      return statement.executinPlanCanBeCached(session);
    }
    if (functionCall != null) {
      return functionCall.isCacheable(session);
    }

    return true;
  }

  public boolean refersToParent() {
    if (modifier != null && modifier.refersToParent()) {
      return true;
    }
    if (statement != null && statement.refersToParent()) {
      return true;
    }
    return functionCall != null && functionCall.refersToParent();
  }

  public void addRid(SQLRid rid) {
    this.rids.add(rid);
  }

  public void addInputParam(SQLInputParameter par) {
    this.inputParams.add(par);
  }
}
/* JavaCC - OriginalChecksum=f64e3b4d2a2627a1b5d04a7dcb95fa94 (do not edit this line) */
