/* Generated By:JJTree: Do not edit this line. SQLFunctionCall.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=O,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.jetbrains.youtrackdb.internal.core.sql.parser;

import com.jetbrains.youtrackdb.internal.core.command.CommandContext;
import com.jetbrains.youtrackdb.internal.core.db.DatabaseSessionEmbedded;
import com.jetbrains.youtrackdb.internal.core.db.record.record.Identifiable;
import com.jetbrains.youtrackdb.internal.core.exception.CommandExecutionException;
import com.jetbrains.youtrackdb.internal.core.metadata.schema.schema.SchemaClass;
import com.jetbrains.youtrackdb.internal.core.query.Result;
import com.jetbrains.youtrackdb.internal.core.sql.SQLEngine;
import com.jetbrains.youtrackdb.internal.core.sql.executor.AggregationContext;
import com.jetbrains.youtrackdb.internal.core.sql.executor.FuncitonAggregationContext;
import com.jetbrains.youtrackdb.internal.core.sql.executor.ResultInternal;
import com.jetbrains.youtrackdb.internal.core.sql.functions.IndexableSQLFunction;
import com.jetbrains.youtrackdb.internal.core.sql.functions.SQLFunction;
import com.jetbrains.youtrackdb.internal.core.sql.functions.graph.SQLFunctionMove;
import com.jetbrains.youtrackdb.internal.core.sql.functions.graph.SQLGraphNavigationFunction;
import java.util.ArrayList;
import java.util.Collection;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Set;
import java.util.stream.Collectors;
import javax.annotation.Nullable;

public final class SQLFunctionCall extends SimpleNode {

  SQLIdentifier name;

  List<SQLExpression> params = new ArrayList<>();

  boolean polymorphicLabelsInGraphNavigation = true;

  public SQLFunctionCall(int id) {
    super(id);
  }

  public SQLFunctionCall(YouTrackDBSql p, int id) {
    super(p, id);
  }

  public boolean isStar() {

    if (this.params.size() != 1) {
      return false;
    }
    var param = params.getFirst();
    if (!(param.mathExpression instanceof SQLBaseExpression base)) {

      return false;
    }
    if (base.getIdentifier() == null || base.getIdentifier().suffix == null) {
      return false;
    }
    return base.getIdentifier().suffix.star;
  }

  public List<SQLExpression> getParams() {
    return params;
  }

  public void setParams(List<SQLExpression> params) {
    this.params = params;
  }

  public void addParam(SQLExpression param) {
    this.params.add(param);
  }

  @Override
  public void toString(Map<Object, Object> params, StringBuilder builder) {
    name.toString(params, builder);
    builder.append("(");
    var first = true;
    for (var expr : this.params) {
      if (!first) {
        builder.append(", ");
      }
      expr.toString(params, builder);
      first = false;
    }
    builder.append(")");
  }

  @Override
  public void toGenericStatement(StringBuilder builder) {
    name.toGenericStatement(builder);
    builder.append("(");
    var first = true;
    for (var expr : this.params) {
      if (!first) {
        builder.append(", ");
      }
      expr.toGenericStatement(builder);
      first = false;
    }
    builder.append(")");
  }

  public Object execute(Object targetObjects, CommandContext ctx) {
    return execute(targetObjects, ctx, name.getStringValue());
  }

  private Object execute(Object targetObjects, CommandContext ctx, String name) {
    List<Object> paramValues = new ArrayList<>();

    Object record;

    if (targetObjects instanceof Identifiable) {
      record = targetObjects;
    } else if (targetObjects instanceof Result result && result.isEntity()) {
      record = result.asEntity();
    } else {
      record = targetObjects;
    }

    if (record == null) {
      var current = ctx == null ? null : ctx.getSystemVariable(CommandContext.VAR_CURRENT);
      if (current != null) {
        if (current instanceof Identifiable) {
          record = current;
        } else if (current instanceof Result result && result.isEntity()) {
          record = result.asEntity();
        } else {
          record = current;
        }
      }
    }
    for (var expr : this.params) {
      if (targetObjects instanceof Result) {
        paramValues.add(expr.execute((Result) targetObjects, ctx));
      } else if (record instanceof Identifiable) {
        paramValues.add(expr.execute((Identifiable) record, ctx));
      } else if (record instanceof Result) {
        paramValues.add(expr.execute((Result) record, ctx));
      } else if (record == null) {
        paramValues.add(expr.execute((Result) record, ctx));
      } else {
        throw new CommandExecutionException(ctx.getDatabaseSession(),
            "Invalid value for $current: " + record);
      }
    }
    var function = SQLEngine.getFunction(ctx.getDatabaseSession(), name);
    if (function != null) {
      function.config(this.params.toArray());

      validateFunctionParams(ctx.getDatabaseSession(), function, paramValues.size());

      ctx.setVariable("aggregation", false);
      var session = ctx.getDatabaseSession();
      return switch (record) {
        case Identifiable identifiable -> {
          var transaction = session.getActiveTransaction();
          yield function.execute(targetObjects, transaction.loadEntity(identifiable), null,
              paramValues.toArray(),
              ctx);
        }
        case Result result -> function.execute(
            targetObjects,
            result,
            null,
            paramValues.toArray(),
            ctx);
        case null -> function.execute(targetObjects, null, null, paramValues.toArray(), ctx);
        default ->
            throw new CommandExecutionException(session, "Invalid value for $current: " + record);
      };
    } else {
      throw new CommandExecutionException(ctx.getDatabaseSession(), "Funciton not found: " + name);
    }
  }

  private static void validateFunctionParams(DatabaseSessionEmbedded session, SQLFunction function,
      int paramsCount) {
    if (function.getMaxParams(session) == -1 || function.getMaxParams(session) > 0) {
      if (paramsCount < function.getMinParams()
          || (function.getMaxParams(session) > -1 && paramsCount > function.getMaxParams(
          session))) {
        String params;
        if (function.getMinParams() == function.getMaxParams(session)) {
          params = "" + function.getMinParams();
        } else {
          params = function.getMinParams() + "-" + function.getMaxParams(session);
        }
        throw new CommandExecutionException(session,
            "Syntax error: function '"
                + function.getName(session)
                + "' needs "
                + params
                + " argument(s) while has been received "
                + paramsCount);
      }
    }
  }

  public boolean isIndexedFunctionCall(DatabaseSessionEmbedded session) {
    var function = SQLEngine.getFunctionOrNull(session, name.getStringValue());
    return (function instanceof IndexableSQLFunction);
  }

  public boolean isGraphNavigationFunction(DatabaseSessionEmbedded session) {
    var function = SQLEngine.getFunctionOrNull(session, name.getStringValue());
    return (function instanceof SQLGraphNavigationFunction);
  }

  @Nullable
  public Collection<String> getGraphNavigationFunctionProperties(CommandContext ctx,
      SchemaClass schemaClass) {
    var session = ctx.getDatabaseSession();
    var function = SQLEngine.getFunction(session, name.getStringValue());

    if (function instanceof SQLGraphNavigationFunction graphRelationsFunction) {
      var labels = new String[params.size()];

      for (var i = 0; i < params.size(); i++) {
        var param = params.get(i);

        if (param.isEarlyCalculated(ctx)) {
          var result = param.execute((Result) null, ctx);

          if (result instanceof String label) {
            labels[i] = label;
          } else {
            return null;
          }
        } else {
          return null;
        }
      }

      return graphRelationsFunction.propertyNamesForIndexCandidates(
          labels,
          schemaClass, polymorphicLabelsInGraphNavigation, session);
    }

    return null;
  }

  @Nullable
  public Iterable<Identifiable> executeIndexedFunction(
      SQLFromClause target, CommandContext ctx, SQLBinaryCompareOperator operator,
      Object rightValue) {
    var function = SQLEngine
        .getFunction(ctx.getDatabaseSession(), name.getStringValue());
    if (function instanceof IndexableSQLFunction) {
      return ((IndexableSQLFunction) function)
          .searchFromTarget(
              target, operator, rightValue, ctx, this.params.toArray(new SQLExpression[]{}));
    }
    return null;
  }

  /**
   * @param target     query target
   * @param ctx        execution context
   * @param operator   operator at the right of the function
   * @param rightValue value to compare to funciton result
   * @return the approximate number of items returned by the condition execution, -1 if the
   * extimation cannot be executed
   */
  public long estimateIndexedFunction(
      SQLFromClause target, CommandContext ctx, SQLBinaryCompareOperator operator,
      Object rightValue) {
    var function = SQLEngine
        .getFunction(ctx.getDatabaseSession(), name.getStringValue());
    if (function instanceof IndexableSQLFunction) {
      return ((IndexableSQLFunction) function)
          .estimate(target, operator, rightValue, ctx, this.params.toArray(new SQLExpression[]{}));
    }
    return -1;
  }

  /**
   * tests if current function is an indexed function AND that function can also be executed without
   * using the index
   *
   * @param target  the query target
   * @param context the execution context
   * @return true if current function is an indexed funciton AND that function can also be executed
   * without using the index, false otherwise
   */
  public boolean canExecuteIndexedFunctionWithoutIndex(
      SQLFromClause target, CommandContext context, SQLBinaryCompareOperator operator,
      Object right) {
    var function = SQLEngine
        .getFunction(context.getDatabaseSession(), name.getStringValue());
    if (function instanceof IndexableSQLFunction) {
      return ((IndexableSQLFunction) function)
          .canExecuteInline(
              target, operator, right, context, this.params.toArray(new SQLExpression[]{}));
    }
    return false;
  }

  /**
   * tests if current function is an indexed function AND that function can be used on this target
   *
   * @param target  the query target
   * @param context the execution context
   * @return true if current function is an indexed function AND that function can be used on this
   * target, false otherwise
   */
  public boolean allowsIndexedFunctionExecutionOnTarget(
      SQLFromClause target, CommandContext context, SQLBinaryCompareOperator operator,
      Object right) {
    var function = SQLEngine
        .getFunction(context.getDatabaseSession(), name.getStringValue());
    if (function instanceof IndexableSQLFunction) {
      return ((IndexableSQLFunction) function)
          .allowsIndexedExecution(
              target, operator, right, context, this.params.toArray(new SQLExpression[]{}));
    }
    return false;
  }

  /**
   * tests if current expression is an indexed function AND the function has also to be executed
   * after the index search. In some cases, the index search is accurate, so this condition can be
   * excluded from further evaluation. In other cases the result from the index is a superset of the
   * expected result, so the function has to be executed anyway for further filtering
   *
   * @param target  the query target
   * @param context the execution context
   * @return true if current expression is an indexed function AND the function has also to be
   * executed after the index search.
   */
  public boolean executeIndexedFunctionAfterIndexSearch(
      SQLFromClause target, CommandContext context, SQLBinaryCompareOperator operator,
      Object right) {
    var function = SQLEngine
        .getFunction(context.getDatabaseSession(), name.getStringValue());
    if (function instanceof IndexableSQLFunction) {
      return ((IndexableSQLFunction) function)
          .shouldExecuteAfterSearch(
              target, operator, right, context, this.params.toArray(new SQLExpression[]{}));
    }
    return false;
  }

  public boolean isExpand() {
    return name.getStringValue().equalsIgnoreCase("expand");
  }

  public boolean needsAliases(Set<String> aliases) {
    for (var param : params) {
      if (param.needsAliases(aliases)) {
        return true;
      }
    }
    return false;
  }

  public boolean isAggregate(DatabaseSessionEmbedded session) {
    if (isAggregateFunction(session)) {
      return true;
    }

    for (var exp : params) {
      if (exp.isAggregate(session)) {
        return true;
      }
    }

    return false;
  }

  public SimpleNode splitForAggregation(
      AggregateProjectionSplit aggregateProj, CommandContext ctx) {
    var db = ctx.getDatabaseSession();
    if (isAggregate(db)) {
      var newFunct = new SQLFunctionCall(-1);
      newFunct.name = this.name;
      var functionResultAlias = aggregateProj.getNextAlias();

      if (isAggregateFunction(db)) {

        if (isStar()) {
          newFunct.params.addAll(params);
        } else {
          for (var param : params) {
            if (param.isAggregate(db)) {
              throw new CommandExecutionException(ctx.getDatabaseSession(),
                  "Cannot calculate an aggregate function of another aggregate function " + this);
            }
            var nextAlias = aggregateProj.getNextAlias();
            var paramItem = new SQLProjectionItem(-1);
            paramItem.alias = nextAlias;
            paramItem.expression = param;
            aggregateProj.getPreAggregate().add(paramItem);

            newFunct.params.add(new SQLExpression(nextAlias));
          }
        }
        aggregateProj.getAggregate().add(createProjection(newFunct, functionResultAlias));
        return new SQLExpression(functionResultAlias);
      } else {
        if (isStar()) {
          newFunct.params.addAll(params);
        } else {
          for (var param : params) {
            newFunct.params.add(param.splitForAggregation(aggregateProj, ctx));
          }
        }
      }
      return newFunct;
    }
    return this;
  }

  private boolean isAggregateFunction(DatabaseSessionEmbedded session) {
    var function = SQLEngine.getFunction(session, name.getStringValue());
    function.config(this.params.toArray());
    return function.aggregateResults();
  }

  private static SQLProjectionItem createProjection(SQLFunctionCall newFunct, SQLIdentifier alias) {
    var l0 = new SQLLevelZeroIdentifier(-1);
    l0.functionCall = newFunct;
    var l1 = new SQLBaseIdentifier(-1);
    l1.levelZero = l0;
    var l2 = new SQLBaseExpression(-1);
    l2.setIdentifier(l1);
    var l3 = new SQLExpression(-1);
    l3.mathExpression = l2;
    var item = new SQLProjectionItem(-1);
    item.alias = alias;
    item.expression = l3;
    return item;
  }

  public boolean isEarlyCalculated(CommandContext ctx) {

    if (isTraverseFunction(ctx.getDatabaseSession())) {
      return false;
    }

    for (var param : params) {
      if (!param.isEarlyCalculated(ctx)) {
        return false;
      }
    }

    return true;
  }

  private boolean isTraverseFunction(DatabaseSessionEmbedded session) {
    if (name == null) {
      return false;
    }
    var function = SQLEngine.getFunction(session, name.value);
    return function instanceof SQLFunctionMove;
  }

  public AggregationContext getAggregationContext(CommandContext ctx) {
    var function = SQLEngine
        .getFunction(ctx.getDatabaseSession(), name.getStringValue());
    function.config(this.params.toArray());

    return new FuncitonAggregationContext(function, this.params);
  }

  @Override
  public SQLFunctionCall copy() {
    var result = new SQLFunctionCall(-1);
    result.name = name;
    result.params = params.stream().map(SQLExpression::copy).collect(Collectors.toList());
    return result;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }

    var that = (SQLFunctionCall) o;

    if (!Objects.equals(name, that.name)) {
      return false;
    }
    return Objects.equals(params, that.params);
  }

  @Override
  public int hashCode() {
    var result = name != null ? name.hashCode() : 0;
    result = 31 * result + (params != null ? params.hashCode() : 0);
    return result;
  }

  public boolean refersToParent() {
    if (params != null) {
      for (var param : params) {
        if (param != null && param.refersToParent()) {
          return true;
        }
      }
    }
    return false;
  }

  public SQLIdentifier getName() {
    return name;
  }

  public SQLMethodCall toMethod() {
    var result = new SQLMethodCall(-1);
    result.methodName = name.copy();
    result.params = params.stream().map(SQLExpression::copy).collect(Collectors.toList());
    return result;
  }

  public Result serialize(DatabaseSessionEmbedded session) {
    var result = new ResultInternal(session);

    if (name != null) {
      result.setProperty("name", name.serialize(session));
    }

    if (params != null) {
      result.setProperty(
          "collection", params.stream().map(oExpression -> oExpression.serialize(session))
              .collect(Collectors.toList()));
    }

    return result;
  }

  public void deserialize(Result fromResult) {
    if (fromResult.getProperty("name") != null) {
      name = SQLIdentifier.deserialize(fromResult.getProperty("name"));
    }
    if (fromResult.getProperty("params") != null) {
      params = new ArrayList<>();
      List<Result> ser = fromResult.getProperty("params");
      for (var item : ser) {
        var exp = new SQLExpression(-1);
        exp.deserialize(item);
        params.add(exp);
      }
    }
  }

  public void extractSubQueries(SQLIdentifier letAlias, SubQueryCollector collector) {
    for (var param : this.params) {
      param.extractSubQueries(letAlias, collector);
    }
  }

  public void extractSubQueries(SubQueryCollector collector) {
    for (var param : this.params) {
      param.extractSubQueries(collector);
    }
  }

  public boolean isCacheable(DatabaseSessionEmbedded session) {
    return isGraphNavigationFunction(session); // TODO
  }

  public boolean varMightBeInUse(String varName) {
    for (var param : params) {
      if (param.varMightBeInUse(varName)) {
        return true;
      }
    }
    return false;
  }
}
/* JavaCC - OriginalChecksum=290d4e1a3f663299452e05f8db718419 (do not edit this line) */
