/* Generated By:JJTree: Do not edit this line. SQLFromClause.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=O,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.jetbrains.youtrackdb.internal.core.sql.parser;

import com.jetbrains.youtrackdb.internal.core.db.DatabaseSessionEmbedded;
import com.jetbrains.youtrackdb.internal.core.metadata.schema.SchemaClassInternal;
import com.jetbrains.youtrackdb.internal.core.query.Result;
import com.jetbrains.youtrackdb.internal.core.sql.executor.ResultInternal;
import java.util.Map;
import java.util.Objects;
import javax.annotation.Nullable;

public class SQLFromClause extends SimpleNode {

  protected SQLFromItem item;

  public SQLFromClause(int id) {
    super(id);
  }

  public SQLFromClause(YouTrackDBSql p, int id) {
    super(p, id);
  }

  @Override
  public void toString(Map<Object, Object> params, StringBuilder builder) {
    if (item != null) {
      item.toString(params, builder);
    }
  }

  @Override
  public void toGenericStatement(StringBuilder builder) {
    if (item != null) {
      item.toGenericStatement(builder);
    }
  }

  public SQLFromItem getItem() {
    return item;
  }

  @Nullable
  public SchemaClassInternal getSchemaClass(DatabaseSessionEmbedded session) {
    if (item != null) {
      return item.getSchemaClass(session);
    }

    return null;
  }

  public void setItem(SQLFromItem item) {
    this.item = item;
  }

  @Override
  public SQLFromClause copy() {
    var result = new SQLFromClause(-1);
    result.item = item.copy();
    return result;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }

    var that = (SQLFromClause) o;

    return Objects.equals(item, that.item);
  }

  @Override
  public int hashCode() {
    return item != null ? item.hashCode() : 0;
  }

  public Result serialize(DatabaseSessionEmbedded session) {
    var result = new ResultInternal(session);
    result.setProperty("item", item.serialize(session));
    return result;
  }

  public void deserialize(Result fromResult) {
    item = new SQLFromItem(-1);
    item.deserialize(fromResult.getProperty("item"));
  }

  public boolean isCacheable(DatabaseSessionEmbedded session) {
    return item.isCacheable(session);
  }

  public boolean refersToParent() {
    return item.refersToParent();
  }
}
/* JavaCC - OriginalChecksum=051839d20dabfa4cce26ebcbe0d03a86 (do not edit this line) */
