/* Generated By:JJTree: Do not edit this line. SQLGeOperator.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=O,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */

/*
 *
 *  *  Copyright YouTrackDB
 *  *
 *  *  Licensed under the Apache License, Version 2.0 (the "License");
 *  *  you may not use this file except in compliance with the License.
 *  *  You may obtain a copy of the License at
 *  *
 *  *       http://www.apache.org/licenses/LICENSE-2.0
 *  *
 *  *  Unless required by applicable law or agreed to in writing, software
 *  *  distributed under the License is distributed on an "AS IS" BASIS,
 *  *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  *  See the License for the specific language governing permissions and
 *  *  limitations under the License.
 *  *
 *
 *
 */

package com.jetbrains.youtrackdb.internal.core.sql.parser;

import com.jetbrains.youtrackdb.internal.core.db.DatabaseSessionEmbedded;
import com.jetbrains.youtrackdb.internal.core.sql.executor.metadata.IndexFinder.Operation;
import java.util.Map;
import javax.annotation.Nonnull;

public class SQLGeOperator extends SimpleNode implements SQLBinaryCompareOperator {

  public SQLGeOperator(int id) {
    super(id);
  }

  public SQLGeOperator(YouTrackDBSql p, int id) {
    super(p, id);
  }

  @Override
  public boolean execute(@Nonnull DatabaseSessionEmbedded session, Object left, Object right) {
    var result = SQLBinaryCompareOperator.doCompare(left, right);
    return result != null && result >= 0;
  }


  @Override
  public String toString() {
    return ">=";
  }

  @Override
  public void toString(Map<Object, Object> params, StringBuilder builder) {
    builder.append(">=");
  }

  @Override
  public void toGenericStatement(StringBuilder builder) {
    builder.append(">=");
  }

  @Override
  public boolean supportsBasicCalculation() {
    return true;
  }

  @Override
  public SQLGeOperator copy() {
    return this;
  }

  @Override
  public boolean isRangeOperator() {
    return true;
  }

  @Override
  public Operation getOperation() {
    return Operation.Ge;
  }

  @Override
  public boolean equals(Object obj) {
    return obj != null && obj.getClass().equals(this.getClass());
  }

  @Override
  public int hashCode() {
    return getClass().hashCode();
  }
}
/* JavaCC - OriginalChecksum=960da239569d393eb155f7d8a871e6d5 (do not edit this line) */
