/* Generated By:JJTree: Do not edit this line. SQLGtOperator.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=O,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.jetbrains.youtrackdb.internal.core.sql.parser;

import com.jetbrains.youtrackdb.internal.core.db.DatabaseSessionEmbedded;
import com.jetbrains.youtrackdb.internal.core.sql.executor.metadata.IndexFinder.Operation;
import java.util.Map;
import javax.annotation.Nonnull;

public class SQLGtOperator extends SimpleNode implements SQLBinaryCompareOperator {

  public static final SQLGtOperator INSTANCE = new SQLGtOperator(-1);

  public SQLGtOperator(int id) {
    super(id);
  }

  public SQLGtOperator(YouTrackDBSql p, int id) {
    super(p, id);
  }

  @Override
  public boolean execute(@Nonnull DatabaseSessionEmbedded session, Object iLeft, Object iRight) {
    var result = SQLBinaryCompareOperator.doCompare(iLeft, iRight);
    return result != null && result > 0;
  }

  @Override
  public String toString() {
    return ">";
  }

  @Override
  public void toGenericStatement(StringBuilder builder) {
    builder.append(">");
  }

  @Override
  public void toString(Map<Object, Object> params, StringBuilder builder) {
    builder.append(">");
  }

  @Override
  public boolean supportsBasicCalculation() {
    return true;
  }

  @Override
  public SQLGtOperator copy() {
    return this;
  }

  @Override
  public boolean isRangeOperator() {
    return true;
  }

  @Override
  public Operation getOperation() {
    return Operation.Gt;
  }

  @Override
  public boolean equals(Object obj) {
    return obj != null && obj.getClass().equals(this.getClass());
  }

  @Override
  public int hashCode() {
    return getClass().hashCode();
  }
}
/* JavaCC - OriginalChecksum=4b96739fc6e9ae496916d542db361376 (do not edit this line) */
