package com.jetbrains.youtrackdb.internal.core.sql.parser;

import com.jetbrains.youtrackdb.internal.core.command.CommandContext;
import com.jetbrains.youtrackdb.internal.core.db.DatabaseSessionEmbedded;
import com.jetbrains.youtrackdb.internal.core.db.record.record.Entity;
import com.jetbrains.youtrackdb.internal.core.db.record.record.Identifiable;
import com.jetbrains.youtrackdb.internal.core.exception.CommandExecutionException;
import com.jetbrains.youtrackdb.internal.core.metadata.schema.schema.Collate;
import com.jetbrains.youtrackdb.internal.core.query.Result;
import com.jetbrains.youtrackdb.internal.core.record.impl.EntityImpl;
import com.jetbrains.youtrackdb.internal.core.sql.executor.AggregationContext;
import com.jetbrains.youtrackdb.internal.core.sql.executor.ResultInternal;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Set;
import javax.annotation.Nullable;

/// Expression that returns value of property using internal API in opposite to public API.
///
/// Public API is used by default in SQL engine to automatically handle security rules and attempts
/// to access internal properties that represent, for example, an edges.
///
/// This expression is not generated by pares but only created during AST post-processing.
public class SQLGetInternalPropertyExpression extends SQLExpression {

  private String propertyName;

  public SQLGetInternalPropertyExpression(String propertyName) {
    super(-1);
    this.propertyName = propertyName;
  }

  @Nullable
  @Override
  public Object execute(Identifiable iCurrentRecord, CommandContext ctx) {
    var session = ctx.getDatabaseSession();
    var tx = session.getTransactionInternal();
    var entity = (EntityImpl) tx.loadEntity(iCurrentRecord);

    return entity.getPropertyInternal(propertyName);
  }

  @Nullable
  @Override
  public Object execute(Result iCurrentRecord, CommandContext ctx) {
    if (iCurrentRecord.isEntity()) {
      return execute((Identifiable) iCurrentRecord.asEntity(), ctx);
    }

    return iCurrentRecord.getProperty(propertyName);
  }

  @Override
  public boolean isBaseIdentifier() {
    return true;
  }

  @Override
  public boolean isEarlyCalculated(CommandContext ctx) {
    return false;
  }

  @Override
  public SQLIdentifier getDefaultAlias() {
    return new SQLIdentifier(propertyName);
  }

  @Override
  public void toString(Map<Object, Object> params, StringBuilder builder) {
    builder.append(propertyName);
  }

  @Override
  public boolean supportsBasicCalculation() {
    return false;
  }

  @Override
  public boolean isIndexedFunctionCal(DatabaseSessionEmbedded session) {
    return false;
  }

  @Override
  public boolean canExecuteIndexedFunctionWithoutIndex(
      SQLFromClause target, CommandContext context, SQLBinaryCompareOperator operator,
      Object right) {
    return false;
  }

  @Override
  public boolean allowsIndexedFunctionExecutionOnTarget(
      SQLFromClause target, CommandContext context, SQLBinaryCompareOperator operator,
      Object right) {
    return false;
  }

  @Override
  public boolean executeIndexedFunctionAfterIndexSearch(
      SQLFromClause target, CommandContext context, SQLBinaryCompareOperator operator,
      Object right) {
    return false;
  }

  @Override
  public boolean isExpand() {
    return false;
  }

  @Override
  @Nullable
  public SQLValueExpression getExpandContent() {
    return null;
  }

  @Override
  public boolean needsAliases(Set<String> aliases) {
    return false;
  }

  @Override
  public boolean isAggregate(DatabaseSessionEmbedded session) {
    return false;
  }

  @Override
  public AggregationContext getAggregationContext(CommandContext ctx) {
    throw new CommandExecutionException(ctx.getDatabaseSession(), "Cannot aggregate on " + this);
  }

  @Override
  public SQLGetInternalPropertyExpression copy() {
    return new SQLGetInternalPropertyExpression(propertyName);
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }

    var that = (SQLGetInternalPropertyExpression) o;
    return Objects.equals(propertyName, that.propertyName);
  }

  @Override
  public int hashCode() {
    return propertyName.hashCode();
  }

  @Override
  public void extractSubQueries(SubQueryCollector collector) {
  }

  @Override
  public void extractSubQueries(SQLIdentifier letAlias, SubQueryCollector collector) {
  }

  @Override
  public boolean refersToParent() {
    return false;
  }

  @Override
  @Nullable
  public List<String> getMatchPatternInvolvedAliases() {
    return null;
  }

  @Override
  public void applyRemove(ResultInternal result, CommandContext ctx) {
    throw new CommandExecutionException(ctx.getDatabaseSession(), "Cannot apply REMOVE " + this);
  }

  @Override
  public boolean isCount() {
    return false;
  }

  @Override
  public Result serialize(DatabaseSessionEmbedded session) {
    var result = new ResultInternal(session);
    result.setProperty("propertyName", propertyName);
    return result;
  }

  @Override
  public void deserialize(Result fromResult) {
    propertyName = fromResult.getString("propertyName");
  }

  @Override
  public boolean isDefinedFor(Result currentRecord) {
    return true;
  }

  @Override
  public boolean isDefinedFor(DatabaseSessionEmbedded db, Entity currentRecord) {
    return true;
  }

  @Override
  @Nullable
  public Collate getCollate(Result currentRecord, CommandContext ctx) {
    return null;
  }

  @Override
  public boolean isCacheable(DatabaseSessionEmbedded session) {
    return true;
  }

  @Override
  public boolean varMightBeInUse(String varName) {
    return false;
  }
}
