/* Generated By:JJTree: Do not edit this line. SQLJson.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=O,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.jetbrains.youtrackdb.internal.core.sql.parser;

import com.jetbrains.youtrackdb.internal.core.command.CommandContext;
import com.jetbrains.youtrackdb.internal.core.db.DatabaseSessionEmbedded;
import com.jetbrains.youtrackdb.internal.core.db.record.record.Entity;
import com.jetbrains.youtrackdb.internal.core.db.record.record.Identifiable;
import com.jetbrains.youtrackdb.internal.core.metadata.schema.PropertyTypeInternal;
import com.jetbrains.youtrackdb.internal.core.query.Result;
import com.jetbrains.youtrackdb.internal.core.record.impl.EntityHelper;
import com.jetbrains.youtrackdb.internal.core.record.impl.EntityImpl;
import com.jetbrains.youtrackdb.internal.core.serialization.serializer.record.string.FieldTypesString;
import com.jetbrains.youtrackdb.internal.core.sql.executor.ResultInternal;
import com.jetbrains.youtrackdb.internal.core.sql.executor.UpdatableResult;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Locale;
import java.util.Map;
import java.util.Objects;
import java.util.Set;
import java.util.stream.Collectors;
import javax.annotation.Nullable;

public class SQLJson extends SimpleNode {

  protected List<SQLJsonItem> items = new ArrayList<SQLJsonItem>();

  public SQLJson(int id) {
    super(id);
  }

  public SQLJson(YouTrackDBSql p, int id) {
    super(p, id);
  }

  @Override
  public void toString(Map<Object, Object> params, StringBuilder builder) {
    builder.append("{");
    var first = true;
    for (var item : items) {
      if (!first) {
        builder.append(", ");
      }
      item.toString(params, builder);

      first = false;
    }
    builder.append("}");
  }

  @Override
  public void toGenericStatement(StringBuilder builder) {
    builder.append("{");
    var first = true;
    for (var item : items) {
      if (!first) {
        builder.append(", ");
      }
      item.toGenericStatement(builder);

      first = false;
    }
    builder.append("}");
  }

  public EntityImpl toEntity(Identifiable source, CommandContext ctx) {
    var className = getClassNameForEntity(ctx);
    var session = ctx.getDatabaseSession();

    EntityImpl entity;
    if (className == null) {
      entity = (EntityImpl) session.newEmbeddedEntity();
    } else {
      var cls = session.getMetadata().getImmutableSchemaSnapshot().getClass(className);

      if (cls.isAbstract()) {
        entity = (EntityImpl) session.newEmbeddedEntity();
      } else if (cls.isVertexType()) {
        entity = (EntityImpl) session.newVertex(className);
      } else {
        entity = (EntityImpl) session.newEntity(className);
      }
    }

    for (var item : items) {
      var name = item.getLeftValue();
      if (name == null) {
        continue;
      }
      Object value;
      if (item.right.value instanceof SQLJson) {
        value = ((SQLJson) item.right.value).toEntity(source, ctx);
      } else {
        value = item.right.execute(source, ctx);
      }

      var schemaClass = entity.getImmutableSchemaClass(session);
      var schemaProperty = schemaClass != null ? schemaClass.getProperty(name) : null;
      entity.setProperty(name, SQLUpdateItem.cleanPropertyValue(value, session, schemaProperty));
    }

    return entity;
  }

  private EntityImpl toEntity(Result source, CommandContext ctx, String className) {
    var session = ctx.getDatabaseSession();
    EntityImpl entity;
    if (className == null) {
      entity = (EntityImpl) session.newEmbeddedEntity();
    } else {
      var cls = session.getMetadata().getImmutableSchemaSnapshot().getClass(className);

      if (cls.isAbstract()) {
        entity = (EntityImpl) session.newEmbeddedEntity(cls);
      } else if (cls.isVertexType()) {
        entity = (EntityImpl) session.newVertex(className);
      } else {
        entity = (EntityImpl) session.newEntity(className);
      }
    }

    var schemaClass = entity.getImmutableSchemaClass(session);

    Map<String, Character> types = null;
    for (var item : items) {
      var name = item.getLeftValue();
      if (name == null
          || EntityHelper.getReservedAttributes().contains(name.toLowerCase(Locale.ENGLISH))) {
        if (name.equals(FieldTypesString.ATTRIBUTE_FIELD_TYPES)) {
          var value = item.right.execute(source, ctx);
          types = FieldTypesString.loadFieldTypes(value.toString());
          for (var entry : types.entrySet()) {
            var t = FieldTypesString.getOTypeFromChar(entry.getValue());
            var propertyName = entry.getKey();
            if (entity.hasProperty(propertyName)
                && PropertyTypeInternal.convertFromPublicType(entity.getPropertyType(propertyName))
                != t) {
              if (t != null) {
                entity.setProperty(propertyName,
                    entity.getProperty(propertyName), t.getPublicPropertyType());
              } else {
                entity.setProperty(propertyName,
                    entity.getProperty(propertyName));
              }
            }

          }
        }
        continue;
      }

      var value = item.right.execute(source, ctx);
      value = SQLUpdateItem.cleanPropertyValue(value, session, schemaClass != null ?
          schemaClass.getProperty(name) : null);
      Character charType;
      if (types != null) {
        charType = types.get(name);
      } else {
        charType = null;
      }
      if (charType != null) {
        var t = FieldTypesString.getOTypeFromChar(charType);
        if (t != null) {
          entity.setProperty(name, value, t.getPublicPropertyType());
        } else {
          entity.setProperty(name, value);
        }
      } else {
        entity.setProperty(name, value);
      }
    }
    return entity;
  }

  /**
   * choosing return type is based on existence of @class and @type field in JSON
   */
  public Object toObjectDetermineType(Result source, CommandContext ctx) {
    var className = getClassNameForEntity(ctx);
    var type = getTypeForEntity(ctx);
    if (className != null || ("d".equalsIgnoreCase(type))) {
      return toEntity(source, ctx, className);
    } else {
      return toMap(source, ctx);
    }
  }

  public Object toObjectDetermineType(Identifiable source, CommandContext ctx) {
    var db = ctx.getDatabaseSession();
    var className = getClassNameForEntity(ctx);
    var type = getTypeForEntity(ctx);

    if (className != null || ("d".equalsIgnoreCase(type))) {
      UpdatableResult element = null;
      if (source != null) {
        var identity = source.getIdentity();
        if (identity.isPersistent()) {
          element = new UpdatableResult(db, db.load(source.getIdentity()));
        } else if (identity instanceof Entity el) {
          element = new UpdatableResult(db, el);
        }
      }
      return toEntity(element, ctx, className);
    } else {
      return toMap(source, ctx);
    }
  }

  public Map<String, Object> toMap(Identifiable source, CommandContext ctx) {
    Map<String, Object> map = new HashMap<String, Object>();
    for (var item : items) {
      var name = item.getLeftValue();
      if (name == null) {
        continue;
      }
      var value = item.right.execute(source, ctx);
      map.put(name, value);
    }

    return map;
  }

  public Map<String, Object> toMap(Result source, CommandContext ctx) {
    Map<String, Object> map = new HashMap<String, Object>();
    for (var item : items) {
      var name = item.getLeftValue();
      if (name == null) {
        continue;
      }
      var value = item.right.execute(source, ctx);
      map.put(name, value);
    }

    return map;
  }

  @Nullable
  private String getClassNameForEntity(CommandContext ctx) {
    for (var item : items) {
      var left = item.getLeftValue();
      if (left != null && left.toLowerCase(Locale.ENGLISH).equals("@class")) {
        return "" + item.right.execute((Result) null, ctx);
      }
    }

    return null;
  }

  @Nullable
  private String getTypeForEntity(CommandContext ctx) {
    for (var item : items) {
      var left = item.getLeftValue();
      if (left != null && left.toLowerCase(Locale.ENGLISH).equals("@type")) {
        return "" + item.right.execute((Result) null, ctx);
      }
    }

    return null;
  }

  public boolean needsAliases(Set<String> aliases) {
    for (var item : items) {
      if (item.needsAliases(aliases)) {
        return true;
      }
    }
    return false;
  }

  public boolean isAggregate(DatabaseSessionEmbedded session) {
    for (var item : items) {
      if (item.isAggregate(session)) {
        return true;
      }
    }
    return false;
  }

  public SQLJson splitForAggregation(AggregateProjectionSplit aggregateSplit, CommandContext ctx) {
    if (isAggregate(ctx.getDatabaseSession())) {
      var result = new SQLJson(-1);
      for (var item : items) {
        result.items.add(item.splitForAggregation(aggregateSplit, ctx));
      }
      return result;
    } else {
      return this;
    }
  }

  @Override
  public SQLJson copy() {
    var result = new SQLJson(-1);
    result.items = items.stream().map(SQLJsonItem::copy).collect(Collectors.toList());
    return result;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }

    var oJson = (SQLJson) o;

    return Objects.equals(items, oJson.items);
  }

  @Override
  public int hashCode() {
    return items != null ? items.hashCode() : 0;
  }

  public void extractSubQueries(SubQueryCollector collector) {
    for (var item : items) {
      item.extractSubQueries(collector);
    }
  }

  public boolean refersToParent() {
    for (var item : items) {
      if (item.refersToParent()) {
        return true;
      }
    }
    return false;
  }

  public Result serialize(DatabaseSessionEmbedded session) {
    var result = new ResultInternal(session);
    if (items != null) {
      result.setProperty(
          "items",
          items.stream().map(oJsonItem -> oJsonItem.serialize(session))
              .collect(Collectors.toList()));
    }
    return result;
  }

  public void deserialize(Result fromResult) {

    if (fromResult.getProperty("items") != null) {
      List<Result> ser = fromResult.getProperty("items");
      items = new ArrayList<>();
      for (var r : ser) {
        var exp = new SQLJsonItem();
        exp.deserialize(r);
        items.add(exp);
      }
    }
  }

  public void addItem(SQLJsonItem item) {
    this.items.add(item);
  }

}
/* JavaCC - OriginalChecksum=3beec9f6db486de944498588b51a505d (do not edit this line) */
