/* Generated By:JJTree: Do not edit this line. SQLLikeOperator.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=O,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.jetbrains.youtrackdb.internal.core.sql.parser;

import com.jetbrains.youtrackdb.internal.common.collection.MultiValue;
import com.jetbrains.youtrackdb.internal.core.db.DatabaseSessionEmbedded;
import com.jetbrains.youtrackdb.internal.core.query.QueryHelper;
import com.jetbrains.youtrackdb.internal.core.sql.executor.metadata.IndexFinder.Operation;
import com.jetbrains.youtrackdb.internal.core.sql.operator.QueryOperatorEquals;
import java.util.Map;
import javax.annotation.Nonnull;
import javax.annotation.Nullable;

public class SQLLikeOperator extends SimpleNode implements SQLBinaryCompareOperator {

  public SQLLikeOperator(int id) {
    super(id);
  }

  public SQLLikeOperator(YouTrackDBSql p, int id) {
    super(p, id);
  }

  @Override
  public boolean execute(@Nonnull DatabaseSessionEmbedded session, Object iLeft, Object iRight) {
    if (MultiValue.isMultiValue(iRight)) {
      return false;
    }
    if (iLeft == null || iRight == null) {
      return false;
    }

    if (MultiValue.isMultiValue(iLeft)) {
      return MultiValue.contains(iLeft,
          item -> QueryHelper.like(item.toString(), iRight.toString()));
    }

    return QueryHelper.like(iLeft.toString(), iRight.toString());
  }

  @Override
  public String toString() {
    return "LIKE";
  }

  @Override
  public void toGenericStatement(StringBuilder builder) {
    builder.append("LIKE");
  }

  @Override
  public void toString(Map<Object, Object> params, StringBuilder builder) {
    builder.append("LIKE");
  }

  @Override
  public boolean supportsBasicCalculation() {
    return true;
  }

  @Nullable
  @Override
  public MergeResult mergeWithOperator(@Nonnull DatabaseSessionEmbedded session,
      @Nonnull SQLBinaryCompareOperator otherOperator, Object currentRight,
      Object otherRight) {
    if (QueryOperatorEquals.equals(session, currentRight, otherRight)) {
      return new MergeResult(this, currentRight);
    }

    return null;
  }

  @Override
  public SQLLikeOperator copy() {
    return this;
  }

  @Override
  public Operation getOperation() {
    return Operation.FuzzyEq;
  }

  @Override
  public boolean equals(Object obj) {
    return obj != null && obj.getClass().equals(this.getClass());
  }

  @Override
  public int hashCode() {
    return getClass().hashCode();
  }
}
/* JavaCC - OriginalChecksum=16d302abf0f85b404e57b964606952ca (do not edit this line) */
