/* Generated By:JJTree: Do not edit this line. SQLModifier.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=O,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.jetbrains.youtrackdb.internal.core.sql.parser;

import com.jetbrains.youtrackdb.internal.common.collection.MultiValue;
import com.jetbrains.youtrackdb.internal.core.command.CommandContext;
import com.jetbrains.youtrackdb.internal.core.db.DatabaseSessionEmbedded;
import com.jetbrains.youtrackdb.internal.core.db.record.record.Identifiable;
import com.jetbrains.youtrackdb.internal.core.exception.CommandExecutionException;
import com.jetbrains.youtrackdb.internal.core.metadata.schema.PropertyTypeInternal;
import com.jetbrains.youtrackdb.internal.core.metadata.schema.SchemaClassInternal;
import com.jetbrains.youtrackdb.internal.core.metadata.schema.schema.SchemaProperty;
import com.jetbrains.youtrackdb.internal.core.query.Result;
import com.jetbrains.youtrackdb.internal.core.sql.executor.ResultInternal;
import com.jetbrains.youtrackdb.internal.core.sql.executor.metadata.IndexMetadataPath;
import java.lang.reflect.Array;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Iterator;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Set;
import javax.annotation.Nullable;

public class SQLModifier extends SimpleNode {

  protected boolean squareBrackets = false;
  protected SQLArrayRangeSelector arrayRange;
  protected SQLOrBlock condition;
  protected SQLArraySingleValuesSelector arraySingleValues;
  protected SQLRightBinaryCondition rightBinaryCondition;
  protected SQLMethodCall methodCall;
  protected SQLSuffixIdentifier suffix;

  protected SQLModifier next;

  public SQLModifier(int id) {
    super(id);
  }

  public SQLModifier(YouTrackDBSql p, int id) {
    super(p, id);
  }

  public boolean isArraySingleValue() {
    if (this.arraySingleValues != null) {
      return this.arraySingleValues.items.size() == 1;
    } else {
      return false;
    }
  }

  @Override
  public void toString(Map<Object, Object> params, StringBuilder builder) {

    if (squareBrackets) {
      builder.append("[");

      if (arrayRange != null) {
        arrayRange.toString(params, builder);
      } else if (condition != null) {
        condition.toString(params, builder);
      } else if (arraySingleValues != null) {
        arraySingleValues.toString(params, builder);
      } else if (rightBinaryCondition != null) {
        rightBinaryCondition.toString(params, builder);
      }

      builder.append("]");
    } else if (methodCall != null) {
      methodCall.toString(params, builder);
    } else if (suffix != null) {
      builder.append(".");
      suffix.toString(params, builder);
    }
    if (next != null) {
      next.toString(params, builder);
    }
  }

  @Override
  public void toGenericStatement(StringBuilder builder) {

    if (squareBrackets) {
      builder.append("[");

      if (arrayRange != null) {
        arrayRange.toGenericStatement(builder);
      } else if (condition != null) {
        condition.toGenericStatement(builder);
      } else if (arraySingleValues != null) {
        arraySingleValues.toGenericStatement(builder);
      } else if (rightBinaryCondition != null) {
        rightBinaryCondition.toGenericStatement(builder);
      }

      builder.append("]");
    } else if (methodCall != null) {
      methodCall.toGenericStatement(builder);
    } else if (suffix != null) {
      builder.append(".");
      suffix.toGenericStatement(builder);
    }
    if (next != null) {
      next.toGenericStatement(builder);
    }
  }

  public Object execute(Identifiable iCurrentRecord, Object result, CommandContext ctx) {
    if (ctx.getSystemVariable(CommandContext.VAR_CURRENT) == null) {
      ctx.setSystemVariable(CommandContext.VAR_CURRENT, iCurrentRecord);
    }
    if (methodCall != null) {
      result = methodCall.execute(result, ctx);
    } else if (suffix != null) {
      result = suffix.execute(result, ctx);
    } else if (arrayRange != null) {
      result = arrayRange.execute(iCurrentRecord, result, ctx);
    } else if (condition != null) {
      result = filterByCondition(result, ctx);
    } else if (arraySingleValues != null) {
      result = arraySingleValues.execute(iCurrentRecord, result, ctx);
    } else if (rightBinaryCondition != null) {
      result = rightBinaryCondition.execute(iCurrentRecord, result, ctx);
    }
    if (next != null) {
      result = next.execute(iCurrentRecord, result, ctx);
    }
    return result;
  }

  public Object execute(Result iCurrentRecord, Object result, CommandContext ctx) {
    result = executeOneLevel(iCurrentRecord, result, ctx);
    if (next != null) {
      result = next.execute(iCurrentRecord, result, ctx);
    }
    return result;
  }

  /**
   * Execute this modifier without stepping down to `next`.
   */
  Object executeOneLevel(Result iCurrentRecord, Object result, CommandContext ctx) {
    if (ctx.getSystemVariable(CommandContext.VAR_CURRENT) == null) {
      ctx.setSystemVariable(CommandContext.VAR_CURRENT, iCurrentRecord);
    }
    if (methodCall != null) {
      result = methodCall.execute(result, ctx);
    } else if (suffix != null) {
      result = suffix.execute(result, ctx);
    } else if (arrayRange != null) {
      result = arrayRange.execute(iCurrentRecord, result, ctx);
    } else if (condition != null) {
      result = filterByCondition(result, ctx);
    } else if (arraySingleValues != null) {
      result = arraySingleValues.execute(iCurrentRecord, result, ctx);
    } else if (rightBinaryCondition != null) {
      result = rightBinaryCondition.execute(iCurrentRecord, result, ctx);
    }
    return result;
  }

  @Nullable
  private Object filterByCondition(Object iResult, CommandContext ctx) {
    if (iResult == null) {
      return null;
    }
    List<Object> result = new ArrayList<Object>();
    if (iResult.getClass().isArray()) {
      for (var i = 0; i < Array.getLength(iResult); i++) {
        var item = Array.get(iResult, i);
        if (condition.evaluate(item, ctx)) {
          result.add(item);
        }
      }
      return result;
    }
    if (iResult instanceof Identifiable) {
      iResult = Collections.singleton(iResult);
    }
    if (iResult instanceof Iterable) {
      iResult = ((Iterable) iResult).iterator();
    }
    if (iResult instanceof Iterator) {
      while (((Iterator) iResult).hasNext()) {
        var item = ((Iterator) iResult).next();
        if (condition.evaluate(item, ctx)) {
          result.add(item);
        }
      }
    }
    return result;
  }

  public boolean needsAliases(Set<String> aliases) {
    if (condition != null && condition.needsAliases(aliases)) {
      return true;
    }

    if (arraySingleValues != null && arraySingleValues.needsAliases(aliases)) {
      return true;
    }

    if (arrayRange != null && arrayRange.needsAliases(aliases)) {
      return true;
    }

    if (rightBinaryCondition != null && rightBinaryCondition.needsAliases(aliases)) {
      return true;
    }

    if (methodCall != null && methodCall.needsAliases(aliases)) {
      return true;
    }

    return next != null && next.needsAliases(aliases);
  }

  @Override
  public SQLModifier copy() {
    var result = new SQLModifier(-1);
    result.squareBrackets = squareBrackets;
    result.arrayRange = arrayRange == null ? null : arrayRange.copy();
    result.condition = condition == null ? null : condition.copy();
    result.arraySingleValues = arraySingleValues == null ? null : arraySingleValues.copy();
    result.rightBinaryCondition = rightBinaryCondition == null ? null : rightBinaryCondition.copy();
    result.methodCall = methodCall == null ? null : methodCall.copy();
    result.suffix = suffix == null ? null : suffix.copy();
    result.next = next == null ? null : next.copy();

    return result;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }

    var oModifier = (SQLModifier) o;

    if (squareBrackets != oModifier.squareBrackets) {
      return false;
    }
    if (!Objects.equals(arrayRange, oModifier.arrayRange)) {
      return false;
    }
    if (!Objects.equals(condition, oModifier.condition)) {
      return false;
    }
    if (!Objects.equals(arraySingleValues, oModifier.arraySingleValues)) {
      return false;
    }
    if (!Objects.equals(rightBinaryCondition, oModifier.rightBinaryCondition)) {
      return false;
    }
    if (!Objects.equals(methodCall, oModifier.methodCall)) {
      return false;
    }
    if (!Objects.equals(suffix, oModifier.suffix)) {
      return false;
    }
    return Objects.equals(next, oModifier.next);
  }

  @Override
  public int hashCode() {
    var result = (squareBrackets ? 1 : 0);
    result = 31 * result + (arrayRange != null ? arrayRange.hashCode() : 0);
    result = 31 * result + (condition != null ? condition.hashCode() : 0);
    result = 31 * result + (arraySingleValues != null ? arraySingleValues.hashCode() : 0);
    result = 31 * result + (rightBinaryCondition != null ? rightBinaryCondition.hashCode() : 0);
    result = 31 * result + (methodCall != null ? methodCall.hashCode() : 0);
    result = 31 * result + (suffix != null ? suffix.hashCode() : 0);
    result = 31 * result + (next != null ? next.hashCode() : 0);
    return result;
  }

  public void extractSubQueries(SubQueryCollector collector) {
    if (arrayRange != null) {
      arrayRange.extractSubQueries(collector);
    }
    if (condition != null) {
      condition.extractSubQueries(collector);
    }
    if (arraySingleValues != null) {
      arraySingleValues.extractSubQueries(collector);
    }
    if (rightBinaryCondition != null) {
      rightBinaryCondition.extractSubQueries(collector);
    }
    if (methodCall != null) {
      methodCall.extractSubQueries(collector);
    }
    if (suffix != null) {
      suffix.extractSubQueries(collector);
    }
    if (next != null) {
      next.extractSubQueries(collector);
    }
  }

  public boolean refersToParent() {
    if (arrayRange != null && arrayRange.refersToParent()) {
      return true;
    }
    if (condition != null && condition.refersToParent()) {
      return true;
    }

    if (arraySingleValues != null && arraySingleValues.refersToParent()) {
      return true;
    }
    if (rightBinaryCondition != null && rightBinaryCondition.refersToParent()) {
      return true;
    }
    if (methodCall != null && methodCall.refersToParent()) {
      return true;
    }
    return suffix != null && suffix.refersToParent();
  }

  protected void setValue(Result currentRecord, Object target, Object value,
      CommandContext ctx, @Nullable SchemaProperty schemaProperty, int level) {
    if (next == null) {
      doSetValue(currentRecord, target, value, ctx, schemaProperty, level);
    } else {
      var newTarget = calculateLocal(currentRecord, target, ctx);
      if (newTarget != null) {
        next.setValue(currentRecord, newTarget, value, ctx, schemaProperty, level + 1);
      }
    }
  }

  private void doSetValue(Result currentRecord, Object target, Object value,
      CommandContext ctx, @Nullable SchemaProperty schemaProperty, int level) {
    value = SQLUpdateItem.convertResultToDocument(value);

    var session = ctx.getDatabaseSession();
    if (methodCall != null) {
      // do nothing
    } else if (suffix != null) {

      value = convertLinkedType(value, level == 0 ? schemaProperty : null, session);
      suffix.setValue(target, value, ctx);
    } else if (arrayRange != null) {
      value = SQLUpdateItem.cleanPropertyValue(value, session, schemaProperty);
      arrayRange.setValue(target, value, ctx);
    } else if (condition != null) {
      // TODO
      throw new UnsupportedOperationException(
          "SET value on conditional filtering will be supported soon");
    } else if (arraySingleValues != null) {

      value = convertLinkedType(value, level == 0 ? schemaProperty : null, session);
      arraySingleValues.setValue(currentRecord, target, value, ctx);
    } else if (rightBinaryCondition != null) {
      throw new UnsupportedOperationException(
          "SET value on conditional filtering will be supported soon");
    }
  }

  @Nullable
  private static Object convertLinkedType(
      Object value,
      @Nullable SchemaProperty schemaProperty,
      DatabaseSessionEmbedded session
  ) {
    if (value == null) {
      return null;
    }
    PropertyTypeInternal targetType = null;

    if (schemaProperty != null && PropertyTypeInternal.isSimpleValueType(value)) {
      targetType = PropertyTypeInternal.convertFromPublicType(schemaProperty.getLinkedType());
    }

    if (targetType == null) {
      targetType = PropertyTypeInternal.getTypeByValue(value);
    }

    if (targetType != null) {
      value = targetType.convert(value, session);
    }

    return value;
  }

  @Nullable
  private Object calculateLocal(Result currentRecord, Object target, CommandContext ctx) {
    if (methodCall != null) {
      return methodCall.execute(target, ctx);
    } else if (suffix != null) {
      return suffix.execute(target, ctx);
    } else if (arrayRange != null) {
      return arrayRange.execute(currentRecord, target, ctx);
    } else if (condition != null) {
      if (target instanceof Result || target instanceof Identifiable || target instanceof Map) {
        if (condition.evaluate(target, ctx)) {
          return target;
        } else {
          return null;
        }
      } else if (MultiValue.isMultiValue(target)) {
        List<Object> result = new ArrayList<>();
        for (var o : MultiValue.getMultiValueIterable(target)) {
          if (condition.evaluate(o, ctx)) {
            result.add(o);
          }
        }
        return result;
      } else {
        return null;
      }
    } else if (arraySingleValues != null) {
      return arraySingleValues.execute(currentRecord, target, ctx);
    } else if (rightBinaryCondition != null) {
      return rightBinaryCondition.execute(currentRecord, target, ctx);
    }
    return null;
  }

  public void applyRemove(
      Object currentValue, ResultInternal originalRecord, CommandContext ctx) {
    if (next != null) {
      var val = calculateLocal(originalRecord, currentValue, ctx);
      next.applyRemove(val, originalRecord, ctx);
    } else {
      if (arrayRange != null) {
        arrayRange.applyRemove(currentValue, originalRecord, ctx);
      } else if (condition != null) {
        // TODO
        throw new UnsupportedOperationException(
            "Remove on conditional filtering will be supported soon");
      } else if (arraySingleValues != null) {
        arraySingleValues.applyRemove(currentValue, originalRecord, ctx);
      } else if (rightBinaryCondition != null) {
        throw new UnsupportedOperationException(
            "Remove on conditional filtering will be supported soon");
      } else if (suffix != null) {
        suffix.applyRemove(currentValue, ctx);
      } else {
        throw new CommandExecutionException(ctx.getDatabaseSession(),
            "cannot apply REMOVE " + this);
      }
    }
  }

  public Result serialize(DatabaseSessionEmbedded session) {
    var result = new ResultInternal(session);
    result.setProperty("squareBrackets", squareBrackets);
    if (arrayRange != null) {
      result.setProperty("arrayRange", arrayRange.serialize(session));
    }
    if (condition != null) {
      result.setProperty("condition", condition.serialize(session));
    }
    if (arraySingleValues != null) {
      result.setProperty("arraySingleValues", arraySingleValues.serialize(session));
    }
    if (rightBinaryCondition != null) {
      result.setProperty("rightBinaryCondition", rightBinaryCondition.serialize(session));
    }
    if (methodCall != null) {
      result.setProperty("methodCall", methodCall.serialize(session));
    }
    if (suffix != null) {
      result.setProperty("suffix", suffix.serialize(session));
    }
    if (next != null) {
      result.setProperty("next", next.serialize(session));
    }
    return result;
  }

  public void deserialize(Result fromResult) {
    squareBrackets = fromResult.getProperty("squareBrackets");

    if (fromResult.getProperty("arrayRange") != null) {
      arrayRange = new SQLArrayRangeSelector(-1);
      arrayRange.deserialize(fromResult.getProperty("arrayRange"));
    }
    if (fromResult.getProperty("condition") != null) {
      condition = new SQLOrBlock(-1);
      condition.deserialize(fromResult.getProperty("condition"));
    }
    if (fromResult.getProperty("arraySingleValues") != null) {
      arraySingleValues = new SQLArraySingleValuesSelector(-1);
      arraySingleValues.deserialize(fromResult.getProperty("arraySingleValues"));
    }
    if (fromResult.getProperty("rightBinaryCondition") != null) {
      rightBinaryCondition = new SQLRightBinaryCondition(-1);
      rightBinaryCondition.deserialize(fromResult.getProperty("arraySingleValues"));
    }
    if (fromResult.getProperty("methodCall") != null) {
      methodCall = new SQLMethodCall(-1);
      methodCall.deserialize(fromResult.getProperty("methodCall"));
    }
    if (fromResult.getProperty("suffix") != null) {
      suffix = new SQLSuffixIdentifier(-1);
      suffix.deserialize(fromResult.getProperty("suffix"));
    }

    if (fromResult.getProperty("next") != null) {
      next = new SQLModifier(-1);
      next.deserialize(fromResult.getProperty("next"));
    }
  }

  public boolean isCacheable(DatabaseSessionEmbedded session) {
    if (arrayRange != null || arraySingleValues != null || rightBinaryCondition != null) {
      return false; // TODO enhance a bit
    }
    if (condition != null && !condition.isCacheable(session)) {
      return false;
    }
    if (methodCall != null && !methodCall.isCacheable(session)) {
      return false;
    }
    if (suffix != null && !suffix.isCacheable()) {
      return false;
    }
    return next == null || next.isCacheable(session);
  }

  public boolean isIndexChain(CommandContext ctx, SchemaClassInternal clazz) {
    if (suffix != null && suffix.isBaseIdentifier()) {
      var prop = clazz.getPropertyInternal(
          suffix.getIdentifier().getStringValue());
      if (prop != null
          && prop.getAllIndexesInternal().stream()
          .anyMatch(idx -> idx.getDefinition().getProperties().size() == 1)) {
        if (next != null) {
          var linkedClazz = (SchemaClassInternal) prop.getLinkedClass();
          return next.isIndexChain(ctx, linkedClazz);
        }
        return true;
      }
    }
    return false;
  }

  /** Returns the suffix identifier segment of this modifier (e.g. the
   * {@code .X} part of {@code $matched.X.out('E')}), or {@code null}. */
  @Nullable
  public SQLSuffixIdentifier getSuffix() {
    return suffix;
  }

  /** Returns the method call segment of this modifier (e.g. the
   * {@code .out('E')} part), or {@code null}. */
  @Nullable
  public SQLMethodCall getMethodCall() {
    return methodCall;
  }

  /** Returns the next modifier in the chain, or {@code null} when this is
   * the last segment. */
  @Nullable
  public SQLModifier getNext() {
    return next;
  }

  @Nullable
  public IndexMetadataPath getIndexMetadataPath() {
    if (this.suffix != null && this.suffix.isBaseIdentifier()) {
      if (this.next != null) {
        var path = this.next.getIndexMetadataPath();
        if (path != null) {
          path.addPre(suffix.identifier.getValue());
        }

        return path;
      } else {
        return new IndexMetadataPath(suffix.identifier.getValue());
      }
    }

    return null;
  }

  public boolean varMightBeInUse(String varName) {
    return arrayRange != null && arrayRange.varMightBeInUse(varName) ||
        condition != null && condition.varMightBeInUse(varName) ||
        arraySingleValues != null && arraySingleValues.varMightBeInUse(varName) ||
        rightBinaryCondition != null && rightBinaryCondition.varMightBeInUse(varName) ||
        methodCall != null && methodCall.varMightBeInUse(varName) ||
        suffix != null && suffix.identifier != null && suffix.identifier.isVariable(varName) ||
        next != null && next.varMightBeInUse(varName);
  }
}
/* JavaCC - OriginalChecksum=39c21495d02f9b5007b4a2d6915496e1 (do not edit this line) */
