/* Generated By:JJTree: Do not edit this line. SQLMatchFilter.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=O,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.jetbrains.youtrackdb.internal.core.sql.parser;

import com.jetbrains.youtrackdb.internal.core.command.CommandContext;
import com.jetbrains.youtrackdb.internal.core.db.DatabaseSessionEmbedded;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.stream.Collectors;
import javax.annotation.Nullable;

public class SQLMatchFilter extends SimpleNode {

  // TODO transform in a map
  protected List<SQLMatchFilterItem> items = new ArrayList<>();

  public SQLMatchFilter(int id) {
    super(id);
  }

  public SQLMatchFilter(YouTrackDBSql p, int id) {
    super(p, id);
  }

  @Nullable
  public String getAlias() {
    for (var item : items) {
      if (item.alias != null) {
        return item.alias.getStringValue();
      }
    }
    return null;
  }

  public void setAlias(String alias) {
    var found = false;
    for (var item : items) {
      if (item.alias != null) {
        item.alias = new SQLIdentifier(alias);
        found = true;
        break;
      }
    }
    if (!found) {
      var newItem = new SQLMatchFilterItem(-1);
      newItem.alias = new SQLIdentifier(alias);
      items.add(newItem);
    }
  }

  /// Factory method for GQL parser: creates SQLMatchFilter from simple alias and class name.
  /// Constructs proper YQL IR structure without exposing internal parser-generated type complexity.
  public static SQLMatchFilter fromGqlNode(String alias, String className) {
    var filter = new SQLMatchFilter(-1);
    if (alias != null && !alias.isBlank()) {
      filter.setAlias(alias);
    }
    if (className != null && !className.isBlank()) {
      // className is SQLExpression - use SQLExpression(SQLIdentifier) constructor
      var item = new SQLMatchFilterItem(-1);
      var sqlIdentifier = new SQLIdentifier(className);
      item.className = new SQLExpression(sqlIdentifier);
      filter.items.add(item);
    }
    return filter;
  }


  @Nullable
  public SQLWhereClause getFilter() {
    for (var item : items) {
      if (item.filter != null) {
        return item.filter;
      }
    }
    return null;
  }

  public void setFilter(SQLWhereClause filter) {
    var found = false;
    for (var item : items) {
      if (item.filter != null) {
        item.filter = filter;
        found = true;
        break;
      }
    }
    if (!found) {
      var newItem = new SQLMatchFilterItem(-1);
      newItem.filter = filter;
      items.add(newItem);
    }
  }

  @Nullable
  public SQLWhereClause getWhileCondition() {
    for (var item : items) {
      if (item.whileCondition != null) {
        return item.whileCondition;
      }
    }
    return null;
  }

  @Nullable
  public String getClassName(CommandContext context) {
    for (var item : items) {
      if (item.className != null) {
        if (item.className.value instanceof String) {
          return (String) item.className.value;
        } else if (item.className.value instanceof SimpleNode) {
          var builder = new StringBuilder();

          ((SimpleNode) item.className.value)
              .toString(context == null ? null : context.getInputParameters(), builder);
          return builder.toString();
        } else if (item.className.isBaseIdentifier()) {
          return item.className.getDefaultAlias().getStringValue();
        } else {
          return item.className.toString();
        }
      }
    }
    return null;
  }

  @Nullable
  public String getCollectionName(CommandContext context) {
    for (var item : items) {
      if (item.collectionName != null) {
        return item.collectionName.getStringValue();
      } else if (item.collectionId != null) {
        var cid = item.collectionId.value.intValue();
        var collectionName = context.getDatabaseSession().getCollectionNameById(cid);
        if (collectionName != null) {
          return collectionName;
        }
      }
    }
    return null;
  }

  @Nullable
  public SQLRid getRid(CommandContext context) {
    for (var item : items) {
      if (item.rid != null) {
        return item.rid;
      }
    }
    return null;
  }

  @Nullable
  public Integer getMaxDepth() {
    for (var item : items) {
      if (item.maxDepth != null) {
        return item.maxDepth.value.intValue();
      }
    }
    return null;
  }

  public boolean isOptional() {
    for (var item : items) {
      if (Boolean.TRUE.equals(item.optional)) {
        return true;
      }
    }
    return false;
  }

  @Nullable
  public String getDepthAlias() {
    for (var item : items) {
      if (item.depthAlias != null) {
        return item.depthAlias.getStringValue();
      }
    }
    return null;
  }

  @Nullable
  public String getPathAlias() {
    for (var item : items) {
      if (item.pathAlias != null) {
        return item.pathAlias.getStringValue();
      }
    }
    return null;
  }

  @Override
  public void toString(Map<Object, Object> params, StringBuilder builder) {
    builder.append("{");
    var first = true;
    for (var item : items) {
      if (!first) {
        builder.append(", ");
      }
      item.toString(params, builder);
      first = false;
    }
    builder.append("}");
  }

  @Override
  public void toGenericStatement(StringBuilder builder) {
    builder.append("{");
    var first = true;
    for (var item : items) {
      if (!first) {
        builder.append(", ");
      }
      item.toGenericStatement(builder);
      first = false;
    }
    builder.append("}");
  }

  public boolean isCacheable(DatabaseSessionEmbedded session) {
    for (var item : items) {
      if (!item.isCacheable(session)) {
        return false;
      }
    }
    return true;
  }

  @Override
  public SQLMatchFilter copy() {
    var result = new SQLMatchFilter(-1);
    result.items =
        items == null ? null : items.stream().map(x -> x.copy()).collect(Collectors.toList());
    return result;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }

    var that = (SQLMatchFilter) o;

    return Objects.equals(items, that.items);
  }

  @Override
  public int hashCode() {
    return items != null ? items.hashCode() : 0;
  }

  public void addItem(SQLMatchFilterItem item) {
    this.items.add(item);
  }
}
/* JavaCC - OriginalChecksum=6b099371c69e0d0c1c106fc96b3072de (do not edit this line) */
