/* Generated By:JJTree: Do not edit this line. SQLOrBlock.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=O,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.jetbrains.youtrackdb.internal.core.sql.parser;

import com.jetbrains.youtrackdb.internal.core.command.CommandContext;
import com.jetbrains.youtrackdb.internal.core.db.DatabaseSessionEmbedded;
import com.jetbrains.youtrackdb.internal.core.db.record.record.Identifiable;
import com.jetbrains.youtrackdb.internal.core.metadata.schema.SchemaClassInternal;
import com.jetbrains.youtrackdb.internal.core.metadata.schema.schema.SchemaClass;
import com.jetbrains.youtrackdb.internal.core.query.Result;
import com.jetbrains.youtrackdb.internal.core.sql.executor.IndexSearchInfo;
import com.jetbrains.youtrackdb.internal.core.sql.executor.ResultInternal;
import com.jetbrains.youtrackdb.internal.core.sql.executor.metadata.IndexCandidate;
import com.jetbrains.youtrackdb.internal.core.sql.executor.metadata.IndexFinder;
import com.jetbrains.youtrackdb.internal.core.sql.executor.metadata.RequiredIndexCanditate;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Set;
import java.util.stream.Collectors;
import javax.annotation.Nonnull;
import javax.annotation.Nullable;

public class SQLOrBlock extends SQLBooleanExpression {

  List<SQLBooleanExpression> subBlocks = new ArrayList<>();

  public SQLOrBlock(int id) {
    super(id);
  }

  public SQLOrBlock(YouTrackDBSql p, int id) {
    super(p, id);
  }

  @Override
  public boolean evaluate(Identifiable currentRecord, CommandContext ctx) {
    if (subBlocks == null) {
      return true;
    }

    for (var block : subBlocks) {
      if (block.evaluate(currentRecord, ctx)) {
        return true;
      }
    }
    return false;
  }

  @Override
  public boolean evaluate(Result currentRecord, CommandContext ctx) {
    if (subBlocks == null) {
      return true;
    }

    for (var block : subBlocks) {
      if (block.evaluate(currentRecord, ctx)) {
        return true;
      }
    }
    return false;
  }

  public boolean evaluate(Object currentRecord, CommandContext ctx) {
    if (currentRecord instanceof Result) {
      return evaluate((Result) currentRecord, ctx);
    } else if (currentRecord instanceof Identifiable) {
      return evaluate((Identifiable) currentRecord, ctx);
    } else if (currentRecord instanceof Map<?, ?> map) {
      var result = new ResultInternal(ctx.getDatabaseSession());

      for (var entry : map.entrySet()) {
        result.setProperty(entry.getKey().toString(), entry.getValue());
      }

      return evaluate(result, ctx);
    }
    return false;
  }

  public List<SQLBooleanExpression> getSubBlocks() {
    return subBlocks;
  }

  public void addSubBlock(SQLBooleanExpression block) {
    this.subBlocks.add(block);
  }

  @Override
  public void toString(Map<Object, Object> params, StringBuilder builder) {
    if (subBlocks == null || subBlocks.isEmpty()) {
      return;
    }

    var first = true;
    for (var expr : subBlocks) {
      if (!first) {
        builder.append(" OR ");
      }
      expr.toString(params, builder);
      first = false;
    }
  }

  @Override
  public void toGenericStatement(StringBuilder builder) {
    if (subBlocks == null || subBlocks.isEmpty()) {
      return;
    }

    var first = true;
    for (var expr : subBlocks) {
      if (!first) {
        builder.append(" OR ");
      }
      expr.toGenericStatement(builder);
      first = false;
    }
  }

  @Override
  protected boolean supportsBasicCalculation() {
    for (var expr : subBlocks) {
      if (!expr.supportsBasicCalculation()) {
        return false;
      }
    }
    return true;
  }

  @Override
  protected int getNumberOfExternalCalculations() {
    var result = 0;
    for (var expr : subBlocks) {
      result += expr.getNumberOfExternalCalculations();
    }
    return result;
  }

  @Override
  protected List<Object> getExternalCalculationConditions() {
    List<Object> result = new ArrayList<>();
    for (var expr : subBlocks) {
      result.addAll(expr.getExternalCalculationConditions());
    }
    return result;
  }

  @Override
  @Nullable
  public List<SQLBinaryCondition> getIndexedFunctionConditions(
      SchemaClass iSchemaClass, DatabaseSessionEmbedded session) {
    if (subBlocks == null || subBlocks.size() > 1) {
      return null;
    }
    List<SQLBinaryCondition> result = new ArrayList<>();
    for (var exp : subBlocks) {
      var sub = exp.getIndexedFunctionConditions(iSchemaClass, session);
      if (sub != null && !sub.isEmpty()) {
        result.addAll(sub);
      }
    }
    return result.isEmpty() ? null : result;
  }

  @Override
  public List<SQLAndBlock> flatten(CommandContext ctx, SchemaClassInternal schemaClass) {
    List<SQLAndBlock> result = new ArrayList<>();

    for (var sub : subBlocks) {
      var childFlattened = sub.flatten(ctx, schemaClass);
      result.addAll(childFlattened);
    }

    return result;
  }

  @Override
  public boolean needsAliases(Set<String> aliases) {
    for (var expr : subBlocks) {
      if (expr.needsAliases(aliases)) {
        return true;
      }
    }
    return false;
  }

  @Override
  public SQLOrBlock copy() {
    var result = new SQLOrBlock(-1);
    result.subBlocks = subBlocks.stream().map(SQLBooleanExpression::copy)
        .collect(Collectors.toList());
    return result;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }

    var oOrBlock = (SQLOrBlock) o;

    return Objects.equals(subBlocks, oOrBlock.subBlocks);
  }

  @Override
  public int hashCode() {
    return subBlocks != null ? subBlocks.hashCode() : 0;
  }

  @Override
  public boolean isEmpty() {
    if (subBlocks.isEmpty()) {
      return true;
    }
    for (var block : subBlocks) {
      if (!block.isEmpty()) {
        return false;
      }
    }
    return true;
  }

  @Override
  public void extractSubQueries(SubQueryCollector collector) {
    for (var block : subBlocks) {
      block.extractSubQueries(collector);
    }
  }

  @Override
  public boolean refersToParent() {
    for (var exp : subBlocks) {
      if (exp != null && exp.refersToParent()) {
        return true;
      }
    }
    return false;
  }

  @Nullable
  @Override
  public List<String> getMatchPatternInvolvedAliases() {
    List<String> result = new ArrayList<>();
    for (var exp : subBlocks) {
      var x = exp.getMatchPatternInvolvedAliases();
      if (x != null) {
        result.addAll(x);
      }
    }
    return result.isEmpty() ? null : result;
  }

  @Override
  public void translateLuceneOperator() {
    subBlocks.forEach(SQLBooleanExpression::translateLuceneOperator);
  }

  @Override
  public boolean isCacheable(DatabaseSessionEmbedded session) {
    for (var block : this.subBlocks) {
      if (!block.isCacheable(session)) {
        return false;
      }
    }
    return true;
  }

  @Override
  public SQLBooleanExpression rewriteIndexChainsAsSubqueries(CommandContext ctx,
      SchemaClassInternal clazz) {
    for (var exp : subBlocks) {
      exp.rewriteIndexChainsAsSubqueries(ctx, clazz);
    }
    return this;
  }

  @Override
  public IndexCandidate findIndex(IndexFinder info, CommandContext ctx) {
    IndexCandidate result = null;
    var first = true;
    for (var exp : subBlocks) {
      var singleResult = exp.findIndex(info, ctx);

      if (singleResult != null) {
        if (first) {
          result = singleResult;

        } else {
          if (result instanceof RequiredIndexCanditate) {
            ((RequiredIndexCanditate) result).addCanditate(singleResult);
          } else {
            var req = new RequiredIndexCanditate();
            req.addCanditate(result);
            req.addCanditate(singleResult);
            result = req;
          }
        }
      } else {
        return null;
      }

      first = false;
    }
    return result;
  }

  @Override
  public boolean isConstantExpression() {
    if (subBlocks.isEmpty()) {
      return true;
    }
    for (var exp : subBlocks) {
      if (exp.isConstantExpression()) {
        return true;
      }
    }
    return false;
  }

  @Override
  public boolean isIndexAware(IndexSearchInfo info, CommandContext ctx) {
    return false;
  }

  @Override
  public boolean isRangeExpression() {
    return false;
  }

  @Nullable
  @Override
  public String getRelatedIndexPropertyName() {
    return null;
  }

  @Nullable
  @Override
  public SQLBooleanExpression mergeUsingAnd(SQLBooleanExpression other,
      @Nonnull CommandContext ctx) {
    return null;
  }

  @Override
  public boolean varMightBeInUse(String varName) {
    for (var subBlock : subBlocks) {
      if (subBlock.varMightBeInUse(varName)) {
        return true;
      }
    }
    return false;
  }

  @Override
  public boolean isAggregate(DatabaseSessionEmbedded session) {
    for (var sub : subBlocks) {
      if (sub.isAggregate(session)) {
        return true;
      }
    }
    return false;
  }

  @Override
  public SQLOrBlock splitForAggregation(
      AggregateProjectionSplit aggregateProj, CommandContext ctx) {
    if (!isAggregate(ctx.getDatabaseSession())) {
      return this;
    }
    var result = new SQLOrBlock(-1);
    for (var sub : subBlocks) {
      result.subBlocks.add(sub.splitForAggregation(aggregateProj, ctx));
    }
    return result;
  }
}
/* JavaCC - OriginalChecksum=98d3077303a598705894dbb7bd4e1573 (do not edit this line) */
