/* Generated By:JJTree: Do not edit this line. SQLParenthesisExpression.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=O,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.jetbrains.youtrackdb.internal.core.sql.parser;

import com.jetbrains.youtrackdb.internal.core.command.CommandContext;
import com.jetbrains.youtrackdb.internal.core.db.DatabaseSessionEmbedded;
import com.jetbrains.youtrackdb.internal.core.db.record.record.Identifiable;
import com.jetbrains.youtrackdb.internal.core.exception.CommandExecutionException;
import com.jetbrains.youtrackdb.internal.core.query.Result;
import com.jetbrains.youtrackdb.internal.core.sql.executor.InsertExecutionPlan;
import com.jetbrains.youtrackdb.internal.core.sql.executor.InternalExecutionPlan;
import com.jetbrains.youtrackdb.internal.core.sql.executor.ResultInternal;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Set;

public class SQLParenthesisExpression extends SQLMathExpression {

  protected SQLExpression expression;
  protected SQLStatement statement;

  public SQLParenthesisExpression(int id) {
    super(id);
  }

  public SQLParenthesisExpression(YouTrackDBSql p, int id) {
    super(p, id);
  }

  public SQLParenthesisExpression(SQLExpression exp) {
    super(-1);
    this.expression = exp;
  }

  @Override
  public Object execute(Identifiable iCurrentRecord, CommandContext ctx) {
    if (expression != null) {
      return expression.execute(iCurrentRecord, ctx);
    }
    if (statement != null) {
      throw new UnsupportedOperationException(
          "Execution of select in parentheses is not supported");
    }
    return super.execute(iCurrentRecord, ctx);
  }

  @Override
  public Object execute(Result iCurrentRecord, CommandContext ctx) {
    if (expression != null) {
      return expression.execute(iCurrentRecord, ctx);
    }
    if (statement != null) {
      InternalExecutionPlan execPlan;
      execPlan = createExecutionPlan(ctx);
      if (execPlan instanceof InsertExecutionPlan) {
        ((InsertExecutionPlan) execPlan).executeInternal();
      }
      var session = ctx.getDatabaseSession();
      var rs = new LocalResultSet(session, execPlan);
      List<Result> result = new ArrayList<>();
      while (rs.hasNext()) {
        result.add(rs.next());
      }
      //      List<Result> result = rs.stream().collect(Collectors.toList());//TODO streamed...
      rs.close();
      return result;
    }
    return super.execute(iCurrentRecord, ctx);
  }

  private InternalExecutionPlan createExecutionPlan(CommandContext ctx) {
    InternalExecutionPlan execPlan;
    if (statement.originalStatement == null || statement.originalStatement.contains("?")) {
      // cannot cache statements with positional params, especially when it's in a
      // subquery/expression.
      execPlan = statement.createExecutionPlanNoCache(ctx, false);
    } else {
      execPlan = statement.createExecutionPlan(ctx, false);
    }
    return execPlan;
  }

  @Override
  public void toString(Map<Object, Object> params, StringBuilder builder) {
    builder.append("(");
    if (expression != null) {
      expression.toString(params, builder);
    } else if (statement != null) {
      statement.toString(params, builder);
    }
    builder.append(")");
  }

  @Override
  public void toGenericStatement(StringBuilder builder) {
    builder.append("(");
    if (expression != null) {
      expression.toGenericStatement(builder);
    } else if (statement != null) {
      statement.toGenericStatement(builder);
    }
    builder.append(")");
  }

  @Override
  protected boolean supportsBasicCalculation() {
    if (expression != null) {
      return expression.supportsBasicCalculation();
    }
    return true;
  }

  @Override
  public boolean isEarlyCalculated(CommandContext ctx) {
    // TODO implement query execution and early calculation;
    return expression != null && expression.isEarlyCalculated(ctx);
  }

  @Override
  public boolean needsAliases(Set<String> aliases) {
    return expression.needsAliases(aliases);
  }

  @Override
  public boolean isExpand() {
    if (expression != null) {
      return expression.isExpand();
    }
    return false;
  }

  @Override
  public boolean isAggregate(DatabaseSessionEmbedded session) {
    if (expression != null) {
      return expression.isAggregate(session);
    }
    return false;
  }

  @Override
  public boolean isCount() {
    if (expression != null) {
      return expression.isCount();
    }
    return false;
  }

  @Override
  public SimpleNode splitForAggregation(
      AggregateProjectionSplit aggregateProj, CommandContext ctx) {
    if (isAggregate(ctx.getDatabaseSession())) {
      var result = new SQLParenthesisExpression(-1);
      result.expression = expression.splitForAggregation(aggregateProj, ctx);
      return result;
    } else {
      return this;
    }
  }

  @Override
  public SQLParenthesisExpression copy() {
    var result = new SQLParenthesisExpression(-1);
    result.expression = expression == null ? null : expression.copy();
    result.statement = statement == null ? null : statement.copy();
    return result;
  }

  public void setStatement(SQLStatement statement) {
    this.statement = statement;
  }

  @Override
  public void extractSubQueries(SubQueryCollector collector) {
    if (expression != null) {
      expression.extractSubQueries(collector);
    } else if (statement != null) {
      var alias = collector.addStatement(statement);
      statement = null;
      expression = new SQLExpression(alias);
    }
  }

  @Override
  public void extractSubQueries(SQLIdentifier letAlias, SubQueryCollector collector) {
    if (expression != null) {
      expression.extractSubQueries(collector);
    } else if (statement != null) {
      var alias = collector.addStatement(letAlias, statement);
      statement = null;
      expression = new SQLExpression(alias);
    }
  }

  @Override
  public boolean refersToParent() {
    if (expression != null && expression.refersToParent()) {
      return true;
    }
    return statement != null && statement.refersToParent();
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    if (!super.equals(o)) {
      return false;
    }

    var that = (SQLParenthesisExpression) o;

    if (!Objects.equals(expression, that.expression)) {
      return false;
    }
    return Objects.equals(statement, that.statement);
  }

  @Override
  public int hashCode() {
    var result = super.hashCode();
    result = 31 * result + (expression != null ? expression.hashCode() : 0);
    result = 31 * result + (statement != null ? statement.hashCode() : 0);
    return result;
  }

  @Override
  public List<String> getMatchPatternInvolvedAliases() {
    return expression.getMatchPatternInvolvedAliases(); // TODO also check the statement...?
  }

  @Override
  public void applyRemove(ResultInternal result, CommandContext ctx) {
    if (expression != null) {
      expression.applyRemove(result, ctx);
    } else {
      throw new CommandExecutionException(ctx.getDatabaseSession(), "Cannot apply REMOVE " + this);
    }
  }

  @Override
  public Result serialize(DatabaseSessionEmbedded session) {
    var result = (ResultInternal) super.serialize(session);
    if (expression != null) {
      result.setProperty("expression", expression.serialize(session));
    }
    if (statement != null) {
      result.setProperty("statement", statement.serialize(session));
    }
    return result;
  }

  @Override
  public void deserialize(Result fromResult) {
    super.deserialize(fromResult);
    if (fromResult.getProperty("expression") != null) {
      expression = new SQLExpression(-1);
      expression.deserialize(fromResult.getProperty("expression"));
    }
    if (fromResult.getProperty("statement") != null) {
      statement = SQLStatement.deserializeFromOResult(fromResult.getProperty("statement"));
    }
  }

  @Override
  public boolean isCacheable(DatabaseSessionEmbedded session) {
    if (expression != null) {
      return expression.isCacheable(session);
    }
    if (statement != null) {
      return statement.executinPlanCanBeCached(session);
    }
    return true;
  }

  @Override
  public boolean varMightBeInUse(String varName) {
    return super.varMightBeInUse(varName) ||
        expression != null && expression.varMightBeInUse(varName);
  }
}
/* JavaCC - OriginalChecksum=4656e5faf4f54dc3fc45a06d8e375c35 (do not edit this line) */
