/* Generated By:JJTree: Do not edit this line. SQLRid.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=O,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.jetbrains.youtrackdb.internal.core.sql.parser;

import com.jetbrains.youtrackdb.internal.core.command.BasicCommandContext;
import com.jetbrains.youtrackdb.internal.core.command.CommandContext;
import com.jetbrains.youtrackdb.internal.core.db.DatabaseSessionEmbedded;
import com.jetbrains.youtrackdb.internal.core.db.record.record.Identifiable;
import com.jetbrains.youtrackdb.internal.core.id.RecordId;
import com.jetbrains.youtrackdb.internal.core.id.RecordIdInternal;
import com.jetbrains.youtrackdb.internal.core.query.Result;
import com.jetbrains.youtrackdb.internal.core.sql.executor.ResultInternal;
import java.util.Map;
import java.util.Objects;
import javax.annotation.Nullable;

public class SQLRid extends SimpleNode {

  protected SQLInteger collection;
  protected SQLInteger position;

  protected SQLExpression expression;
  protected boolean legacy;

  public SQLRid(int id) {
    super(id);
  }

  public SQLRid(YouTrackDBSql p, int id) {
    super(p, id);
  }

  @Override
  public String toString(String prefix) {
    return "#" + collection.getValue() + ":" + position.getValue();
  }

  @Override
  public void toString(Map<Object, Object> params, StringBuilder builder) {
    if (legacy || (expression == null && collection != null && position != null)) {
      builder.append("#").append(collection.getValue()).append(":").append(position.getValue());
    } else {
      builder.append("{\"@rid\":");
      expression.toString(params, builder);
      builder.append("}");
    }
  }

  @Override
  public void toGenericStatement(StringBuilder builder) {
    if (legacy || (expression == null && collection != null && position != null)) {
      builder.append(PARAMETER_PLACEHOLDER);
    } else {
      builder.append("{\"@rid\":");
      expression.toGenericStatement(builder);
      builder.append("}");
    }
  }

  @Nullable
  public RecordIdInternal toRecordId(Result target, CommandContext ctx) {
    if (legacy || (expression == null && collection != null && position != null)) {
      return new RecordId(collection.value.intValue(), position.value.longValue());
    } else {
      var result = expression.execute(target, ctx);
      return switch (result) {
        case null -> null;
        case Identifiable identifiable -> (RecordIdInternal) identifiable.getIdentity();
        case String s -> RecordIdInternal.fromString(s, false);
        default -> null;
      };
    }
  }

  @Nullable
  public RecordIdInternal toRecordId(Identifiable target, CommandContext ctx) {
    if (legacy || (expression == null && collection != null && position != null)) {
      return new RecordId(collection.value.intValue(), position.value.longValue());
    } else {
      var result = expression.execute(target, ctx);
      return switch (result) {
        case null -> null;
        case Identifiable identifiable -> (RecordIdInternal) identifiable.getIdentity();
        case String s -> RecordIdInternal.fromString(s, false);
        default -> null;
      };
    }
  }

  @Override
  public SQLRid copy() {
    var result = new SQLRid(-1);
    result.collection = collection == null ? null : collection.copy();
    result.position = position == null ? null : position.copy();
    result.expression = expression == null ? null : expression.copy();
    result.legacy = legacy;
    return result;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }

    var oRid = (SQLRid) o;

    if (!Objects.equals(collection, oRid.collection)) {
      return false;
    }
    if (!Objects.equals(position, oRid.position)) {
      return false;
    }
    if (!Objects.equals(expression, oRid.expression)) {
      return false;
    }
    return legacy == oRid.legacy;
  }

  @Override
  public int hashCode() {
    var result = collection != null ? collection.hashCode() : 0;
    result = 31 * result + (position != null ? position.hashCode() : 0);
    result = 31 * result + (expression != null ? expression.hashCode() : 0);
    return result;
  }

  public void setCollection(SQLInteger collection) {
    this.collection = collection;
  }

  public void setPosition(SQLInteger position) {
    this.position = position;
  }

  public void setLegacy(boolean b) {
    this.legacy = b;
  }

  public SQLInteger getCollection() {
    if (expression != null) {
      var rid = toRecordId((Result) null, new BasicCommandContext());
      if (rid != null) {
        var result = new SQLInteger(-1);
        result.setValue(rid.getCollectionId());
        return result;
      }
    }
    return collection;
  }

  public SQLInteger getPosition() {
    if (expression != null) {
      var rid = toRecordId((Result) null, new BasicCommandContext());
      if (rid != null) {
        var result = new SQLInteger(-1);
        result.setValue(rid.getCollectionPosition());
        return result;
      }
    }
    return position;
  }

  public Result serialize(DatabaseSessionEmbedded session) {
    var result = new ResultInternal(session);

    if (collection != null) {
      result.setProperty("collection", collection.serialize(session));
    }
    if (position != null) {
      result.setProperty("position", position.serialize(session));
    }
    if (expression != null) {
      result.setProperty("expression", expression.serialize(session));
    }
    result.setProperty("legacy", legacy);

    return result;
  }

  public void deserialize(Result fromResult) {
    if (fromResult.getProperty("collection") != null) {
      collection = new SQLInteger(-1);
      collection.deserialize(fromResult.getProperty("collection"));
    }
    if (fromResult.getProperty("position") != null) {
      position = new SQLInteger(-1);
      position.deserialize(fromResult.getProperty("position"));
    }
    if (fromResult.getProperty("expression") != null) {
      expression = new SQLExpression(-1);
      expression.deserialize(fromResult.getProperty("expression"));
    }
    legacy = fromResult.getProperty("legacy");
  }
}
/* JavaCC - OriginalChecksum=c2c6d67d7722e29212e438574698d7cd (do not edit this line) */
