/* Generated By:JJTree: Do not edit this line. SQLRecordAttribute.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=O,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.jetbrains.youtrackdb.internal.core.sql.parser;

import com.jetbrains.youtrackdb.api.exception.RecordNotFoundException;
import com.jetbrains.youtrackdb.internal.core.command.CommandContext;
import com.jetbrains.youtrackdb.internal.core.db.DatabaseSessionEmbedded;
import com.jetbrains.youtrackdb.internal.core.db.record.record.Entity;
import com.jetbrains.youtrackdb.internal.core.query.Result;
import com.jetbrains.youtrackdb.internal.core.record.RecordAbstract;
import com.jetbrains.youtrackdb.internal.core.record.impl.EntityImpl;
import com.jetbrains.youtrackdb.internal.core.record.impl.RecordBytes;
import com.jetbrains.youtrackdb.internal.core.record.impl.EdgeEntityImpl;
import com.jetbrains.youtrackdb.internal.core.record.impl.VertexEntityImpl;
import com.jetbrains.youtrackdb.internal.core.sql.executor.ResultInternal;
import java.util.Map;
import java.util.Objects;
import javax.annotation.Nullable;

public class SQLRecordAttribute extends SimpleNode {

  protected String name;

  public SQLRecordAttribute(int id) {
    super(id);
  }

  public SQLRecordAttribute(YouTrackDBSql p, int id) {
    super(p, id);
  }

  @Override
  public void toString(Map<Object, Object> params, StringBuilder builder) {
    builder.append(name);
  }

  @Override
  public void toGenericStatement(StringBuilder builder) {
    builder.append(name);
  }

  @Override
  public SQLRecordAttribute copy() {
    var result = new SQLRecordAttribute(-1);
    result.name = name;
    return result;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }

    var that = (SQLRecordAttribute) o;

    return Objects.equals(name, that.name);
  }

  @Override
  public int hashCode() {
    return name != null ? name.hashCode() : 0;
  }

  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public Result serialize(DatabaseSessionEmbedded db) {
    var result = new ResultInternal(db);
    result.setProperty("name", name);
    return result;
  }

  public void deserialize(Result fromResult) {
    name = fromResult.getProperty("name");
  }

  @Nullable
  public Object evaluate(Result iCurrentResult, CommandContext ctx) {
    var session = ctx.getDatabaseSession();
    if (name.equalsIgnoreCase("@rid")) {
      var identity = iCurrentResult.getIdentity();
      if (identity == null) {
        identity = iCurrentResult.getProperty(name);
      }
      return identity;
    } else if (name.equalsIgnoreCase("@class")) {
      if (iCurrentResult.isEntity()) {
        var schemaClass = ((EntityImpl) iCurrentResult.asEntity()).getImmutableSchemaClass(
            session);
        if (schemaClass != null) {
          return schemaClass.getName();
        }
      }

      return iCurrentResult.getString(name);
    } else if (name.equalsIgnoreCase("@version")) {
      if (iCurrentResult.isIdentifiable()) {
        return iCurrentResult.asRecord().getVersion();
      }
      return iCurrentResult.getProperty(name);
    } else if (name.equals("@type")) {
      if (iCurrentResult.isIdentifiable()) {
        var r = iCurrentResult.asRecord();
        ctx.getDatabaseSession();
        var recordType = ((RecordAbstract) r).getRecordType();
        if (recordType == EntityImpl.RECORD_TYPE) {
          return "entity";
        } else if (recordType == RecordBytes.RECORD_TYPE) {
          return "blob";
        } else if (recordType == VertexEntityImpl.RECORD_TYPE) {
          return "vertex";
        } else if (recordType == EdgeEntityImpl.RECORD_TYPE) {
          return "edge";
        } else {
          return "unknown";
        }
      }
      return iCurrentResult.getString(name);
    } else if (name.equals("@size")) {
      if (iCurrentResult.isIdentifiable()) {
        return ((RecordAbstract) iCurrentResult.asRecord()).toStream().length;
      }
      return iCurrentResult.getProperty(name);
    } else if (name.equals("@raw")) {
      if (iCurrentResult.isIdentifiable()) {
        return ((RecordAbstract) iCurrentResult.asRecord()).toStream();
      }
      return iCurrentResult.getProperty(name);
    } else if (name.equals("@rid")) {
      if (iCurrentResult.isIdentifiable()) {
        return iCurrentResult.getIdentity();
      }
      return iCurrentResult.getProperty(name);
    }

    return null;
  }

  @Nullable
  public Object evaluate(Entity iCurrentRecord, CommandContext ctx) {
    if (iCurrentRecord == null) {
      return null;
    }
    var session = ctx.getDatabaseSession();
    if (name.equalsIgnoreCase("@rid")) {
      return iCurrentRecord.getIdentity();
    } else if (name.equalsIgnoreCase("@class")) {
      return iCurrentRecord.getSchemaClassName();
    } else if (name.equalsIgnoreCase("@version")) {
      try {
        var transaction = session.getActiveTransaction();
        var record = transaction.load(iCurrentRecord);
        return record.getVersion();
      } catch (RecordNotFoundException e) {
        return null;
      }
    }
    return null;
  }
}
/* JavaCC - OriginalChecksum=45ce3cd16399dec7d7ef89f8920d02ae (do not edit this line) */
