/* Generated By:JJTree: Do not edit this line. SQLServerStatement.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=O,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.jetbrains.youtrackdb.internal.core.sql.parser;

import com.jetbrains.youtrackdb.internal.core.command.ServerCommandContext;
import com.jetbrains.youtrackdb.internal.core.db.DatabaseSessionEmbedded;
import com.jetbrains.youtrackdb.internal.core.db.YouTrackDBInternal;
import com.jetbrains.youtrackdb.internal.core.exception.BaseException;
import com.jetbrains.youtrackdb.internal.core.exception.CommandExecutionException;
import com.jetbrains.youtrackdb.internal.core.exception.CommandSQLParsingException;
import com.jetbrains.youtrackdb.internal.core.query.Result;
import com.jetbrains.youtrackdb.internal.core.query.ResultSet;
import com.jetbrains.youtrackdb.internal.core.sql.executor.InternalExecutionPlan;
import com.jetbrains.youtrackdb.internal.core.sql.executor.ResultInternal;
import java.util.Map;
import javax.annotation.Nullable;

public class SQLServerStatement extends SimpleNode {

  public SQLServerStatement(int id) {
    super(id);
  }

  public SQLServerStatement(YouTrackDBSql p, int id) {
    super(p, id);
  }

  @Override
  public void toString(Map<Object, Object> params, StringBuilder builder) {
    throw new UnsupportedOperationException(
        "missing implementation in " + getClass().getSimpleName());
  }

  @Override
  public void toGenericStatement(StringBuilder builder) {
    throw new UnsupportedOperationException();
  }

  public void validate() throws CommandSQLParsingException {
  }

  @Override
  public String toString(String prefix) {
    var builder = new StringBuilder();
    toString(null, builder);
    return builder.toString();
  }


  public ResultSet execute(YouTrackDBInternal db, Object[] args, boolean usePlanCache) {
    return execute(db, args, null, usePlanCache);
  }

  public ResultSet execute(
      YouTrackDBInternal db,
      Object[] args,
      ServerCommandContext parentContext,
      boolean usePlanCache) {
    throw new UnsupportedOperationException();
  }

  public ResultSet execute(YouTrackDBInternal db, Map args, boolean usePlanCache) {
    return execute(db, args, null, usePlanCache);
  }

  public ResultSet execute(
      YouTrackDBInternal db, Map args, ServerCommandContext parentContext, boolean usePlanCache) {
    throw new UnsupportedOperationException();
  }

  /**
   * creates an execution plan for current statement, with profiling disabled
   *
   * @param ctx the context that will be used to execute the statement
   * @return an execution plan
   */
  public InternalExecutionPlan createExecutionPlan(ServerCommandContext ctx) {
    return createExecutionPlan(ctx, false);
  }

  /**
   * creates an execution plan for current statement
   *
   * @param ctx     the context that will be used to execute the statement
   * @param profile true to enable profiling, false to disable it
   * @return an execution plan
   */
  public InternalExecutionPlan createExecutionPlan(ServerCommandContext ctx, boolean profile) {
    throw new UnsupportedOperationException();
  }

  public InternalExecutionPlan createExecutionPlanNoCache(
      ServerCommandContext ctx, boolean profile) {
    return createExecutionPlan(ctx, profile);
  }

  @Override
  public SQLServerStatement copy() {
    throw new UnsupportedOperationException("IMPLEMENT copy() ON " + getClass().getSimpleName());
  }

  public boolean refersToParent() {
    throw new UnsupportedOperationException(
        "Implement " + getClass().getSimpleName() + ".refersToParent()");
  }

  public boolean isIdempotent() {
    return false;
  }

  @Nullable
  public static SQLStatement deserializeFromOResult(Result res) {
    try {
      var result =
          (SQLStatement)
              Class.forName(res.getProperty("__class"))
                  .getConstructor(Integer.class)
                  .newInstance(-1);
      result.deserialize(res);
    } catch (Exception e) {
      throw BaseException.wrapException(
          new CommandExecutionException(res.getBoundedToSession(), ""), e,
          res.getBoundedToSession());
    }
    return null;
  }

  public Result serialize(DatabaseSessionEmbedded db) {
    var result = new ResultInternal(db);
    result.setProperty("__class", getClass().getName());
    return result;
  }

  public void deserialize(Result fromResult) {
    throw new UnsupportedOperationException();
  }

  public boolean executinPlanCanBeCached() {
    return false;
  }
}
/* JavaCC - OriginalChecksum=86cab5eeff02ee2a2f8c5e0c0a017e6b (do not edit this line) */
