/* Generated By:JJTree: Do not edit this line. SQLStatement.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=O,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.jetbrains.youtrackdb.internal.core.sql.parser;

import com.jetbrains.youtrackdb.internal.core.command.CommandContext;
import com.jetbrains.youtrackdb.internal.core.db.DatabaseSessionEmbedded;
import com.jetbrains.youtrackdb.internal.core.exception.BaseException;
import com.jetbrains.youtrackdb.internal.core.exception.CommandExecutionException;
import com.jetbrains.youtrackdb.internal.core.exception.CommandSQLParsingException;
import com.jetbrains.youtrackdb.internal.core.query.Result;
import com.jetbrains.youtrackdb.internal.core.query.ResultSet;
import com.jetbrains.youtrackdb.internal.core.sql.executor.InternalExecutionPlan;
import com.jetbrains.youtrackdb.internal.core.sql.executor.ResultInternal;
import java.util.Map;
import javax.annotation.Nullable;

public class SQLStatement extends SimpleNode {

  // only for internal use!!! (caching and profiling)
  protected String originalStatement;

  public static final String CUSTOM_STRICT_SQL = "strictSql";

  public SQLStatement(int id) {
    super(id);
  }

  public SQLStatement(YouTrackDBSql p, int id) {
    super(p, id);
  }

  @Override
  public void toString(Map<Object, Object> params, StringBuilder builder) {
    builder.append(originalStatement);
  }

  @Override
  public void toGenericStatement(StringBuilder builder) {
    builder.append(originalStatement);
  }

  public void validate() throws CommandSQLParsingException {
  }

  @Override
  public String toString(String prefix) {
    var builder = new StringBuilder();
    toString(null, builder);
    return builder.toString();
  }


  public ResultSet execute(DatabaseSessionEmbedded session, Object[] args) {
    return execute(session, args, true);
  }

  public ResultSet execute(
      DatabaseSessionEmbedded session, Object[] args, CommandContext parentContext) {
    return execute(session, args, parentContext, true);
  }

  public ResultSet execute(DatabaseSessionEmbedded session, Map<Object, Object> args) {
    return execute(session, args, true);
  }

  public ResultSet execute(DatabaseSessionEmbedded session, Map<Object, Object> args,
      CommandContext parentContext) {
    return execute(session, args, parentContext, true);
  }

  public ResultSet execute(DatabaseSessionEmbedded session, Object[] args, boolean usePlanCache) {
    return execute(session, args, null, usePlanCache);
  }

  public ResultSet execute(
      DatabaseSessionEmbedded session,
      Object[] args,
      CommandContext parentContext,
      boolean usePlanCache) {
    throw new UnsupportedOperationException();
  }

  public ResultSet execute(DatabaseSessionEmbedded session, Map<Object, Object> args,
      boolean usePlanCache) {
    return execute(session, args, null, usePlanCache);
  }

  public ResultSet execute(
      DatabaseSessionEmbedded session, Map<Object, Object> args, CommandContext parentContext,
      boolean usePlanCache) {
    throw new UnsupportedOperationException();
  }

  /**
   * creates an execution plan for current statement, with profiling disabled
   *
   * @param ctx the context that will be used to execute the statement
   * @return an execution plan
   */
  public InternalExecutionPlan createExecutionPlan(CommandContext ctx) {
    return createExecutionPlan(ctx, false);
  }

  /**
   * creates an execution plan for current statement
   *
   * @param ctx     the context that will be used to execute the statement
   * @param profile true to enable profiling, false to disable it
   * @return an execution plan
   */
  public InternalExecutionPlan createExecutionPlan(CommandContext ctx, boolean profile) {
    throw new UnsupportedOperationException();
  }

  public InternalExecutionPlan createExecutionPlanNoCache(CommandContext ctx, boolean profile) {
    return createExecutionPlan(ctx, profile);
  }

  @Override
  public SQLStatement copy() {
    throw new UnsupportedOperationException("IMPLEMENT copy() ON " + getClass().getSimpleName());
  }

  public boolean refersToParent() {
    throw new UnsupportedOperationException(
        "Implement " + getClass().getSimpleName() + ".refersToParent()");
  }

  public boolean isIdempotent() {
    return false;
  }

  @Nullable
  public static SQLStatement deserializeFromOResult(Result res) {
    try {
      var result =
          (SQLStatement)
              Class.forName(res.getProperty("__class"))
                  .getConstructor(Integer.class)
                  .newInstance(-1);
      result.deserialize(res);
    } catch (Exception e) {
      throw BaseException.wrapException(
          new CommandExecutionException(res.getBoundedToSession(), ""), e,
          res.getBoundedToSession());
    }
    return null;
  }

  public Result serialize(DatabaseSessionEmbedded session) {
    var result = new ResultInternal(session);
    result.setProperty("__class", getClass().getName());
    return result;
  }

  public void deserialize(Result fromResult) {
    throw new UnsupportedOperationException();
  }

  public boolean executinPlanCanBeCached(DatabaseSessionEmbedded session) {
    return false;
  }

  public String getOriginalStatement() {
    return originalStatement;
  }

  public void setOriginalStatement(String originalStatement) {
    this.originalStatement = originalStatement;
  }
}
/* JavaCC - OriginalChecksum=589c4dcc8287f430e46d8eb12b0412c5 (do not edit this line) */
