/* Generated By:JJTree: Do not edit this line. SQLWhereClause.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=O,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.jetbrains.youtrackdb.internal.core.sql.parser;

import com.jetbrains.youtrackdb.internal.common.util.RawPair;
import com.jetbrains.youtrackdb.internal.core.command.CommandContext;
import com.jetbrains.youtrackdb.internal.core.db.DatabaseSessionEmbedded;
import com.jetbrains.youtrackdb.internal.core.db.record.record.Identifiable;
import com.jetbrains.youtrackdb.internal.core.db.record.record.RID;
import com.jetbrains.youtrackdb.internal.core.index.CompositeIndexDefinition;
import com.jetbrains.youtrackdb.internal.core.index.CompositeKey;
import com.jetbrains.youtrackdb.internal.core.index.Index;
import com.jetbrains.youtrackdb.internal.core.index.PropertyIndexDefinition;
import com.jetbrains.youtrackdb.internal.core.index.engine.EquiDepthHistogram;
import com.jetbrains.youtrackdb.internal.core.index.engine.IndexStatistics;
import com.jetbrains.youtrackdb.internal.core.index.engine.SelectivityEstimator;
import com.jetbrains.youtrackdb.internal.core.metadata.schema.PropertyTypeInternal;
import com.jetbrains.youtrackdb.internal.core.metadata.schema.SchemaClassInternal;
import com.jetbrains.youtrackdb.internal.core.query.Result;
import com.jetbrains.youtrackdb.internal.core.sql.executor.ResultInternal;
import com.jetbrains.youtrackdb.internal.core.sql.executor.metadata.IndexCandidate;
import com.jetbrains.youtrackdb.internal.core.sql.executor.metadata.IndexFinder;
import java.util.ArrayList;
import java.util.Collection;
import java.util.Collections;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import java.util.Set;
import java.util.Spliterator;
import java.util.stream.Collectors;
import javax.annotation.Nullable;

public class SQLWhereClause extends SimpleNode {

  protected SQLBooleanExpression baseExpression;

  private List<SQLAndBlock> flattened;

  public SQLWhereClause(int id) {
    super(id);
  }

  public SQLWhereClause(YouTrackDBSql p, int id) {
    super(p, id);
  }

  public boolean matchesFilters(Identifiable currentRecord, CommandContext ctx) {
    if (baseExpression == null) {
      return true;
    }
    return baseExpression.evaluate(currentRecord, ctx);
  }

  public boolean matchesFilters(Result currentRecord, CommandContext ctx) {
    if (baseExpression == null) {
      return true;
    }
    return baseExpression.evaluate(currentRecord, ctx);
  }

  @Override
  public void toString(Map<Object, Object> params, StringBuilder builder) {
    if (baseExpression == null) {
      return;
    }
    baseExpression.toString(params, builder);
  }

  @Override
  public void toGenericStatement(StringBuilder builder) {
    if (baseExpression == null) {
      return;
    }
    baseExpression.toGenericStatement(builder);
  }

  /**
   * estimates how many items of this class will be returned applying this filter
   *
   * @return an estimation of the number of records of this class returned applying this filter, 0
   * if and only if sure that no records are returned
   */
  public long estimate(SchemaClassInternal schemaClass, long threshold, CommandContext ctx) {
    var session = ctx.getDatabaseSession();
    var classCount = schemaClass.approximateCount(session);
    if (classCount <= 0) {
      return 0;
    }

    // Upper-bound estimate: count/2 heuristic when no histogram is available.
    var count = classCount > 1 ? classCount / 2 : classCount;
    if (count < threshold) {
      return count;
    }

    var indexesCount = 0L;
    var flattenedConditions = flatten(ctx, schemaClass);
    var indexes = schemaClass.getIndexesInternal();
    for (var condition : flattenedConditions) {

      var indexedFunctConditions =
          condition.getIndexedFunctionConditions(schemaClass, session);

      var conditionEstimation = Long.MAX_VALUE;

      if (indexedFunctConditions != null) {
        for (var cond : indexedFunctConditions) {
          var from = new SQLFromClause(-1);
          from.item = new SQLFromItem(-1);
          from.item.setIdentifier(new SQLIdentifier(schemaClass.getName()));
          var newCount = cond.estimateIndexed(from, ctx);
          if (newCount < conditionEstimation) {
            conditionEstimation = newCount;
          }
        }
      } else {
        // Try histogram-based estimation first (handles equality, range,
        // IS NULL, BETWEEN, NOT, etc. without expensive index probes).
        for (var index : indexes) {
          var histEstimate = estimateConditionFromHistogram(
              session, index, condition, classCount, ctx);
          if (histEstimate >= 0 && histEstimate < conditionEstimation) {
            conditionEstimation = histEstimate;
          }
        }

        // Fall back to expensive index probes for equality conditions
        // when no histogram is available.
        if (conditionEstimation == Long.MAX_VALUE) {
          var conditions = getEqualityOperations(condition, ctx);

          for (var index : indexes) {
            var indexedFields = index.getDefinition().getProperties();
            var nMatchingKeys = 0;
            for (var indexedField : indexedFields) {
              if (conditions.containsKey(indexedField)) {
                nMatchingKeys++;
              } else {
                break;
              }
            }
            if (nMatchingKeys > 0) {
              var newCount =
                  estimateFromIndex(session, index, conditions, nMatchingKeys);
              if (newCount < conditionEstimation) {
                conditionEstimation = newCount;
              }
            }
          }
        }
      }
      if (conditionEstimation > count) {
        return count;
      }
      indexesCount += conditionEstimation;
    }
    return Math.min(indexesCount, count);
  }

  private static long estimateFromIndex(
      DatabaseSessionEmbedded session, Index index, Map<String, Object> conditions,
      int nMatchingKeys) {
    if (nMatchingKeys < 1) {
      throw new IllegalArgumentException("Cannot estimate from an index with zero keys");
    }
    var definition = index.getDefinition();
    var definitionFields = definition.getProperties();
    Object key = null;
    if (definition instanceof PropertyIndexDefinition) {
      key = convert(session, conditions.get(definitionFields.getFirst()), definition.getTypes()[0]);
    } else if (definition instanceof CompositeIndexDefinition) {
      key = new CompositeKey();
      for (var i = 0; i < nMatchingKeys; i++) {
        var keyValue =
            convert(session, conditions.get(definitionFields.get(i)), definition.getTypes()[i]);
        ((CompositeKey) key).addKey(keyValue);
      }
    }
    if (key != null) {
      if (conditions.size() == definitionFields.size()) {
        try (var rids = index.getRids(session, key)) {
          return rids.count();
        }
      } else {
        final Spliterator<RawPair<Object, RID>> spliterator;

        try (var stream =
            index.streamEntriesBetween(session, key, true, key, true, true)) {
          spliterator = stream.spliterator();
          return spliterator.estimateSize();
        }
      }
    }
    return Long.MAX_VALUE;
  }

  private static Object convert(DatabaseSessionEmbedded session, Object o,
      PropertyTypeInternal oType) {
    return PropertyTypeInternal.convert(session, o, oType.getDefaultJavaType());
  }

  private static Map<String, Object> getEqualityOperations(
      SQLAndBlock condition, CommandContext ctx) {
    Map<String, Object> result = new HashMap<>();
    for (var expression : condition.subBlocks) {
      if (expression instanceof SQLBinaryCondition b) {
        if (b.operator instanceof SQLEqualsOperator) {
          if (b.left.isBaseIdentifier() && b.right.isEarlyCalculated(ctx)) {
            result.put(b.left.toString(), b.right.execute((Result) null, ctx));
          }
        }
      }
    }
    return result;
  }

  // ═══════════════════════════════════════════════════════════════════
  // HAND-WRITTEN histogram estimation methods (YTDB-584).
  // These are NOT generated by JJTree — preserve them during grammar
  // regeneration. They live here (not in a separate helper class)
  // because they access package-private AST fields (subBlocks, left,
  // right, operator, negate, sub, expression, first/second/third).
  // ═══════════════════════════════════════════════════════════════════

  /**
   * Estimates the number of matching rows for an AND block using the histogram
   * from the given index. Multiplies selectivities of matching predicates
   * (independence assumption per Section 7.3). Returns -1 if no predicate in
   * the block references the index's leading field, or if no statistics exist.
   */
  private static long estimateConditionFromHistogram(
      DatabaseSessionEmbedded session, Index index,
      SQLAndBlock condition, long classCount, CommandContext ctx) {
    var stats = index.getStatistics(session);
    if (stats == null || stats.totalCount() == 0) {
      return -1;
    }
    var histogram = index.getHistogram(session);
    var leadingField = index.getDefinition().getProperties().getFirst();

    // Detect two-sided range on the leading field (e.g., f > 20 AND f < 30)
    // and combine into a single estimateRange call for tighter estimates.
    var rangeResult = detectTwoSidedRange(
        condition, leadingField, stats, histogram, ctx);

    double selectivity = 1.0;
    boolean anyEstimated = false;

    if (rangeResult != null) {
      // Use the combined range selectivity and skip the two range predicates
      selectivity *= rangeResult.selectivity;
      anyEstimated = true;

      for (var expr : condition.subBlocks) {
        if (expr == rangeResult.lowerExpr || expr == rangeResult.upperExpr) {
          continue; // already accounted for by the combined range
        }
        var sel = estimatePredicateSelectivity(
            expr, leadingField, stats, histogram, ctx);
        if (sel >= 0) {
          selectivity *= sel;
        }
      }
    } else {
      // No two-sided range detected — estimate each predicate independently
      for (var expr : condition.subBlocks) {
        var sel = estimatePredicateSelectivity(
            expr, leadingField, stats, histogram, ctx);
        if (sel >= 0) {
          selectivity *= sel;
          anyEstimated = true;
        }
      }
    }

    if (!anyEstimated) {
      return -1;
    }
    // Note: selectivity is a fraction of non-null index entries (see
    // SelectivityEstimator Javadoc), but classCount includes all rows.
    // This produces a mild overestimate bounded by the null fraction —
    // an intentional conservative bias (see SelectivityEstimator class doc).
    return Math.max(1, (long) (classCount * selectivity));
  }

  /**
   * Result of detecting a two-sided range pattern in an AND block.
   */
  private record TwoSidedRange(
      SQLBooleanExpression lowerExpr,
      SQLBooleanExpression upperExpr,
      double selectivity
  ) {}

  /**
   * Scans the AND block's sub-blocks for a pair of binary conditions on
   * the same field where one is a lower bound (GT/GE) and the other is an
   * upper bound (LT/LE). Returns a {@link TwoSidedRange} with the combined
   * selectivity via {@link SelectivityEstimator#estimateRange}, or null if
   * no such pair is found.
   */
  @Nullable
  private static TwoSidedRange detectTwoSidedRange(
      SQLAndBlock condition, String indexField,
      IndexStatistics stats, @Nullable EquiDepthHistogram histogram,
      CommandContext ctx) {
    SQLBinaryCondition lower = null;
    SQLBinaryCondition upper = null;

    for (var expr : condition.subBlocks) {
      if (!(expr instanceof SQLBinaryCondition bc)) {
        continue;
      }
      if (!matchesField(bc.left, indexField)
          || !bc.right.isEarlyCalculated(ctx)) {
        continue;
      }
      var op = bc.operator;
      if (op instanceof SQLGtOperator || op instanceof SQLGeOperator) {
        if (lower == null) {
          lower = bc;
        }
      } else if (op instanceof SQLLtOperator || op instanceof SQLLeOperator) {
        if (upper == null) {
          upper = bc;
        }
      }
    }

    if (lower == null || upper == null) {
      return null;
    }

    var fromKey = lower.right.execute((Result) null, ctx);
    var toKey = upper.right.execute((Result) null, ctx);
    if (fromKey == null || toKey == null) {
      return null;
    }

    boolean fromInclusive = lower.operator instanceof SQLGeOperator;
    boolean toInclusive = upper.operator instanceof SQLLeOperator;
    double sel = SelectivityEstimator.estimateRange(
        stats, histogram, fromKey, toKey, fromInclusive, toInclusive);
    return new TwoSidedRange(lower, upper, sel);
  }

  /**
   * Estimates the selectivity of a single predicate using index statistics.
   * Returns -1 if the predicate does not reference the index field or cannot
   * be estimated.
   */
  private static double estimatePredicateSelectivity(
      SQLBooleanExpression expr, String indexField,
      IndexStatistics stats, @Nullable EquiDepthHistogram histogram,
      CommandContext ctx) {
    if (expr instanceof SQLBinaryCondition bc) {
      return estimateBinaryConditionSelectivity(
          bc, indexField, stats, histogram, ctx);
    }
    if (expr instanceof SQLBetweenCondition bt) {
      return estimateBetweenSelectivity(
          bt, indexField, stats, histogram, ctx);
    }
    if (expr instanceof SQLIsNullCondition nc) {
      if (matchesField(nc.expression, indexField)) {
        return SelectivityEstimator.estimateIsNull(stats, histogram);
      }
    }
    if (expr instanceof SQLIsNotNullCondition nnc) {
      if (matchesField(nnc.expression, indexField)) {
        return SelectivityEstimator.estimateIsNotNull(stats, histogram);
      }
    }
    if (expr instanceof SQLInCondition ic) {
      return estimateInConditionSelectivity(
          ic, indexField, stats, histogram, ctx);
    }
    if (expr instanceof SQLNotBlock nb && nb.negate) {
      var inner = estimatePredicateSelectivity(
          nb.sub, indexField, stats, histogram, ctx);
      return inner >= 0 ? 1.0 - inner : -1;
    }
    return -1;
  }

  /**
   * Dispatches a binary condition ({@code f op value}) to the appropriate
   * {@link SelectivityEstimator} method based on the operator type.
   */
  private static double estimateBinaryConditionSelectivity(
      SQLBinaryCondition bc, String indexField,
      IndexStatistics stats, @Nullable EquiDepthHistogram histogram,
      CommandContext ctx) {
    if (!matchesField(bc.left, indexField)
        || !bc.right.isEarlyCalculated(ctx)) {
      return -1;
    }
    var value = bc.right.execute((Result) null, ctx);
    if (value == null) {
      return -1;
    }
    return SelectivityEstimator.estimateForOperator(
        bc.operator, stats, histogram, value);
  }

  /**
   * Estimates selectivity for {@code field BETWEEN lower AND upper}.
   */
  private static double estimateBetweenSelectivity(
      SQLBetweenCondition bt, String indexField,
      IndexStatistics stats, @Nullable EquiDepthHistogram histogram,
      CommandContext ctx) {
    if (!matchesField(bt.first, indexField)) {
      return -1;
    }
    if (!bt.second.isEarlyCalculated(ctx)
        || !bt.third.isEarlyCalculated(ctx)) {
      return -1;
    }
    var fromKey = bt.second.execute((Result) null, ctx);
    var toKey = bt.third.execute((Result) null, ctx);
    if (fromKey == null || toKey == null) {
      return -1;
    }
    return SelectivityEstimator.estimateRange(
        stats, histogram, fromKey, toKey, true, true);
  }

  /**
   * Estimates selectivity for {@code field IN (v1, v2, ..., vN)} expressed as
   * an {@link SQLInCondition}. The right-hand side may be a math expression
   * that evaluates to a collection, or a parameter.
   */
  private static double estimateInConditionSelectivity(
      SQLInCondition ic, String indexField,
      IndexStatistics stats, @Nullable EquiDepthHistogram histogram,
      CommandContext ctx) {
    if (ic.getLeft() == null || !matchesField(ic.getLeft(), indexField)) {
      return -1;
    }
    // The right side can be a math expression ([1,2,3]), a parameter (:param),
    // or a subquery. Only estimate when the value is early-calculable.
    var rightExpr = ic.getRightMathExpression();
    if (rightExpr == null || !rightExpr.isEarlyCalculated(ctx)) {
      // Try input parameter fallback
      if (ic.getRightParam() != null) {
        var paramValue = ic.getRightParam().getValue(ctx.getInputParameters());
        if (paramValue instanceof Collection<?> coll) {
          return SelectivityEstimator.estimateIn(stats, histogram, coll);
        }
      }
      return -1;
    }
    var value = rightExpr.execute((Result) null, ctx);
    if (value instanceof Collection<?> coll) {
      return SelectivityEstimator.estimateIn(stats, histogram, coll);
    }
    return -1;
  }

  /**
   * Returns true if the expression is a simple field reference matching
   * the given index field name. Uses {@code getDefaultAlias().getStringValue()}
   * to compare the unquoted identifier, avoiding mismatches when the query
   * uses backtick-quoted field names (e.g., {@code `myField`}).
   */
  private static boolean matchesField(SQLExpression expr, String indexField) {
    return expr.isBaseIdentifier()
        && indexField.equals(expr.getDefaultAlias().getStringValue());
  }

  public List<SQLAndBlock> flatten(CommandContext ctx, SchemaClassInternal schemaClass) {
    if (this.baseExpression == null) {
      return Collections.emptyList();
    }
    if (flattened == null) {
      flattened = this.baseExpression.flatten(ctx, schemaClass);
    }
    // TODO remove false conditions (contraddictions)
    return flattened;
  }

  public boolean needsAliases(Set<String> aliases) {
    return this.baseExpression.needsAliases(aliases);
  }

  public void setBaseExpression(SQLBooleanExpression baseExpression) {
    this.baseExpression = baseExpression;
  }

  @Override
  public SQLWhereClause copy() {
    var result = new SQLWhereClause(-1);
    result.baseExpression = baseExpression.copy();
    result.flattened =
        Optional.ofNullable(flattened)
            .map(
                oAndBlocks -> {
                  try (var stream = oAndBlocks.stream()) {
                    return stream.map(SQLAndBlock::copy).collect(Collectors.toList());
                  }
                })
            .orElse(null);
    return result;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }

    var that = (SQLWhereClause) o;

    if (!Objects.equals(baseExpression, that.baseExpression)) {
      return false;
    }
    return Objects.equals(flattened, that.flattened);
  }

  @Override
  public int hashCode() {
    int result = Optional.ofNullable(baseExpression).map(Object::hashCode).orElse(0);
    result = 31 * result + (Optional.ofNullable(flattened).map(List::hashCode).orElse(0));
    return result;
  }

  public void extractSubQueries(SubQueryCollector collector) {
    if (baseExpression != null) {
      baseExpression.extractSubQueries(collector);
    }
    flattened = null;
  }

  public boolean refersToParent() {
    return baseExpression != null && baseExpression.refersToParent();
  }

  public SQLBooleanExpression getBaseExpression() {
    return baseExpression;
  }

  public List<SQLAndBlock> getFlattened() {
    return flattened;
  }

  public void setFlattened(List<SQLAndBlock> flattened) {
    this.flattened = flattened;
  }

  public Result serialize(DatabaseSessionEmbedded session) {
    var result = new ResultInternal(session);
    if (baseExpression != null) {
      result.setProperty("baseExpression", baseExpression.serialize(session));
    }
    if (flattened != null) {
      try (var stream = flattened.stream()) {
        result.setProperty(
            "flattened",
            stream.map(oAndBlock -> oAndBlock.serialize(session)).collect(Collectors.toList()));
      }
    }
    return result;
  }

  public void deserialize(Result fromResult) {
    if (fromResult.getProperty("baseExpression") != null) {
      baseExpression =
          SQLBooleanExpression.deserializeFromOResult(fromResult.getProperty("baseExpression"));
    }
    if (fromResult.getProperty("flattened") != null) {
      List<Result> ser = fromResult.getProperty("flattened");
      flattened = new ArrayList<>();
      for (var r : ser) {
        var block = new SQLAndBlock(-1);
        block.deserialize(r);
        flattened.add(block);
      }
    }
  }

  public boolean isCacheable(DatabaseSessionEmbedded session) {
    return baseExpression.isCacheable(session);
  }

  @Nullable
  public IndexCandidate findIndex(IndexFinder info, CommandContext ctx) {
    return this.baseExpression.findIndex(info, ctx);
  }

  /**
   * If this WHERE clause is exactly {@code @class = 'ClassName'} (or the reversed
   * form {@code 'ClassName' = @class}), returns the class name. Otherwise returns null.
   *
   * <p>Used by the predicate push-down optimizer to resolve a class filter into
   * collection (cluster) IDs that can be checked against the RID before loading
   * the record from storage — zero disk I/O for non-matching vertices.
   */
  @Nullable
  public String extractClassEqualityName() {
    var result = extractAndRemoveClassEquality();
    return result != null ? result.className() : null;
  }


  /**
   * Result of extracting a {@code @class = 'X'} condition from a WHERE clause.
   *
   * @param className the extracted class name
   * @param remainingWhere the WHERE clause with the class condition removed,
   *     or {@code null} if the class condition was the only condition
   */
  public record ClassExtractionResult(
      String className, @Nullable SQLWhereClause remainingWhere) {
  }

  /**
   * Extracts a {@code @class = 'ClassName'} condition from this WHERE clause,
   * handling both simple and compound AND forms:
   * <ul>
   *   <li>{@code WHERE @class = 'Post'} → className="Post", remainingWhere=null
   *   <li>{@code WHERE @class = 'Post' AND x > 5} → className="Post",
   *       remainingWhere="x > 5"
   *   <li>{@code WHERE x > 5} → returns null
   * </ul>
   *
   * @return extraction result, or {@code null} if no class equality is found
   */
  @Nullable
  public ClassExtractionResult extractAndRemoveClassEquality() {
    if (baseExpression == null) {
      return null;
    }

    // Unwrap OrBlock → AndBlock (must be single OR branch)
    var expr = baseExpression;
    if (expr instanceof SQLOrBlock orBlock) {
      if (orBlock.subBlocks.size() != 1) {
        return null;
      }
      expr = orBlock.subBlocks.getFirst();
    }
    if (!(expr instanceof SQLAndBlock andBlock)) {
      return null;
    }

    // Scan AND terms for @class = 'X'
    for (var idx = 0; idx < andBlock.subBlocks.size(); idx++) {
      var className = tryExtractClassFromTerm(andBlock.subBlocks.get(idx));
      if (className != null) {
        if (andBlock.subBlocks.size() == 1) {
          return new ClassExtractionResult(className, null);
        }
        var remaining = buildWhereWithout(andBlock, idx);
        return new ClassExtractionResult(className, remaining);
      }
    }
    return null;
  }

  /**
   * Checks if a single AND term (possibly wrapped in a non-negated NotBlock)
   * is {@code @class = 'X'}. Returns the class name or null.
   */
  @Nullable
  private static String tryExtractClassFromTerm(SQLBooleanExpression term) {
    if (term instanceof SQLNotBlock notBlock) {
      if (notBlock.negate) {
        return null;
      }
      term = notBlock.sub;
    }
    if (!(term instanceof SQLBinaryCondition cond)) {
      return null;
    }
    if (!(cond.operator instanceof SQLEqualsOperator)) {
      return null;
    }
    var name = tryExtractClassName(cond.left, cond.right);
    return name != null ? name : tryExtractClassName(cond.right, cond.left);
  }

  /**
   * Builds a new WHERE clause from the AND block with the term at
   * {@code skipIdx} removed. Public entry point for cross-package callers
   * (e.g. MATCH planner stripping NOT IN conditions).
   *
   * <p>Returns {@code null} when the AND block has only one term (removing
   * it would leave an empty WHERE clause).
   *
   * <p>The returned clause is a deep copy — its sub-blocks do not share
   * instances with the source {@code andBlock}. This keeps the stripped
   * filter independent from anything the caller retained a reference to
   * (e.g. the removed term cached for runtime fallback), so subsequent
   * AST rewrites on either side cannot corrupt the other.
   */
  @Nullable
  public static SQLWhereClause buildWhereWithoutTerm(
      SQLAndBlock andBlock, int skipIdx) {
    if (andBlock.subBlocks.size() <= 1) {
      return null;
    }
    return buildWhereWithout(andBlock, skipIdx);
  }

  private static SQLWhereClause buildWhereWithout(
      SQLAndBlock andBlock, int skipIdx) {
    var newAnd = new SQLAndBlock(-1);
    for (var i = 0; i < andBlock.subBlocks.size(); i++) {
      if (i != skipIdx) {
        newAnd.subBlocks.add(andBlock.subBlocks.get(i).copy());
      }
    }
    var newOr = new SQLOrBlock(-1);
    newOr.subBlocks.add(newAnd);
    var where = new SQLWhereClause(-1);
    where.baseExpression = newOr;
    return where;
  }

  /**
   * Result of splitting a WHERE clause by {@code $parent} references.
   *
   * @param parentReferencing conditions that reference {@code $parent},
   *     or {@code null} if none do
   * @param nonParentReferencing conditions that do not reference {@code $parent},
   *     or {@code null} if all conditions reference {@code $parent}
   */
  public record ParentSplitResult(
      @Nullable SQLWhereClause parentReferencing,
      @Nullable SQLWhereClause nonParentReferencing) {
  }

  /**
   * Splits this WHERE clause into conditions that reference {@code $parent} and
   * conditions that do not. Only works on single-OR-branch AND blocks.
   *
   * <ul>
   *   <li>{@code WHERE a > 5 AND out('X').@rid = $parent.$current.@rid}
   *       → nonParent="a > 5", parent="out('X').@rid = $parent.$current.@rid"
   *   <li>{@code WHERE a > 5} → returns null (no $parent references, no split needed)
   *   <li>{@code WHERE out('X').@rid = $parent.$current.@rid} → nonParent=null,
   *       parent=the whole clause
   * </ul>
   *
   * @return split result, or {@code null} if the clause does not reference
   *     {@code $parent} at all (the caller should use the clause as-is for push-down)
   */
  @Nullable
  public ParentSplitResult splitByParentReference() {
    if (baseExpression == null || !baseExpression.refersToParent()) {
      return null;
    }

    var expr = baseExpression;
    if (expr instanceof SQLOrBlock orBlock) {
      if (orBlock.subBlocks.size() != 1) {
        return new ParentSplitResult(this, null);
      }
      expr = orBlock.subBlocks.getFirst();
    }
    if (!(expr instanceof SQLAndBlock andBlock)) {
      return new ParentSplitResult(this, null);
    }
    if (andBlock.subBlocks.size() < 2) {
      return new ParentSplitResult(this, null);
    }

    List<Integer> parentIndices = new ArrayList<>();
    List<Integer> nonParentIndices = new ArrayList<>();
    for (var i = 0; i < andBlock.subBlocks.size(); i++) {
      if (andBlock.subBlocks.get(i).refersToParent()) {
        parentIndices.add(i);
      } else {
        nonParentIndices.add(i);
      }
    }

    if (nonParentIndices.isEmpty()) {
      return new ParentSplitResult(this, null);
    }

    var parentWhere = parentIndices.isEmpty()
        ? null : buildWhereWith(andBlock, parentIndices);
    var nonParentWhere = buildWhereWith(andBlock, nonParentIndices);
    return new ParentSplitResult(parentWhere, nonParentWhere);
  }

  /**
   * Result of splitting a WHERE clause by {@code $matched} references.
   *
   * @param matchedReferencing    conditions that reference {@code $matched}
   * @param nonMatchedReferencing conditions that do NOT reference {@code $matched}
   */
  public record MatchedSplitResult(
      @Nullable SQLWhereClause matchedReferencing,
      @Nullable SQLWhereClause nonMatchedReferencing) {
  }

  /**
   * Splits this WHERE clause into conditions that reference {@code $matched}
   * and conditions that do not. Only works on single-OR-branch AND blocks.
   *
   * <p>Analogous to {@link #splitByParentReference()} but uses
   * {@link SQLBooleanExpression#getMatchPatternInvolvedAliases()} to detect
   * {@code $matched} references.
   *
   * @return split result, or {@code null} if the clause does not reference
   *     {@code $matched} at all
   */
  @Nullable
  public MatchedSplitResult splitByMatchedReference() {
    if (baseExpression == null) {
      return null;
    }
    var involved = baseExpression.getMatchPatternInvolvedAliases();
    if (involved == null || involved.isEmpty()) {
      return null;
    }

    var expr = baseExpression;
    if (expr instanceof SQLOrBlock orBlock) {
      if (orBlock.subBlocks.size() != 1) {
        return new MatchedSplitResult(this, null);
      }
      expr = orBlock.subBlocks.getFirst();
    }
    if (!(expr instanceof SQLAndBlock andBlock)) {
      return new MatchedSplitResult(this, null);
    }
    if (andBlock.subBlocks.size() < 2) {
      return new MatchedSplitResult(this, null);
    }

    List<Integer> matchedIndices = new ArrayList<>();
    List<Integer> nonMatchedIndices = new ArrayList<>();
    for (var i = 0; i < andBlock.subBlocks.size(); i++) {
      var aliases = andBlock.subBlocks.get(i).getMatchPatternInvolvedAliases();
      if (aliases != null && !aliases.isEmpty()) {
        matchedIndices.add(i);
      } else {
        nonMatchedIndices.add(i);
      }
    }

    if (nonMatchedIndices.isEmpty()) {
      return new MatchedSplitResult(this, null);
    }

    var matchedWhere = matchedIndices.isEmpty()
        ? null : buildWhereWith(andBlock, matchedIndices);
    var nonMatchedWhere = buildWhereWith(andBlock, nonMatchedIndices);
    return new MatchedSplitResult(matchedWhere, nonMatchedWhere);
  }

  /**
   * Extracts the subset of AND conditions that flatten to a single OR branch.
   * Conditions involving graph navigation functions (e.g. {@code out('X').name
   * CONTAINS :val}) may flatten to multiple OR branches, which prevents index
   * lookup. This method separates the "simple" conditions (single-branch
   * flatten) from the rest so that the simple subset can be used for index
   * pre-filtering while the full WHERE remains as a post-filter.
   *
   * @param ctx         command context (needed for flatten evaluation)
   * @param schemaClass the target schema class (needed for flatten evaluation)
   * @return a WHERE clause containing only the single-branch-flattening
   *     conditions, or {@code null} if none exist or if the clause is not a
   *     single AND block
   */
  @Nullable
  public SQLWhereClause extractIndexablePart(
      CommandContext ctx, SchemaClassInternal schemaClass) {
    var expr = baseExpression;
    if (expr instanceof SQLOrBlock orBlock) {
      if (orBlock.subBlocks.size() != 1) {
        return null;
      }
      expr = orBlock.subBlocks.getFirst();
    }
    if (!(expr instanceof SQLAndBlock andBlock)) {
      return null;
    }
    if (andBlock.subBlocks.size() < 2) {
      return null;
    }

    List<Integer> indexableIndices = new ArrayList<>();
    for (var i = 0; i < andBlock.subBlocks.size(); i++) {
      var sub = andBlock.subBlocks.get(i);
      // A condition is "indexable" if it flattens to exactly one OR branch.
      var subFlat = sub.flatten(ctx, schemaClass);
      if (subFlat.size() == 1) {
        indexableIndices.add(i);
      }
    }

    if (indexableIndices.isEmpty()
        || indexableIndices.size() == andBlock.subBlocks.size()) {
      // Either nothing is indexable, or everything is (the caller already
      // tried the full WHERE — no point retrying the same thing).
      return null;
    }

    return buildWhereWith(andBlock, indexableIndices);
  }

  /**
   * Builds a new WHERE clause from the AND block containing only the terms
   * at the specified indices.
   *
   * <p>N.B. the returned clause shares sub-block instances with the
   * source {@code andBlock} — callers must not mutate the result.
   */
  private static SQLWhereClause buildWhereWith(
      SQLAndBlock andBlock, List<Integer> indices) {
    var newAnd = new SQLAndBlock(-1);
    for (var idx : indices) {
      newAnd.subBlocks.add(andBlock.subBlocks.get(idx));
    }
    var newOr = new SQLOrBlock(-1);
    newOr.subBlocks.add(newAnd);
    var where = new SQLWhereClause(-1);
    where.baseExpression = newOr;
    return where;
  }

  /**
   * Non-destructive version of {@link #extractAndRemoveRidEquality()}: finds a
   * {@code @rid = <expr>} condition in this WHERE clause without modifying it.
   *
   * @return the value-side expression, or {@code null} if no RID equality is found
   */
  @Nullable
  public SQLExpression findRidEquality() {
    if (baseExpression == null) {
      return null;
    }
    return findRidInExpression(baseExpression);
  }

  /**
   * Recursively searches for {@code @rid = <expr>} in a possibly nested
   * AND/OR structure. Handles the double-nesting created by
   * {@code addAliases()} in {@code MatchExecutionPlanner}, where compound
   * WHERE clauses like {@code @rid = #23:1 AND name = 'bob'} are wrapped
   * in an extra AND layer.
   */
  @Nullable
  private static SQLExpression findRidInExpression(SQLBooleanExpression expr) {
    if (expr instanceof SQLOrBlock orBlock) {
      if (orBlock.subBlocks.size() != 1) {
        return null;
      }
      expr = orBlock.subBlocks.getFirst();
    }
    if (expr instanceof SQLAndBlock andBlock) {
      for (var sub : andBlock.subBlocks) {
        var ridExpr = tryExtractRidFromTerm(sub);
        if (ridExpr != null) {
          return ridExpr;
        }
        // sub might be a nested AND/OR wrapping the compound condition —
        // recurse to flatten it
        ridExpr = findRidInExpression(sub);
        if (ridExpr != null) {
          return ridExpr;
        }
      }
    }
    return null;
  }

  /**
   * Result of extracting a {@code @rid = <expr>} condition from a WHERE clause.
   *
   * @param ridExpression the value-side expression (literal, parameter, etc.)
   * @param remainingWhere the WHERE clause with the RID condition removed,
   *     or {@code null} if the RID condition was the only condition
   */
  public record RidExtractionResult(
      SQLExpression ridExpression, @Nullable SQLWhereClause remainingWhere) {
  }

  /**
   * Extracts a {@code @rid = <expr>} condition from this WHERE clause,
   * handling both simple and compound AND forms:
   * <ul>
   *   <li>{@code WHERE @rid = #23:1} → ridExpression="#23:1", remainingWhere=null
   *   <li>{@code WHERE @rid = :param AND x > 5} → ridExpression=":param",
   *       remainingWhere="x > 5"
   *   <li>{@code WHERE x > 5} → returns null
   * </ul>
   *
   * @return extraction result, or {@code null} if no RID equality is found
   */
  @Nullable
  public RidExtractionResult extractAndRemoveRidEquality() {
    if (baseExpression == null) {
      return null;
    }

    var expr = baseExpression;
    if (expr instanceof SQLOrBlock orBlock) {
      if (orBlock.subBlocks.size() != 1) {
        return null;
      }
      expr = orBlock.subBlocks.getFirst();
    }
    if (!(expr instanceof SQLAndBlock andBlock)) {
      return null;
    }

    for (var idx = 0; idx < andBlock.subBlocks.size(); idx++) {
      var ridExpr = tryExtractRidFromTerm(andBlock.subBlocks.get(idx));
      if (ridExpr != null) {
        if (andBlock.subBlocks.size() == 1) {
          return new RidExtractionResult(ridExpr, null);
        }
        var remaining = buildWhereWithout(andBlock, idx);
        return new RidExtractionResult(ridExpr, remaining);
      }
    }
    return null;
  }

  /**
   * Checks if a single AND term (possibly wrapped in a single-element OrBlock
   * and/or a non-negated NotBlock) is {@code @rid = <expr>}. Returns the
   * value-side expression or null.
   */
  @Nullable
  private static SQLExpression tryExtractRidFromTerm(SQLBooleanExpression term) {
    // Unwrap single-element wrapper blocks. The parser produces deeply nested
    // structures like OrBlock(AndBlock(OrBlock(BinaryCondition))) even for
    // simple conditions. Peel off single-element OrBlock and AndBlock wrappers
    // until we reach the actual condition.
    while (true) {
      if (term instanceof SQLOrBlock orBlock) {
        if (orBlock.subBlocks.size() != 1) {
          return null;
        }
        term = orBlock.subBlocks.getFirst();
      } else if (term instanceof SQLAndBlock andBlock) {
        if (andBlock.subBlocks.size() != 1) {
          return null;
        }
        term = andBlock.subBlocks.getFirst();
      } else {
        break;
      }
    }
    assert !(term instanceof SQLOrBlock) && !(term instanceof SQLAndBlock)
        : "tryExtractRidFromTerm: loop should have unwrapped all single-element wrappers";
    if (term instanceof SQLNotBlock notBlock) {
      if (notBlock.negate) {
        return null;
      }
      term = notBlock.sub;
    }
    if (!(term instanceof SQLBinaryCondition cond)) {
      return null;
    }
    if (!(cond.operator instanceof SQLEqualsOperator)) {
      return null;
    }
    var result = tryExtractRidValue(cond.left, cond.right);
    return result != null ? result : tryExtractRidValue(cond.right, cond.left);
  }

  /**
   * Checks if {@code attrSide} is a bare {@code @rid} record attribute.
   * Returns the {@code valueSide} expression if so, or null.
   */
  @Nullable
  private static SQLExpression tryExtractRidValue(
      SQLExpression attrSide, SQLExpression valueSide) {
    if (!(attrSide.mathExpression instanceof SQLBaseExpression attrBase)) {
      return null;
    }
    var ident = attrBase.getIdentifier();
    if (ident == null || ident.getSuffix() == null
        || ident.getSuffix().recordAttribute == null
        || attrBase.getModifier() != null) {
      return null;
    }
    if (!"@rid".equalsIgnoreCase(
        ident.getSuffix().recordAttribute.getName())) {
      return null;
    }
    return valueSide;
  }

  /**
   * Result of extracting an {@code out/in('EdgeClass').@rid = <expr>} condition.
   *
   * @param edgeClassName the edge class name (e.g. "HAS_CREATOR")
   * @param traversalDirection the direction of the original traversal (OUT or IN)
   * @param targetRidExpression the expression for the target RID (literal,
   *     parameter, or $parent reference)
   * @param remainingWhere the WHERE with the edge-RID condition removed,
   *     or {@code null} if it was the only condition
   */
  public record EdgeRidLookupExtractionResult(
      String edgeClassName,
      String traversalDirection,
      SQLExpression targetRidExpression,
      @Nullable SQLWhereClause remainingWhere) {
  }

  /**
   * Extracts an {@code out/in('EdgeClass').@rid = <expr>} condition from this
   * WHERE clause. Recognizes the AST pattern where a graph function call
   * ({@code out} or {@code in}) with a single string parameter is followed by
   * a {@code .@rid} suffix, compared via equality.
   *
   * @return extraction result, or {@code null} if no matching condition is found
   */
  @Nullable
  public EdgeRidLookupExtractionResult extractAndRemoveEdgeRidLookup() {
    if (baseExpression == null) {
      return null;
    }

    var expr = baseExpression;
    if (expr instanceof SQLOrBlock orBlock) {
      if (orBlock.subBlocks.size() != 1) {
        return null;
      }
      expr = orBlock.subBlocks.getFirst();
    }
    if (!(expr instanceof SQLAndBlock andBlock)) {
      return null;
    }

    for (var idx = 0; idx < andBlock.subBlocks.size(); idx++) {
      var info = tryExtractEdgeRidFromTerm(andBlock.subBlocks.get(idx));
      if (info != null) {
        SQLWhereClause remaining = andBlock.subBlocks.size() == 1
            ? null : buildWhereWithout(andBlock, idx);
        return new EdgeRidLookupExtractionResult(
            info.edgeClassName, info.direction, info.targetRidExpr, remaining);
      }
    }
    return null;
  }

  private record EdgeRidTermInfo(
      String edgeClassName, String direction, SQLExpression targetRidExpr) {
  }

  @Nullable
  private static EdgeRidTermInfo tryExtractEdgeRidFromTerm(SQLBooleanExpression term) {
    if (term instanceof SQLNotBlock notBlock) {
      if (notBlock.negate) {
        return null;
      }
      term = notBlock.sub;
    }
    if (!(term instanceof SQLBinaryCondition cond)) {
      return null;
    }
    if (!(cond.operator instanceof SQLEqualsOperator)) {
      return null;
    }
    var info = tryExtractEdgeRidSide(cond.left, cond.right);
    return info != null ? info : tryExtractEdgeRidSide(cond.right, cond.left);
  }

  /**
   * Checks if {@code methodSide} is {@code out/in('EdgeClass').@rid} and
   * returns the edge class name, direction, and value expression.
   */
  @Nullable
  private static EdgeRidTermInfo tryExtractEdgeRidSide(
      SQLExpression methodSide, SQLExpression valueSide) {
    if (!(methodSide.mathExpression instanceof SQLBaseExpression baseExpr)) {
      return null;
    }
    var ident = baseExpr.getIdentifier();
    if (ident == null || ident.getLevelZero() == null) {
      return null;
    }
    var funcCall = ident.getLevelZero().getFunctionCall();
    if (funcCall == null) {
      return null;
    }
    var funcName = funcCall.getName().getStringValue();
    if (!"out".equalsIgnoreCase(funcName) && !"in".equalsIgnoreCase(funcName)) {
      return null;
    }
    if (funcCall.getParams().size() != 1) {
      return null;
    }

    var edgeClassName = extractStringLiteral(funcCall.getParams().getFirst());
    if (edgeClassName == null) {
      return null;
    }

    var modifier = baseExpr.getModifier();
    if (modifier == null || modifier.suffix == null
        || modifier.suffix.recordAttribute == null) {
      return null;
    }
    if (!"@rid".equalsIgnoreCase(modifier.suffix.recordAttribute.getName())) {
      return null;
    }
    if (modifier.next != null) {
      return null;
    }

    return new EdgeRidTermInfo(edgeClassName, funcName.toLowerCase(), valueSide);
  }

  @Nullable
  private static String extractStringLiteral(SQLExpression expr) {
    if (!(expr.mathExpression instanceof SQLBaseExpression base)) {
      return null;
    }
    if (base.string == null || base.getModifier() != null) {
      return null;
    }
    var raw = base.string;
    if (raw.length() >= 2
        && ((raw.startsWith("\"") && raw.endsWith("\""))
            || (raw.startsWith("'") && raw.endsWith("'")))) {
      return raw.substring(1, raw.length() - 1);
    }
    return raw;
  }

  /**
   * Checks if {@code attrSide} is a bare {@code @class} record attribute and
   * {@code valueSide} is a string literal. Returns the unquoted class name or null.
   */
  @Nullable
  private static String tryExtractClassName(SQLExpression attrSide, SQLExpression valueSide) {
    if (!(attrSide.mathExpression instanceof SQLBaseExpression attrBase)) {
      return null;
    }
    var ident = attrBase.getIdentifier();
    if (ident == null || ident.getSuffix() == null
        || ident.getSuffix().recordAttribute == null
        || attrBase.getModifier() != null) {
      return null;
    }
    if (!"@class".equalsIgnoreCase(
        ident.getSuffix().recordAttribute.getName())) {
      return null;
    }

    if (!(valueSide.mathExpression instanceof SQLBaseExpression valBase)) {
      return null;
    }
    if (valBase.string == null || valBase.getModifier() != null) {
      return null;
    }

    // The string literal is stored with surrounding quotes: "\"X\"" or "'X'"
    var raw = valBase.string;
    if (raw.length() >= 2
        && ((raw.startsWith("\"") && raw.endsWith("\""))
            || (raw.startsWith("'") && raw.endsWith("'")))) {
      return raw.substring(1, raw.length() - 1);
    }
    return raw;
  }
}
/* JavaCC - OriginalChecksum=e8015d01ce1ab2bc337062e9e3f2603e (do not edit this line) */
