package com.jetbrains.youtrackdb.junit;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertNull;
import static org.junit.jupiter.api.Assertions.assertTrue;
import static org.junit.jupiter.api.Assertions.fail;

import com.jetbrains.youtrackdb.internal.core.db.DatabaseSessionEmbedded;
import com.jetbrains.youtrackdb.internal.core.db.record.record.DBRecord;
import com.jetbrains.youtrackdb.internal.core.db.record.record.Identifiable;
import com.jetbrains.youtrackdb.internal.core.index.CompositeKey;
import com.jetbrains.youtrackdb.internal.core.metadata.schema.schema.PropertyType;
import com.jetbrains.youtrackdb.internal.core.metadata.schema.schema.Schema;
import com.jetbrains.youtrackdb.internal.core.metadata.schema.schema.SchemaClass;
import com.jetbrains.youtrackdb.internal.core.record.impl.EntityImpl;
import java.util.Date;
import java.util.Set;
import org.junit.jupiter.api.Order;
import org.junit.jupiter.api.Test;

/**
 * Tests for schema property default values.
 *
 * @since 3/3/2015
 */
public class DefaultValuesTrivialTest extends BaseDBJUnit5Test {

  private static final int DOCUMENT_COUNT = 50;

  @Test
  @Order(1)
  void test() {
    // create example schema
    Schema schema = session.getMetadata().getSchema();
    var classPerson = schema.createClass("PersonA");

    classPerson.createProperty("name", PropertyType.STRING);
    classPerson.createProperty("join_date", PropertyType.DATETIME)
        .setDefaultValue("sysdate()");
    classPerson.createProperty("active", PropertyType.BOOLEAN)
        .setDefaultValue("true");

    session.begin();
    var dtStart = getDatabaseSysdate(session);

    var docs = new EntityImpl[DOCUMENT_COUNT];
    for (var i = 0; i < DOCUMENT_COUNT; ++i) {
      var doc = ((EntityImpl) session.newEntity("PersonA"));
      doc.setProperty("name", "autoGeneratedName #" + i);

      docs[i] = doc;
    }
    session.commit();

    final var tx = session.begin();
    var dtAfter = getDatabaseSysdate(session);

    for (var i = 0; i < DOCUMENT_COUNT; ++i) {
      final var doc = tx.loadEntity(docs[i].getIdentity());

      try {
        //
        var dt = doc.getDateTime("join_date");

        var isInRange = !dt.before(dtStart) && !dt.after(dtAfter);
        assertTrue(isInRange);

        //
        boolean active = doc.getBoolean("active");
        assertTrue(active);
      } catch (Exception ex) {
        ex.printStackTrace();
        fail();
      }
    }
    session.commit();
  }

  private static Date getDatabaseSysdate(DatabaseSessionEmbedded database) {
    return database.computeInTx(transaction -> {
      try (var dates = transaction.query("SELECT sysdate() as sysdate")) {
        return dates.next().getProperty("sysdate");
      }
    });
  }

  @Test
  @Order(2)
  void testDefaultValueConversion() {
    session.begin();
    final var userId = session.getCurrentUser().getIdentity();
    session.commit();

    Schema schema = session.getMetadata().getSchema();

    var classPerson = schema.createClass("PersonB");
    classPerson.createProperty("users", PropertyType.LINKSET)
        .setDefaultValue("[" + userId + "]");

    session.begin();
    var doc = ((EntityImpl) session.newEntity("PersonB"));
    var record = (DBRecord) doc;
    session.commit();

    session.begin();
    EntityImpl doc1 = session.load(record.getIdentity());
    Set<Identifiable> rids = doc1.getProperty("users");
    assertEquals(1, rids.size());
    assertEquals(userId, rids.iterator().next());
    session.commit();
  }

  @Test
  @Order(3)
  void testPrepopulation() {
    // create example schema
    Schema schema = session.getMetadata().getSchema();
    var classA = schema.createClass("ClassA");

    classA.createProperty("name", PropertyType.STRING)
        .setDefaultValue("default name");
    classA.createProperty("date", PropertyType.DATETIME)
        .setDefaultValue("sysdate()");
    classA.createProperty("active", PropertyType.BOOLEAN)
        .setDefaultValue("true");

    session.executeInTx(tx -> {
      var doc = ((EntityImpl) session.newEntity(classA));
      assertEquals("default name", doc.getProperty("name"));
      assertNotNull(doc.getProperty("date"));
      assertTrue((Boolean) doc.getProperty("active"));
    });

    session.executeInTx(tx -> {
      var doc = ((EntityImpl) session.newEntity(classA.getName()));
      assertEquals("default name", doc.getProperty("name"));
      assertNotNull(doc.getProperty("date"));
      assertTrue((Boolean) doc.getProperty("active"));
    });

    session.executeInTx(tx -> {
      var doc = ((EntityImpl) session.newEntity());
      assertNull(doc.getProperty("name"));
      assertNull(doc.getProperty("date"));
      assertNull(doc.getProperty("active"));
      doc.setClassNameIfExists(classA.getName());
      assertEquals("default name", doc.getProperty("name"));
      assertNotNull(doc.getProperty("date"));
      assertTrue((Boolean) doc.getProperty("active"));
    });
  }

  @Test
  @Order(4)
  void testPrepopulationIndex() {
    // create example schema
    Schema schema = session.getMetadata().getSchema();
    var classB = schema.createClass("ClassB");

    var prop = classB.createProperty("name", PropertyType.STRING);
    prop.setDefaultValue("default name");
    prop.createIndex(SchemaClass.INDEX_TYPE.NOTUNIQUE);

    session.executeInTx(tx -> {
      var doc = ((EntityImpl) session.newEntity(classB));
      assertEquals("default name", doc.getProperty("name"));
    });

    session.begin();
    try (var stream = session.getIndex("ClassB.name")
        .getRids(session, "default name")) {
      assertEquals(1, stream.count());
    }
    session.rollback();
  }

  @Test
  @Order(5)
  void testPrepopulationMultivalueIndex() {
    // create example schema
    Schema schema = session.getMetadata().getSchema();
    var classD = schema.createClass("ClassD");

    var prop = classD.createProperty("name", PropertyType.STRING);
    prop.setDefaultValue("default name");
    classD.createProperty("value", PropertyType.STRING);
    classD.createIndex("multi", SchemaClass.INDEX_TYPE.NOTUNIQUE, "value",
        "name");
    var index = session.getIndex("multi");

    {
      session.begin();
      var doc = ((EntityImpl) session.newEntity(classD));
      assertEquals("default name", doc.getProperty("name"));
      doc.setProperty("value", "1");

      session.commit();

      session.begin();
      try (var stream = index.getRids(session, new CompositeKey("1"))) {
        assertEquals(1, stream.count());
      }
      session.rollback();
    }
    {
      session.begin();
      var doc = ((EntityImpl) session.newEntity(classD));
      assertEquals("default name", doc.getProperty("name"));
      doc.setProperty("value", "2");

      session.commit();

      session.begin();
      try (var stream = index.getRids(session, new CompositeKey("2"))) {
        assertEquals(1, stream.count());
      }
      session.rollback();
    }
    session.begin();
    try (var stream = index.getRids(session, new CompositeKey("3"))) {
      assertEquals(0, stream.count());
    }
    session.rollback();
  }
}
