/*
 *
 *
 *  *
 *  *  Licensed under the Apache License, Version 2.0 (the "License");
 *  *  you may not use this file except in compliance with the License.
 *  *  You may obtain a copy of the License at
 *  *
 *  *       http://www.apache.org/licenses/LICENSE-2.0
 *  *
 *  *  Unless required by applicable law or agreed to in writing, software
 *  *  distributed under the License is distributed on an "AS IS" BASIS,
 *  *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  *  See the License for the specific language governing permissions and
 *  *  limitations under the License.
 *  *
 *
 *
 */
package com.jetbrains.youtrackdb.internal.core.tx;

import com.jetbrains.youtrackdb.api.exception.RecordNotFoundException;
import com.jetbrains.youtrackdb.internal.common.profiler.monitoring.QueryMonitoringMode;
import com.jetbrains.youtrackdb.internal.common.profiler.monitoring.TransactionMetricsListener;
import com.jetbrains.youtrackdb.internal.core.db.DatabaseSessionEmbedded;
import com.jetbrains.youtrackdb.internal.core.db.record.RecordOperation;
import com.jetbrains.youtrackdb.internal.core.db.record.record.Identifiable;
import com.jetbrains.youtrackdb.internal.core.db.record.record.RID;
import com.jetbrains.youtrackdb.internal.core.id.RecordIdInternal;
import com.jetbrains.youtrackdb.internal.core.index.Index;
import com.jetbrains.youtrackdb.internal.core.record.RecordAbstract;
import com.jetbrains.youtrackdb.internal.core.storage.impl.local.paginated.RecordSerializationContext;
import com.jetbrains.youtrackdb.internal.core.tx.FrontendTransactionIndexChanges.OPERATION;
import java.util.Collection;
import java.util.List;
import java.util.Map;
import javax.annotation.Nonnull;
import javax.annotation.Nullable;

public interface FrontendTransaction extends Transaction {

  enum TXSTATUS {
    INVALID, BEGUN, COMMITTING, ROLLBACKING, COMPLETED, ROLLED_BACK
  }

  int beginInternal();

  /// Commits the current transaction. The transaction is reentrant: if [#beginInternal()]
  /// has been called several times, the actual storage commit happens only when the same number
  /// of `commitInternal()` calls have been made (i.e., only the outermost commit writes).
  ///
  /// @return a map from temporary RIDs (assigned to new records during the transaction) to their
  ///     final RIDs generated by the storage during commit, or `null` if this was an inner
  ///     (reentrant) commit that did not trigger a storage write.
  @Nullable Map<RID, RID> commitInternal();

  /// Commits the current transaction with transaction metrics collection enabled. Behaves
  /// identically to [#commitInternal()], but additionally captures timing data around the
  /// storage commit and notifies the given listener via
  /// [TransactionMetricsListener#writeTransactionCommitted] for write transactions.
  ///
  /// The listener is only called when the outermost commit actually writes to storage and the
  /// transaction contains write operations. Read-only and reentrant (inner) commits do not
  /// trigger the listener.
  ///
  /// @param listener   the listener to notify after a successful write commit
  /// @param mode       timing precision: [QueryMonitoringMode#LIGHTWEIGHT] uses the approximate
  ///     [com.jetbrains.youtrackdb.internal.common.profiler.Ticker],
  ///     [QueryMonitoringMode#EXACT] uses `System.nanoTime()` and `System.currentTimeMillis()`
  /// @param trackingId eagerly captured tracking ID for this transaction
  /// @return a map from temporary RIDs to final RIDs, or `null` if this was an inner
  ///     (reentrant) commit that did not trigger a storage write.
  @Nullable Map<RID, RID> monitoredCommitInternal(
      @Nonnull TransactionMetricsListener listener,
      @Nonnull QueryMonitoringMode mode,
      @Nonnull String trackingId);

  void rollbackInternal();

  @Override
  @Nonnull
  DatabaseSessionEmbedded getDatabaseSession();

  @Deprecated
  void clearRecordEntries();

  @Nonnull
  RecordAbstract loadRecord(RID rid) throws RecordNotFoundException;

  @Override
  boolean exists(@Nonnull RID rid);

  TXSTATUS getStatus();

  @Deprecated
  Iterable<? extends RecordOperation> getCurrentRecordEntries();

  RecordOperation getRecordEntry(RID rid);

  List<String> getInvolvedIndexes();

  @Deprecated
  void clearIndexEntries();

  void close();

  /**
   * When commit in transaction is performed all new records will change their identity, but index
   * values will contain stale links, to fix them given method will be called for each entry. This
   * update local transaction maps too.
   *
   * @param oldRid Record identity before commit.
   * @param newRid Record identity after commit.
   */
  boolean assertIdentityChangedAfterCommit(final RecordIdInternal oldRid,
      final RecordIdInternal newRid);

  int amountOfNestedTxs();

  int getEntryCount();

  /**
   * @return {@code true} if this transaction is active, {@code false} otherwise.
   */
  @Override
  boolean isActive();

  /**
   * Deletes the given record in this transaction.
   *
   * @param record the record to delete.
   */
  void deleteRecord(RecordAbstract record);

  /**
   * Resolves a record with the given RID in the context of this transaction.
   *
   * @param rid the record RID.
   * @return the resolved record, or {@code null} if no record is found.
   */
  @Nullable RecordAbstract getRecord(RID rid);

  /**
   * Adds the transactional index entry in this transaction.
   *
   * @param index     the index.
   * @param indexName the index name.
   * @param operation the index operation to register.
   * @param key       the index key.
   * @param value     the index key value.
   */
  void addIndexEntry(
      Index index,
      String indexName,
      OPERATION operation,
      Object key,
      Identifiable value);

  /**
   * Obtains the index changes done in the context of this transaction.
   *
   * @param indexName the index name.
   * @return the index changes in question or {@code null} if index is not found.
   */
  @Nullable FrontendTransactionIndexChanges getIndexChanges(String indexName);

  /**
   * Does the same thing as {@link #getIndexChanges(String)}, but handles remote storages in a
   * special way.
   *
   * @param indexName the index name.
   * @return the index changes in question or {@code null} if index is not found or storage is
   * remote.
   */
  @Nullable FrontendTransactionIndexChanges getIndexChangesInternal(String indexName);

  /**
   * Obtains the custom value by its name stored in the context of this transaction.
   *
   * @param name the value name.
   * @return the obtained value or {@code null} if no value found.
   */
  Object getCustomData(String name);

  /**
   * Sets the custom value by its name stored in the context of this transaction.
   *
   * @param name  the value name.
   * @param value the value to store.
   */
  void setCustomData(String name, Object value);

  /**
   * Extract all the record operations for the current transaction
   *
   * @return the record operations, the collection should not be modified.
   */
  Collection<RecordOperation> getRecordOperationsInternal();

  /**
   * Extract all the calculated index operations for the current transaction changes, the key of the
   * map is the index name the value all the changes for the specified index.
   *
   * @return the index changes, the map should not be modified.
   */
  Map<String, FrontendTransactionIndexChanges> getIndexOperations();

  /**
   * Change the status of the transaction.
   */
  void setStatus(final FrontendTransaction.TXSTATUS iStatus);

  void setSession(DatabaseSessionEmbedded session);

  long getId();

  void addRecordOperation(RecordAbstract record, byte status);

  @Nullable RecordIdInternal getNextRidInCollection(@Nonnull RecordIdInternal rid, long upperBoundExclusive);

  @Nullable RecordIdInternal getPreviousRidInCollection(@Nonnull RecordIdInternal rid,
      long lowerBoundInclusive);

  boolean isDeletedInTx(@Nonnull RID rid);

  default void preProcessRecordsAndExecuteCallCallbacks() {
  }

  boolean isCallBackProcessingInProgress();

  boolean isScheduledForCallbackProcessing(RecordIdInternal rid);

  @Nonnull
  RecordSerializationContext getRecordSerializationContext();
}
