apiVersion: 1

datasources:
  - name: InfluxDB
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    jsonData:
      version: Flux
      organization: youtrackdb
      defaultBucket: jmh-benchmarks
    secureJsonData:
      token: ${INFLUXDB_ADMIN_TOKEN}
