package com.jetbrains.youtrackdb.internal.lucene.test;

import com.jetbrains.youtrackdb.api.schema.PropertyType;
import com.jetbrains.youtrackdb.api.schema.Schema;
import com.jetbrains.youtrackdb.internal.core.record.impl.EntityImpl;
import org.junit.Assert;
import org.junit.Before;
import org.junit.Test;

/**
 *
 */
public class LuceneSortTest extends BaseLuceneTest {

  private static final String DESCRIPTION =
      "verylong verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong  verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylongverylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong  verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylongverylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong  verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylongverylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong  verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylongverylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong  verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylongverylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong  verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylongverylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong  verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylongverylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong  verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylongverylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong  verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylongverylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong  verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylongverylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong  verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylongverylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong  verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong verylong"
          + " verylong verylong verylong verylong verylong verylong verylong verylong";

  @Before
  public void setUp() throws Exception {
    Schema schema = session.getMetadata().getSchema();

    var cls = schema.createClass("Person");
    cls.createProperty("name", PropertyType.STRING);
    cls.createProperty("surname", PropertyType.STRING);
    cls.createProperty("description", PropertyType.STRING);
  }

  @Test
  public void shouldIndexVeryLongDescriptionWithWildCardConfig() throws Exception {

    session.begin();
    EntityImpl entity = ((EntityImpl) session.newEntity("Person"));
    entity.setProperty("description", DESCRIPTION);
    session.commit();

    session.execute(
            "create index Person.description on Person(description) FULLTEXT ENGINE LUCENE METADATA"
                + " { \"*_index_sorted\" : false }")
        .close();

    var count =
        session.query("SELECT FROM Person WHERE SEARCH_CLASS(\"verylong\")  = true").stream()
            .count();

    Assert.assertEquals(1, count);
  }

  @Test
  public void shouldIndexVeryLongDescriptionWithSingleField() throws Exception {

    session.begin();
    EntityImpl entity = ((EntityImpl) session.newEntity("Person"));
    entity.setProperty("description", DESCRIPTION);
    session.commit();

    session.execute(
            "create index Person.description on Person(description) FULLTEXT ENGINE LUCENE METADATA"
                + " { \"description_index_sorted\" : false }")
        .close();

    var count =
        session.query("SELECT FROM Person WHERE SEARCH_CLASS(\"verylong\") = true ").stream()
            .count();

    Assert.assertEquals(1, count);
  }
}
